### PR TITLE
Add cache-flush step in Twenty upgrade command  #7521

### LINKED ISSUE #7521: Add cache-flush step in Twenty upgrade command
## Scope & Context

`upgrade-x.xx` commands can sometimes bring migrations to the data model and now that the default cache is redis and persistent we need to make sure to clear it by the end of the command.

## Current behavior

Cache needs to be flushed after we run the upgrade command

## Expected behavior
Cache flush should be part of the global command

## Technical inputs

A command already exists (see FlushCacheCommand) and can be directly added but it's flushing the whole cache. While this could be fine like this, I think we only want to remove keys that follow that pattern `engine:*` and not interact with the rest (bull, module, ...). This command could be updated to take an optional parameter for that purpose.

### PR DESCRIPTION
**Pull request by yadavshubham01**
Fixes: #7521 

Flush Specific Redis Keys After Upgrade Command :----

Changes Made :----
Updated the FlushCacheCommand to allow for selective flushing of keys that match the pattern engine:*, rather than flushing the entire cache.
Added a new optional parameter to specify the cache keys pattern.
Ensured that the cache is flushed at the end of the upgrade command.

Code Changes :----
Modified FlushCacheCommand to include a method for flushing keys by pattern.
Added a new function in CacheStorageService to handle the pattern-based flushing.

### CODE REVIEW

**Review by Weiko — APPROVED** [review]
I've updated the PR to use redis SCAN instead of KEYS as this is the recommended way for large dataset due to the fact that KEYS can block the server.
Thanks for your contribution!

**Review by charlesBochet — APPROVED** [review]
LGTM

**Comment by yadavshubham01** [comment]
@Weiko Thank you for your feedback

**Pull request merged**
