### PR TITLE
fix(front): fix some console errors

### PR DESCRIPTION
**Pull request by zephearmin**
fixes the following console.errors : 

image

image

### CODE REVIEW

**Comment by zephearmin** [comment]
Au final je n'ai pas fait de PR de fix de pixels, elles étaient déjà parties et j'ai vu ces erreurs en lançant le projet alors je me suis dit lets go haha 

merci d'avoir pris @bosiraphael  :)

**Comment by bosiraphael** [comment]
Hello @zephearmin ! Good idea ! There are two typescript errors inside `ObjectFilterDropdownSearchInput` and `ObjectFilterDropdownTextSearchInput` because we're trying to pass a ref ;) Maybe it should be `ComponentPropsWithRef`?

**Comment by zephearmin** [comment]
> Hello @zephearmin ! Good idea ! There are two typescript errors inside `ObjectFilterDropdownSearchInput` and `ObjectFilterDropdownTextSearchInput` because we're trying to pass a ref ;) Maybe it should be `ComponentPropsWithRef`?

Yeah sorry for missing those, they're removed :)

**Comment by zephearmin** [comment]
Sorry for the many commits btw, I left my station and vscode.dev is amazing but lacks the tools I'm used to :D

**Comment by ehconitin** [comment]
@zephearmin
There was a ref being passed to `DropdownMenuSearchInput`, which was changed in #6906. That ref handled the focus and selection of the input, so instead of removing those props, we should figure out a way to either use refs conditionally or merge them! For your context, those props you removed were added in PR #6449.

:)

**Pull request closed without merging**
