### PR TITLE
ossgg: Self-host guide and Article

### PR DESCRIPTION
**Pull request by harshsbhat**
## What does this PR do?

Wrote an article and self-host guide for Twenty CRM:

Article:
https://www.harshbhat.me/blog/twenty-crm

Self-host guide:
https://www.harshbhat.me/blog/twenty-self-host

POINTS:
1500

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
Thank you @harshsbhat :)

**Comment by charlesBochet** [comment]
I'm awarding 500 for each based on the length :)

**Comment by harshsbhat** [comment]
sure not an issue @charlesBochet

**Pull request merged**
