### PR TITLE
E2E tests

### PR DESCRIPTION
**Pull request by BOHEUS**
Continuation of #6644 

Now chromium browser is used in workspaces tests instead of firefox and screenshots after each test are properly saved in one folder when run from IDE and from terminal using `yarn test:e2e` command

### CODE REVIEW

**Review by lucasbordeau — COMMENTED** [review]
Login doesn't work : 

Capture d’écran 2024-08-23 à 17 16 52

**Comment by BOHEUS** [comment]
@lucasbordeau I wrote in previous PR but I'll ask again, what `yarn test:e2e:ui companies` or `yarn test:e2e:debug companies` show? Also, is app running locally while tests are running?

**Comment by lucasbordeau** [comment]
@BOHEUS 

image

**Comment by BOHEUS** [comment]
Okay, so that's why I couldn't understand why it wasn't working, I'm preparing a fix for this

**Comment by BOHEUS** [comment]
I tested it on demo and now it works, if it fails due to hardcoded check of rows in table, that's expected

**Comment by lucasbordeau** [comment]
Thanks, I tested it again, the test fails in localhost because it doesn't have the time to load the companies page : 

image

We should find a way to be sure that login is finished and the next page is loaded.

**Comment by BOHEUS** [comment]
It seems like the 5 sec wait for expect is not applied for that one specific check and it can't be done in asynchronous way as it simply doesn't wait for DOM, I'll try to fix this as I don't repeat it on my machine.

**Comment by BOHEUS** [comment]
I'm pretty sure I've found the root cause of this: the test assumes that user is logged in by checking the URL as well as default page which is Companies but since Companies page is both default page after logging and background for the login page and has the same HTML structure, the test finds the expected data in background of login page (because the transition from login page to user's workspace is not immediate and it takes up to few seconds), not in the workspace.

**Comment by BOHEUS** [comment]
I've changed the logic of tests and now they use proper fixture for making screenshot after each test as well as login setup before all tests so now no time will be wasted for logging as tests can reuse authorized state.

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
Ok that works, I'm merging this first round, well done.

**Pull request merged**
