### PR TITLE
Feat: First column style update

### LINKED ISSUE #935: First column style update (Good first issue)
# Current behavior

Today, clicking outside the chip opens the input to edit the company name. Clicking on the chip navigates to the associated show

https://github.com/twentyhq/twenty/assets/19412894/5e85c2be-6c1e-4759-801b-483a6bb3218d

Precision: for sure, clicking on the input should not close it but allow to edit it! (Did it only on Figma to show the behavior)

# Desired behavior

### New line

Clicking on the "plus" icon on the top right should directly open a field above the new empty line. Once something as been written in the Company name input, and the input has been closed, the behavior should be the one of _existing line_ below (clicking on the first cell should navigate to the associate show page). If the input has been closed, but no content has been written inside, clicking again on the empty cell should open it again. 

https://github.com/twentyhq/twenty/assets/19412894/98a237a8-2c5c-4f34-b1b3-dd58c52d0314

### Existing lines

Once a line has been created, the whole cell should be clickable, and link to the associated show page. On cell hover, a button should appear, and the chip state should be changed to its hover state (the one that appears on chip hover today). 

The button has an independent hover, even if it will redirect to the corresponding detail page on click as the rest of the cell. Once the name of the company or people has been updated, it should no longer be editable on the index page (maybe we can add the option back in a contextual menu later) so **make sure the instance name edition is perfectly working on the show page first!**

https://github.com/twentyhq/twenty/assets/19412894/44b58497-6882-4ddc-bac6-2284aca30c19

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=rYlqqQ4Pj9HITkSR-4

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
Closes #935 

Approach
1. Made the table cell button generic by passing the Icon as a prop.
2. Instead of setting the useEditButton boolean in definitions, the Button Icon itself is set if it is to be displayed. This is similar to the Column Header icon already used in definitions and will allow cell-specific buttons to be used.
3. Modified openTableCell logic to check for company / person cell and navigate to the show page if the value is not empty.
4. Modified TableCellContainer logic to check for empty company / person and not show the icon when empty.

https://github.com/twentyhq/twenty/assets/54364088/1c0f15e8-f0dc-4b83-883c-95ff07a6e3ab

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 nice implementation, since it's a complex zone of the app, we have to work on some details which I'll take the time to write this afternoon. 

You can already look at how things are done in the field module with typeguards, `useIsFieldEmpty` and `usePersistField`

**Review by lucasbordeau — COMMENTED** [review]
- We should avoid implementing features in openTableCell, because it's responsible for opening only, instead the first column should know if it should call openTableCell
- There shouldn't be any mention of people or company in the table cell components, we should instead rely on a generic feature that allows to go to a link on the first cell, and this link should be computed by a function that is passed to the field definition. So every field definition handles its scope. 

Please feel free to come on our Discord server to discuss the details as it may require some back and forth discussions on the best implementation

**Comment by AyushAgrawal-A2** [comment]
I have reimplemented it as per your suggestions.

Approach for latest commit ([d9fa535](https://github.com/twentyhq/twenty/pull/1746/commits/d9fa535594dddcb822867cabbf0f97b1098e43a8)):

1. (same as previous) Made the table cell button generic by passing the Icon as a prop.
2. (same as previous)  Instead of setting the useEditButton boolean in definitions, the Button Icon itself is set if it is to be displayed. This is similar to the Column Header icon already used in definitions and will allow cell-specific buttons to be used.

3. Added pathToShowPage on field definition for company and person fields.
4. Modified openTableCell logic to check whether it is a first-column cell and navigate to the show page if the value is not empty.
5. Modified TableCellContainer logic to check whether it is a first-column cell and show the icon when not empty.

**Comment by lucasbordeau** [comment]
Ok I checked it on my local computer but I don't have the button appearing, could you merge main and verify on your side ?

**Comment by AyushAgrawal-A2** [comment]
@lucasbordeau 
Done

https://github.com/twentyhq/twenty/assets/54364088/a5ad2cda-a003-4f1f-82bf-a0ebf2ff5474

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
