### PR TITLE
[oss.gg]: hubspot to twenty contact data migration script (750 points) (migration-script)

### PR DESCRIPTION
**Pull request by FaheemOnHub**
HubSpot to Twenty CRM Contact Migration Script

Script's  github repo: https://github.com/FaheemOnHub/twenty-crm-hubspot-script

This Node.js script facilitates migrating contacts from HubSpot CRM to Twenty CRM. The user has the option to either check for duplicates in the Twenty CRM before migrating or directly migrate all contacts without checking.

Video Proof added in oss-gg's twenty-dev-challenges

### CODE REVIEW

**Comment by FaheemOnHub** [comment]
kindly add hacktoberfest also to it

**Review by charlesBochet — APPROVED** [review]
Very nice! I've take a look at your script and at your video. Cool to see a migration script in action

**Comment by FaheemOnHub** [comment]
can u please add hacktoberfest to it ?, i will get my hacktoberfest pr

**Comment by charlesBochet** [comment]
what do you mean to add hacktoberfest to it?

**Comment by FaheemOnHub** [comment]
@charlesBochet Can I get 20crm paid as I want to continue contribute to the CRM repo, but I think for that I need to be able to access it?

**Pull request merged**
