### PR TITLE
chore(front): Refactor the SnackBar component to use the new scope architecture

### LINKED ISSUE #2366: Refactor the SnackBar component to use the new scope architecture
## Scope & Context

We are doing a global refactoring to introduce components scopes.

## Technical inputs

See #2415 

- Refactor SnackBarProvider to SnackBarManager
- Create SnackBarManagerScope
- Create a useSnackBarManager() hook and get rid of useSnackBar()
- Refactor snackBarSetQueueState to use a Recoil callback

### PR DESCRIPTION
**Pull request by gitstart-twenty**
Fixes #2366

### CODE REVIEW

**Comment by lucasbordeau** [comment]
We've decided to keep the same pattern in the naming of the files :
- Manager stays Provider
- useSnackBarManager stays useSnackBar

This way we won't create another parallel naming convention for the Provider / hook pattern that is standard in React.

**Review by lucasbordeau — CHANGES_REQUESTED** [review]
We've decided to keep the same pattern in the naming of the files :

- Manager stays Provider
- useSnackBarManager stays useSnackBar

This way we won't create another parallel naming convention for the Provider / hook pattern that is standard in React.

**Comment by gitstart-twenty** [comment]
@lucasbordeau This has been updated

**Review by charlesBochet — APPROVED** [review]
Thank you :)

**Pull request merged**
