### PR TITLE
 Improve menu mobile display

### PR DESCRIPTION
**Pull request by ketanMehtaa**
Improving menu  in mobile display . twentyhq/core-team-issues#153
design is not proper right now.

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey @ketanMehtaa great progress, this will be super cool!!!
Three things I noticed:
- Access to settings page is broken
- Search page hides menu
- I have a vertical scroll and an horizontal scroll, probably because the bar width/height doesn't match anymore

**Comment by ketanMehtaa** [comment]
> Hey @ketanMehtaa great progress, this will be super cool!!! Three things I noticed:
> 
> * Access to settings page is broken
> * Search page hides menu
> * I have a vertical scroll and an horizontal scroll, probably because the bar width/height doesn't match anymore

Thanks for the review , working on it @FelixMalfait .

**Comment by ketanMehtaa** [comment]
[Screencast from 2024-10-26 03-55-58.webm](https://github.com/user-attachments/assets/63804341-de11-4b33-abe6-9cc97e9a3631)
@FelixMalfait , I’m having trouble handling <currentWorkspaceMemberFavorites> within the drag-and-drop functionality provided by @hello-pangea/dnd. Is this functionality still actively in use? I checked on demo.twenty.com and noticed that the drag-and-drop wasn’t working there.

**Comment by ketanMehtaa** [comment]
@Bonapara  @FelixMalfait  I’m having trouble handling currentWorkspaceMemberFavorites within the drag-and-drop functionality provided by @hello-pangea/dnd. Is this functionality still actively in use? I checked on demo.twenty.com and noticed that the drag-and-drop wasn’t working there.
please review and tell me if i need to do any refactoring or changes
Thanks :)

**Comment by lucasbordeau** [comment]
@ketanMehtaa Could you please work with @Hitarthsheth07 on one PR. I'm closing this PR but please see on PR https://github.com/twentyhq/twenty/pull/8163 to propose your modification and work together with @Hitarthsheth07

**Pull request closed without merging**
