### PR TITLE
Member card fix email display

### LINKED ISSUE #3554: Display Email Instead of Duplicate Name in 'Members' Settings
## Current Behavior

The user's name is displayed twice on the "Members" page.

CleanShot 2024-01-19 at 14 46 29@2x

## Desired Behavior

Display the user's email below their name.

CleanShot 2024-01-19 at 14 50 50@2x

### PR DESCRIPTION
**Pull request by brendanlaschke**
Bildschirmfoto 2024-01-19 um 15 33 55

closes #3554

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
LGTM, good one as always @brendanlaschke!

**Comment by charlesBochet** [comment]
@brendanlaschke before we merge it though, we would need to populate this email on signUp, could you also make sure we are filling workspaceMember email address in signUp methode of user.service.ts on the the backend side?

Then, we will need to run a SQL script to update existing workspace in production

**Comment by charlesBochet** [comment]
If you have time, it would be great to create a command that would do it! Would really help :)

**Comment by brendanlaschke** [comment]
```
Set search_path = workspace_1wgvd1injqtife6y4rvfbu3h5;

UPDATE "workspaceMember" member
SET "userEmail" = u.email
FROM core."user" u
WHERE u.id = member."userId" and member."userEmail" = '';
```
Would this be enough? Or how would you target all schemas, via a search path or do you loop over them or do you have a different method?

**Comment by charlesBochet** [comment]
@brendanlaschke I'm going to take of the script manually, it's not a big deal

**Pull request merged**
