### PR TITLE
migrate eslint rules to typescript

### LINKED ISSUE #1590: Migrate matching-state-variable rule from eslint-plugin-twenty to eslint-plugin-twenty-ts
## Context

We are maintaining a package `eslint-plugin-twenty` to add our own linter rule and help the community share the same standards. We have introduced a new `eslint-plugin-twenty-ts` package where rules can be written in typescript and tested. We need to migrate from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`

## Scope
This ticket is about moving the `matching-state-variable` rule from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`. 
- take a look at `twenty/packages/eslint-plugin-twenty/rules/matching-state-variable.js`
- create a new rule within eslint-plugin-twenty-ts that does the same thing
- write tests to cover the different cases  'useRecoilState' / 'useRecoilFamilyState' / 'useRecoilSelector' / 'useRecoilScopedState' / 'useRecoilScopedFamilyState' / 'useRecoilScopedSelector' / 'useRecoilValue'
- make sure the linting rule is still working by trying to badly name recoilState: `const currentUserBla = useRecoilValue(currentUserState);` should be an error

### LINKED ISSUE #1591: Migrate no-hardcoded-colors rule from eslint-plugin-twenty to eslint-plugin-twenty-ts
## Context

We are maintaining a package `eslint-plugin-twenty` to add our own linter rule and help the community share the same standards. We have introduced a new `eslint-plugin-twenty-ts` package where rules can be written in typescript and tested. We need to migrate from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`

## Scope
This ticket is about moving the `no-hardcoded-colors` rule from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`. 
- take a look at `twenty/packages/eslint-plugin-twenty/rules/no-hardcoded-colors.js`
- create a new rule within eslint-plugin-twenty-ts that does the same thing
- write tests to cover the different case
- make sure that the linter is still detecting hardcoded colors in the codebase

### LINKED ISSUE #1592: Migrate sort-css-properties-alphabetically rule from eslint-plugin-twenty to eslint-plugin-twenty-ts
## Context

We are maintaining a package `eslint-plugin-twenty` to add our own linter rule and help the community share the same standards. We have introduced a new `eslint-plugin-twenty-ts` package where rules can be written in typescript and tested. We need to migrate from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`

## Scope
This ticket is about moving the `no-hardcoded-colors` rule from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`. 
- take a look at `twenty/packages/eslint-plugin-twenty/rules/sort-css-properties-alphabetically.js`
- create a new rule within eslint-plugin-twenty-ts that does the same thing
- write tests to cover the different case
- make sure that the linter is still detecting non ordered imports

### LINKED ISSUE #1593: Migrate styled-components-prefixed-with-styled rule from eslint-plugin-twenty to eslint-plugin-twenty-ts
## Context

We are maintaining a package `eslint-plugin-twenty` to add our own linter rule and help the community share the same standards. We have introduced a new `eslint-plugin-twenty-ts` package where rules can be written in typescript and tested. We need to migrate from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`

## Scope
This ticket is about moving the `no-hardcoded-colors` rule from `eslint-plugin-twenty` to `eslint-plugin-twenty-ts`. 
- take a look at `twenty/packages/eslint-plugin-twenty/rules/styled-components-prefixed-with-styled.js`
- create a new rule within eslint-plugin-twenty-ts that does the same thing
- write tests to cover the different case
- make sure that the linter is still detecting styled component with a name not prefixed by Styled

### PR DESCRIPTION
**Pull request by neo773**
This PR migrates all eslint rules to TypeScript, the code is strongly typed

/fixes https://github.com/twentyhq/twenty/issues/1590
/fixes https://github.com/twentyhq/twenty/issues/1591
/fixes https://github.com/twentyhq/twenty/issues/1592
/fixes https://github.com/twentyhq/twenty/issues/1593

### CODE REVIEW

**Comment by yashug** [comment]
@neo773 your missing all the test cases

**Comment by charlesBochet** [comment]
@neo773 thanks for contributing :)

Unfortunately, it's a duplicate of https://github.com/twentyhq/twenty/pull/1618, so I will close this one

**Comment by neo773** [comment]
@charlesBochet 
I would like you to reconsider this, I started work on it shortly after the private bounties were posted.
My code is strongly typed and has no any type.
The test cases are also working.

**Comment by charlesBochet** [comment]
I am not familiar with Algora but can multiple person claim the same bounty?

That's true that your code is closer to what we want, let's split the bounty for this one, if that's fine with you :)
Could you split the test file in multiple tests (one by rule) and remove the old package? (eslint-plugin-twenty)

**Comment by anikdhabal** [comment]
> @neo773 I am not familiar with Algora but can multiple person claim the same bounty?
> 
> That's true that your code is closer to what we want, let's split the bounty for this one, if that's fine with you :) Could you split the test file in multiple tests (one by rule) and remove the old package? (eslint-plugin-twenty)

Hey @charlesBochet, I respect your decision, but please don't split it this time. I've been working on this issue from the start, which is why I haven't been able to focus on other issues. I understand that @neo773 has also invested time in it, and I appreciate that. I submitted my PR two hours ago, and @neo773 has made another PR for your consideration. However, as I mentioned earlier, I haven't been able to focus on other issues due to this one, and I've spent a lot of time trying to fix it. I hope you understand guys.

Please don't split it this time. 🙏

**Comment by yashug** [comment]
@charlesBochet I kindly suggest that Algora consider allowing only the individual who makes the initial attempt to create a PR for a given task. Presently, it seems to have turned into a race where, even though someone has made an attempt, another individual promptly submits a PR before the initial attempt can be completed. This situation requires careful consideration, as it results in all of us investing a significant amount of time on the same issue, which ultimately leads to wastage of time for everyone involved.

It would be greatly appreciated if you could permit the person who makes the first attempt to create the PR. It's important to recognize that not everyone may have the luxury of dedicating their full time to creating a PR as quickly as possible.

For instance, in the case of issue #1593 (https://console.algora.io/bounties/clmluyink0008l50fud3o1z6f), I initiated the first attempt and began working on it. However, others started creating PRs in parallel, resulting in a significant amount of time being spent on the same issue. I believe that Algora should strive to find a suitable solution to address this situation where contributors are competing for bounties. Open source contributions should be motivated by willingness and collaboration, rather than being turned into a race to claim bounties.

Thank you for your understanding and consideration.

 cc: @anikdhabal @neo773

**Comment by yashug** [comment]
@neo773 please also consider updating this file also with new ts rules https://github.com/twentyhq/twenty/blob/main/front/.eslintrc.js

**Comment by neo773** [comment]
@charlesBochet 
Thank you for the tip but you forgot to authorize it with your Algora account (see the link in AlgoraBot's reply).

**Comment by charlesBochet** [comment]
Done!

**Pull request closed without merging**
