### PR TITLE
Adds secondary color and styles to code snippets in block note editor ( #6029 )

### LINKED ISSUE #6029: Add a secondary background color to code blocks
## Add a secondary background color to inline code blocks

Can we change the background color of `code blocks` (backticked text) to make it more visibly distinct? The website has this, but the CRM doesn't.

## Current behavior

Currently the font and kerning change, but it's easy to miss. The following screenshot contains a code block. This affects both light and dark mode.

Screenshot 2024-06-25 at 7 42 21 PM

## Expected behavior

Secondary background color, consistent with the website.

Screenshot 2024-06-25 at 7 45 53 PM

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/6929
- [ ] https://github.com/twentyhq/twenty/issues/6930
```

### LINKED ISSUE #6929: Fixes inline code block

### PR DESCRIPTION
**Pull request by Faisal-imtiyaz123**
fixes https://github.com/twentyhq/twenty/issues/6929

### CODE REVIEW

**Review by lucasbordeau — APPROVED** [review]

**Comment by Faisal-imtiyaz123** [comment]
@lucasbordeau My bad! I missed the apt position to place the css code!! I think we should use `theme variables` because visibility is bad in `dark theme`.

**Comment by lucasbordeau** [comment]
Could you open another PR for that ?

**Comment by lucasbordeau** [comment]
We'll link it to this issue also.

**Comment by Faisal-imtiyaz123** [comment]
@lucasbordeau I did open a PR for this quite a while ago. That got merged !

**Comment by lucasbordeau** [comment]
Ok nice thank you !

**Pull request merged**
