### PR TITLE
Update blocknote

### PR DESCRIPTION
**Pull request by brendanlaschke**
Update blocknote and remove feature flag as the problems with images described [here](https://github.com/twentyhq/twenty/pull/2872) were fixed.

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
Thank you @brendanlaschke, LGTM :)

**Comment by charlesBochet** [comment]
@brendanlaschke I have actually reverted the version upgrade as it was breaking the design and I have opened an issue here, hopefully this can be fixed soon: https://github.com/TypeCellOS/BlockNote/issues/523

**Comment by brendanlaschke** [comment]
oh that's not that great didn't check for this - I thought this are the same styles as for the inline modules before ...

**Comment by charlesBochet** [comment]
@brendanlaschke it should be fixed, could you try to re-upgrade blocknote version? :)

**Comment by brendanlaschke** [comment]
It still doesn't look right especially the box sizing is a problem ... but also styles on the body like line height and font-size are breaking the layout ...

Bildschirmfoto 2024-01-22 um 13 31 09

**Pull request merged**
