### PR TITLE
fixed Calendar clear button should take the full width issue

### LINKED ISSUE #3249: Calendar clear button should take the full width
# Current behavior

CleanShot 2024-01-05 at 10 36 06

# Desired behavior

The button should take the full width as a regular menu item

### PR DESCRIPTION
**Pull request by abdul-irfan-k**
fix #3249
Screenshot from 2024-01-07 13-32-30

### CODE REVIEW

**Review by lucasbordeau — CHANGES_REQUESTED** [review]
Welcome to Twenty repo and thanks for your first contribution.

Here are some guidelines to complete this issue : 

image
 
The paddings have to be consistent, please measure them so you have the same horizontal and vertical padding.

Could you refactor the StyledButtonContainer, so it extends MenuItem like this : 

```tsx
const StyledButtonContainer = styled(MenuItem)`
  ...
```

That's how we use className, to extend components with styled-component, not to pass classes to them directly.

**Comment by abdul-irfan-k** [comment]
Screenshot from 2024-01-09 17-16-43

**Comment by abdul-irfan-k** [comment]
Hi i maded change

**Comment by lucasbordeau** [comment]
Hi @abdul-irfan-k, could you help @leojalfred on his PR https://github.com/twentyhq/twenty/pull/3265 

We need this to be pixel perfect, please take care of reviewing his PR with your changes and take care of the menu item padding. 

Thanks.

**Comment by lucasbordeau** [comment]
Hi @abdul-irfan-k, I'm closing this PR in favor of https://github.com/twentyhq/twenty/issues/3249.

**Pull request closed without merging**
