### PR TITLE
Fix display empty value if boolean instead of false on show page

### LINKED ISSUE #4438: Boolean (True/False) display "empty"
I created a "Non Profit" field with boolean :

shot 2024-03-13 at 09 12 06

But when I click in the Company, it says "Empty" :

shot 2024-03-13 at 09 12 44

### PR DESCRIPTION
**Pull request by brendanlaschke**
closes #4438

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Thanks!
It's better than what we currently have for sure so we could merge it like this, but the only issue is that the ui doesn't reflect the DB.
We could:
(1) allow empty values and keep displaying empty state when it's null (but we need to adapt true/false component to also have some form of "reset" which might not look good)
(2) always set a default value on backend to false
(3) force user to pick default value when creating the field

3 is my favorite option :). We already have default values for select so the mechanism is already there.

@brendanlaschke would you accept to give it a try? if yes, probably @Bonapara could suggest design

**Comment by brendanlaschke** [comment]
Had the same thoughts about the null values but I thought only about 1 & 2 - and was also not happy with them ...
Sure I could give it a try :)

**Comment by Bonapara** [comment]
image

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14456-175450&mode=design&t=TRw01yPRJGTPE1Ry-11

3) That would be great! We should set "true" as the default value.

**Comment by brendanlaschke** [comment]
I feel like im 95% there but what confuses me is:

If I send a field metadata mutation(to reproduce ust change a defaultValue on a boolean field) I get a validation error:

```
[class FieldMetadataDefaultValueBoolean]


[
  ValidationError {
    target: false,
    value: undefined,
    property: undefined,
    children: [],
    constraints: {
      unknownValue: 'an unknown value was passed to the validate function'
    }
  }
]
```

(validate-default-value-for-type.util)

defaultValueInstance is `false` matching the SELECT one  `"Option_1"`


Do you spot something wrong or have an idea what could be the problem?

**Comment by magrinj** [comment]
Hey @brendanlaschke,
Thanks for your PR, I don't really understand your error, you're speaking about `Option_1` that seems related to `enum` type, but we're trying to add defaultValue for `boolean` type

**Comment by brendanlaschke** [comment]
> Hey @brendanlaschke, Thanks for your PR, I don't really understand your error, you're speaking about `Option_1` that seems related to `enum` type, but we're trying to add defaultValue for `boolean` type

Let me try to explain it:

I am trying to set the default Value. Therefore I set the `defaultValue` parameter in the grapql query:

```
{
    "operationName": "UpdateOneFieldMetadataItem",
    "variables": {
        "idToUpdate": "07dde1e7-10be-4a48-ba08-73361c8ee93d",
        "updatePayload": {
            "defaultValue": false,
            "description": null,
            "icon": "IconUsers",
            "label": "as",
            "name": "as"
        }
    },
    "query": "mutation UpdateOneFieldMetadataItem($idToUpdate: ID!, $updatePayload: UpdateFieldInput!) {\n  updateOneField(input: {id: $idToUpdate, update: $updatePayload}) {\n    id\n    type\n    name\n    label\n    description\n    icon\n    isCustom\n    isActive\n    isNullable\n    createdAt\n    updatedAt\n    __typename\n  }\n}"
}
```

this query receives an error: 
```
{
  "errors": [
    {
      "message": "update.FieldMetadataDefaultValue is not valid",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ],
  "data": null
}
```
Here the Error is triggered by a class-validator FieldMetadataDefaultValueBoolean



Now I compare this to one with a select field metadatatype:

```
{
    "operationName": "UpdateOneFieldMetadataItem",
    "variables": {
        "idToUpdate": "945fdb54-e117-42a2-9040-b838ccf2a7c1",
        "updatePayload": {
            "defaultValue": "OPTION_1",
            "description": null,
            "icon": "IconUsers",
            "label": "sele",
            "name": "sele",
            "options": [
                {
                    "color": "green",
                    "id": "e6d9a68b-fa20-44f2-98a3-edce80764302",
                    "label": "Option 1",
                    "position": 0,
                    "value": "OPTION_1"
                }
            ]
        }
    },
    "query": "mutation UpdateOneFieldMetadataItem($idToUpdate: ID!, $updatePayload: UpdateFieldInput!) {\n  updateOneField(input: {id: $idToUpdate, update: $updatePayload}) {\n    id\n    type\n    name\n    label\n    description\n    icon\n    isCustom\n    isActive\n    isNullable\n    createdAt\n    updatedAt\n    __typename\n  }\n}"
}
```

This works and updates the default value ...


Maybe I don't understand the validators correctly but I would expect them to work the same for both types...

**Comment by magrinj** [comment]
@brendanlaschke Thanks for your precision, I've taken a look on that as I'm refactoring the default value part, and in fact we've a bug in this part.
The second time when front-end send default value `OPTION_1` you should also receive an error, as default value should always be under an object:
```json
{ "value": "OPTION_1" }
```
But I'm working on this PR #4592 and will refactor this, so it will work without editing the front-end when this one will be merged.
I'll let you know here !

**Comment by brendanlaschke** [comment]
Should be working now ...

**Comment by FelixMalfait** [comment]
Didn't look into the code since it's been reviewed, but it doesn't work yet on my side (strangely false worked but not true)

Screenshot 2024-03-29 at 18 08 39

**Review by FelixMalfait — APPROVED** [review]
Great work as always!

**Pull request merged**
