### PR TITLE
fix:Hide Scrollbar before Scroll

### PR DESCRIPTION
**Pull request by Lucifer4255**
Fix for the issue #8847 Hide Scrollbar before Scroll.

https://github.com/user-attachments/assets/27dda89f-e3f6-4c72-bcc5-8c7e10d3c823

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Thank you @Lucifer4255!

@ehconitin I think you had introduced the changed that led to scrollbars appearing, would you mind reviewing this / giving context? Maybe instead we shouldn't have set `scrollHide` to default to false? Seems like it was the previous behavior

**Comment by ehconitin** [comment]
@FelixMalfait
This is my fault—I must have forgotten to commit and pushed the wrong changes in #8570.
@Lucifer4255, your changes make sense, but the code you're working on is wrong!

I’m reverting it to how it should have been. We simply want to make the scroll bars' background transparent when scrollHide = true

**Comment by FelixMalfait** [comment]
Merging like this and we agreed with @ehconitin that he will do a followup PR based on new requirements.

Thanks @Lucifer4255

**Comment by ehconitin** [comment]
Followup issue #9026

**Review by ehconitin — APPROVED** [review]
Let's merge it like this as this was the previous requirement, we will revert these changes when we get the scroll correct in NavigationDrawer :)

**Pull request merged**
