### PR TITLE
fix: Default View Font Color and Reordering

### PR DESCRIPTION
**Pull request by nganphan123**
This PR fixes issue #6114 
I removed the separate check for default item and add it into the draggable list.

### CODE REVIEW

**Review by Weiko — APPROVED** [review]
LGTM, thank you!

**Comment by FelixMalfait** [comment]
@Weiko I was just reviewing at the same time, I think it's missing a change so that it also reorders the sidebar

**Comment by nganphan123** [comment]
Hi @FelixMalfait , could you let me know which part of the sidebar you mentioned? I'll make any changes if needed.

**Comment by FelixMalfait** [comment]
@nganphan123 thanks a lot! Ping me and we can award 150 more points for the fix

The problem is the order here in the left sidebar which isn't affected in the same way

Screenshot 2024-10-24 at 08 53 56

**Comment by nganphan123** [comment]
Got it! I'll work on that.

**Comment by nganphan123** [comment]
Hi @FelixMalfait , I couldn't reproduce the issue above. When I reorder, the left navigation bar is also updated. Is this the one you were talking about? 

[Screencast from 2024-10-24 13-20-52.webm](https://github.com/user-attachments/assets/4ab20c5b-6548-4519-aa85-01edc7db2f07)

**Comment by FelixMalfait** [comment]
@nganphan123 sorry I missed your reply. Yes that's what I was talking about. Strange I still have the issue on my side! I will check and come back to you

**Comment by FelixMalfait** [comment]
Screenshot 2024-10-27 at 16 09 34

**Comment by FelixMalfait** [comment]
Oh I think I know why, there's a feature flag with 2 different ways of building the menu. You probably don't have that feature flag enabled (`isWorkspaceFavoriteEnabled`)

**Comment by FelixMalfait** [comment]
It's probably this: https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-metadata/components/NavigationDrawerItemForObjectMetadataItem.tsx#L47

I'll raise a quick fix!

**Pull request merged**
