### PR TITLE
feat: Adding className as a prop

### LINKED ISSUE #2362: Add className on UI components where it is missing
## Scope & Context

We want to be able to style the ui components with emotion, so we need to pass a classname.

## Technical inputs

Add a classname optional prop to the ui components where is is missing and pass this prop to the component the highest in the tree.

Example:
```
type H1TitleProps = {
  title: string;
  fontColor?: H1TitleFontColor;
  className?: string;
};

export const H1Title = ({
  title,
  fontColor = H1TitleFontColor.Tertiary,
  className,
}: H1TitleProps) => {
  return (
    <StyledTitle fontColor={fontColor} className={className}>
      {title}
    </StyledTitle>
  );
```

### PR DESCRIPTION
**Pull request by MatheusSanchez**
closes https://github.com/twentyhq/twenty/issues/2362

Just added className as a prop to the UI components.

### CODE REVIEW

**Comment by MatheusSanchez** [comment]
Hey @bosiraphael,

As this is my first open-source project and also my initial exposure to "twenty," I would like to confirm whether I am heading in the right direction.

Essentially, I plan to add the className prop to the components within the ui folder (twenty/front/src/modules/ui).

I've started implementing the necessary changes in the display folder, and I'll replicate them in the remaining folders if I'm on the correct path.

So, if I've understood the project correctly, it doesn't make sense to add this prop to the icons (twenty/front/src/modules/ui/display/icons), nor to the ColorSample.tsx and AnimatedCheckmark.tsx components. 
Is that correct? 


I'll continue working on adding it to the remaining components inside the ui folder.

**Comment by bosiraphael** [comment]
Hello @MatheusSanchez ! Thank you for contributing to twenty !
Yes you're right, we only want to pass the className prop to the components we want to be able to modify with styled components, and the components you are referring to are not part of it.

**Comment by MatheusSanchez** [comment]
Let's merge; please check if anything is missing. I would like to resolve this issue, and I'm going to work on a more complex one.

**Review by charlesBochet — APPROVED** [review]
Thank you! LGTM :)

**Pull request merged**
