### PR TITLE
fix: use <button> tag for buttons

### LINKED ISSUE #7577: Use the <button> tag for buttons
# Current behavior

Buttons are made of div

CleanShot 2024-10-10 at 18 26 00

# Desired Behavior

Use <button> HTML tags for accessibility

**BEWARE OF REGRESSIONS 🚨**

Check that all button states are working fine; otherwise let's use `role=button` but that's plan b

### PR DESCRIPTION
**Pull request by Pk9697**
## What does this PR do?
This PR updates div with button tag for buttons

Fixes #7577 

Screenshot 2024-10-17 210955

### CODE REVIEW

**Review by Devessier — APPROVED** [review]
Great job! We can merge.

**Comment by Pk9697** [comment]
Was my first PR !

**Comment by Devessier** [comment]
Good job, @Pk9697! 🎉

**Pull request merged**
