### PR TITLE
#3489 sidebar label in one line

### PR DESCRIPTION
**Pull request by jeet1desai**
Issue #3489 

image
image

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey thanks a lot for this! It's nice to have introduced the tooltip but I think it would be better without it since we can always click to open that item

**Comment by jeet1desai** [comment]
Oky, let me change that

**Comment by jeet1desai** [comment]
@FelixMalfait done, I have removed the tooltip

image

**Comment by FelixMalfait** [comment]
Perfect, thanks!

**Review by FelixMalfait — APPROVED** [review]

**Pull request merged**
