### PR TITLE
#2133 Add comments icon and count to Timeline card

### PR DESCRIPTION
**Pull request by codergirl2023**
Screenshot from 2023-10-23 08-34-07

### CODE REVIEW

**Review by charlesBochet — COMMENTED** [review]
@codergirl2023 The design looks nice and the code style is aligned with project convention :)
However, I would not add this commentCount to the UserChip / EntityChip, this is not their role to display a comment count.
Could you instead introduce a standalone CommentCounter component (in modules/comments module) and insert it within TimelineActivityCardFooter without chaning EntityChip and UserChip?

Thanks for the help, it's much appreciated

**Comment by codergirl2023** [comment]
@charlesBochet thanks for providing valuable feedback. Sure i will make the asked changes and raise PR

**Comment by charlesBochet** [comment]
@codergirl2023 Taking a look!

**Review by charlesBochet — APPROVED** [review]
LGTM!

**Pull request merged**
