### PR TITLE
Show Data Skeleton Loading

### LINKED ISSUE #4460: Show Data Skeleton Loading
# Desired Behavior

(See #4462 for videos)

Thanks to prefetch loading, we can now display the correct number of field lines and their names. It's time to launch the content loading:

image

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25429-70096&mode=design&t=75yrmyKfqMepmFVt-11

### PR DESCRIPTION
**Pull request by gitstart-twenty**
### Description

Show Data Skeleton loading

### Refs

#4460

### Demo

Figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25429-70096&mode=design&t=VRxtgYCKnJkl2zpt-0

https://jam.dev/c/178878cb-e600-4370-94d5-c8c12c8fe0d5

Fixes #4460

### CODE REVIEW

**Comment by Bonapara** [comment]
Hi, thanks for your work and this PR!

I have several feedbacks:

## Spacings

The skeleton spacing must match the loaded content exactly to prevent any "blink" when the content loads. For instance, the vertical gap between the inline fields in the left column is larger when the content is loaded than on the skeleton, There should be a spacing under the left column title. Please make sure nothing is blinking because of spacing issues.

https://github.com/twentyhq/twenty/assets/19412894/874b3d54-33fb-48cd-b433-dcfa14dfe657

## Colors

The skeleton color looks darker than on Figma. Could you make sure to use the appropriate colors?

| Skeleton | Figma |
| ------- | ------- |
| 
CleanShot 2024-05-07 at 18 39 22
 | 
image
 |
 
 ### Buttons
 
Is it possible to display the top right buttons at the start of loading, perhaps as disabled if they're not functional?

**Comment by gitstart-twenty** [comment]
@Bonapara On it 💪

**Comment by charlesBochet** [comment]
@gitstart-twenty could you rebase your PR on main, tests should be green :)

**Comment by gitstart-twenty** [comment]
> @gitstart-twenty could you rebase your PR on main, tests should be green :)

Alright

**Comment by gitstart-twenty** [comment]
Hey @Bonapara 
Mind taking another look here


https://github.com/twentyhq/twenty/assets/140154534/c0013e29-395c-4775-9cb3-0355224f56da

**Comment by Bonapara** [comment]
Looking great @gitstart-twenty!

**Comment by gitstart-twenty** [comment]
> Looking great @gitstart-twenty!

Awesome!

**Review by Weiko — APPROVED** [review]
LGTM 👍

**Pull request merged**
