### PR TITLE
Fix focused cell view

### LINKED ISSUE #5595: Focused cell is acting weird when scrolling horizontally
https://github.com/twentyhq/twenty/assets/51697796/1cb614ea-b73f-4629-abd8-7341b826dee2

### PR DESCRIPTION
**Pull request by AshishViradiya153**
Fixes https://github.com/twentyhq/twenty/issues/5595
- The portal has been removed, and the focused cell is now rendered directly within the relevant div/container.
- This ensures that the cell remains correctly positioned within the table and is properly hidden or unfocused when the user scrolls horizontally, fixing the issue of overlap or visibility on top of other elements.

### CODE REVIEW

**Comment by AshishViradiya153** [comment]
@charlesBochet Could you please review and let me know if there’s anything further needed from my side?

**Review by lucasbordeau — APPROVED** [review]

**Comment by AshishViradiya153** [comment]
@charlesBochet Could you please check? I still haven't received 150 points for this issue.

**Comment by AshishViradiya153** [comment]
@lucasbordeau Could you please check? I still haven't received 150 points for this issue.

**Pull request merged**
