### PR TITLE
Fix:If attachment token expires, it throws a 500 error instead of Unauthenticated

### PR DESCRIPTION
**Pull request by giiger**
This fixes this issue by throwing a descriptive error instead of a server error 500

### CODE REVIEW

**Review by charlesBochet — COMMENTED** [review]
@giiger Thanks for opening a PR, I agree we should improve error handling.

1) About the functional behavior: I'm a bit surprise this has to deal with graphql errors. To me files are serve over controllers (file.controller.ts) and I don't see what it has to do with controllers.

2) About the strategy: For rest controllers and for GraphQL API, we want to keep the number of possible errors low (here we should re-use the Authentication error I think) but have a flexible message which is already currently possible. We want services (here token validation service) to throw business specific errors (with dedicated error_code) and then the caller here (a rest controller to convert it to a more standard exception)

Let's first discuss 1) could you help me understand why this has to deal with GraphQL, I'm a bit lost

**Comment by giiger** [comment]
Yes, I apologize I am new to contributing on open source and I am not too familiar with the file structure or the code norms of this project. I see your point about the separation between controllers and GraphQL, and I may have misunderstood how the error handling should be implemented in this context.

Could you possibly give me some guidance about my next steps I should take? I would like to continue working towards dealing with error handling

**Comment by charlesBochet** [comment]
@giiger sure ! First:
- does your existing PR solve the issue, could you show me how? (before / after behavior)

**Comment by charlesBochet** [comment]
@giiger I'm going to close this PR as it's staled, feel free to re-open it if you still want to work on it

**Pull request closed without merging**
