### PR TITLE
chore: inject enviroment at the ./front deployment phase (#2174)

### PR DESCRIPTION
**Pull request by khakimov**
* Dockerfile CMD env.sh
    * env.sh generates env-config.js file
    * index.html imports env-config.js
    * front/src/config/index.ts imports REACT_APP_SERVER_BASE_URL

### CODE REVIEW

**Comment by charlesBochet** [comment]
@khakimov Thank you. I will do extensive testings based on this PR

**Comment by khakimov** [comment]
@charlesBochet i will look into what breaks tests as well (ie front-pages-sb-test)

**Comment by charlesBochet** [comment]
I've fixed it :)

**Comment by charlesBochet** [comment]
I'll merge it as it is as it LGTM, we might have a bit more work to make it work on render

**Comment by khakimov** [comment]
@charlesBochet could you build and push new image for ./front (from [here](https://github.com/twentyhq/twenty/issues/2099)) and I will test deployment on render

**Pull request merged**
