### PR TITLE
Fix hide calender icon if no deadline on task

### LINKED ISSUE #7402: Hide calendar icon if no deadline on task
# Current behavior

On `Record Pages → Tasks Tab` We display a calendar icon on tasks without deadlines:

af50be4b9e5cb1b5ea948af97499b7798165d66338bbe033427d6006ddc3b3cd

With deadline:

ff0cd5d06f0caa4e90165e66607442619d0a20e0a728bf195af6b8176cbcfe3b

# Desired Behavior

Don't display the calendar icon when there is no deadline set

### PR DESCRIPTION
**Pull request by Vardhaman619**
Closes #7402 

image

Ensured that the calendar icon is only visible when a deadline is assigned

### CODE REVIEW

**Comment by ehconitin** [comment]
Could u fix the conflicts @Vardhaman619? or do you need help?

**Comment by Vardhaman619** [comment]
@ehconitin I really want to fix this conflict, but I'm not sure where to start. Could you please outline the steps and processes I should follow to resolve it? Your guidance would be really helpful.

**Comment by ehconitin** [comment]
@Vardhaman619 We merged your previous PR #7438 yesterday, but for some reason same changes were included in this PR as well. The merged changes differ slightly from what you’ve added here, so I’ve removed those redundant changes to resolve the conflicts.
:)
This was a straightforward case, but conflicts like this can become more complex. To avoid them, I recommend keeping your branch up to date with the upstream branch as frequently as possible. ;)

**Comment by Vardhaman619** [comment]
@ehconitin Thank you for handling the conflicts and for the helpful advice! I'll make sure to keep my branch up to date with the upstream branch more frequently to avoid such issues in the future.

Thanks

**Comment by ehconitin** [comment]
@Bonapara instead of showing due date after task target, should we show it before?
That way task target would be consistently shown last, or it looks a bit weird
due date after task target - 

Screenshot 2024-10-09 at 22 34 09

due date before task target - 

Screenshot 2024-10-09 at 22 34 25

**Review by ehconitin — APPROVED** [review]

**Comment by Bonapara** [comment]
@ehconitin yes we should show it before!

**Pull request merged**
