### PR TITLE
fix: linked records redirection

### LINKED ISSUE #4093: Fix Back-Button Loop and View Overrides when displaying Shows Linked Records
# Current behavior

In shows, if there are multiple linked records, you can click "See all" to go to the relation index page showing only the records linked to the show.

CleanShot 2024-02-20 at 16 29 40

Goes to:

Screenshot 2024-02-20 at 16 30 17

# Issue

We are facing two issues with the solution that has currently been implemented:

1. Clicking the `Back` button creates an infinite loop because the previous page redirects to the generated index, preventing returning to the initial show page using the `Back` button.

Screenshot 2024-02-20 at 16 31 45

2. We can override the initial view parameters by pressing the `Update view` button. This is dangerous!

CleanShot 2024-02-20 at 16 34 01

# Desired Behavior

1. The intermediate redirection page should not be persisted in the history so pressing the back button redirects to the show page.

2. We should redirect the user to a `filtered default view` named `All [Object_plural_name]`. Pressing the `X` button should go back to the first user view. **We shouldn't display the "update view" and "reset" buttons on this default view.** (The filters applied to this view cannot be persisted). This _"default view"_ **should not appear in the view Switcher.**

image

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23405-37282&mode=design&t=r4mnIyW3DIbSmeHA-11

### PR DESCRIPTION
**Pull request by Muralidhar22**
Closes: #4093 
### Changes 
- Setting new params on landing records index page screen making it navigate to new screen, which is causing infinite redirection,  added change to `replace` entire url with new params.
- Made UI changes to remove update view and reset in `/objects/[objectNamePlural]` when came from `/object/[objectNameSingular]` by checking for filter params in the URL.
- Removed View switcher at the top view bar of records and added a `ViewObjectFilter`.
#### Recording
https://github.com/twentyhq/twenty/assets/33935339/e6d1e1eb-24dd-4bfe-af10-e49aa80c7eaa

### Checklist:
- [x] The intermediate redirection page should not be persisted in the history so pressing the back button redirects to the show page.
- [x] We should redirect the user to a filtered default view named All [Object_plural_name]. Pressing the X button should go back to the first user view. We shouldn't display the "update view" and "reset" buttons on this default view. (The filters applied to this view cannot be persisted). This "default view" should not appear in the view Switcher.

### CODE REVIEW

**Comment by charlesBochet** [comment]
@Muralidhar22 I'm not sure this is the best way to address this issue. I'm actually re-working this part, once done (later this week), I'll ping you with guidance on how to achieve it without duplicating the view picker

**Comment by charlesBochet** [comment]
@Muralidhar22 The refactoring is complete, you can go ahead :)

**Comment by Muralidhar22** [comment]
hey @charlesBochet thanks, will start working on this

**Comment by lucasbordeau** [comment]
@Bonapara @Muralidhar22 

Since this problem has been addressed by the refactor of @charlesBochet on views, we don't need to do anything special in this PR.

We only hide the reset & save buttons if there are parameters in the url.

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
