### PR TITLE
Show email in RecordChip on Email Thread Right Drawer

### PR DESCRIPTION
**Pull request by gvkhna**
Here's a simple PR to add the email to the record chip in the email threads view. This is really just an attempt to get my feet wet with the code base so I don't expect it to be accepted as-is. But wanted to get it looked at. 

I understand there may be considerations about how to display the email. I would prefer a more muted color for the email text, perhaps a bit smaller, similar to how gmail does it. Also this is a simple way to get the email drilled through the many layers not sure if this is the desired method of extending the AvatarChip.

Here's what it looks like, this is a rather simple `it just works` type of commit.

Screenshot 2024-09-08 at 10 54 08

Also note, the Chip is currently not extending the maxWidth property which I had to add to get the email to not be truncated. Seems to work fine otherwise. 

Update: apologies closed the previous, copied here, sorry for the mess, moved to it's own branch, opened as draft.

### CODE REVIEW

**Comment by bosiraphael** [comment]
Hello @gvkhna, thank you for contributing. Was there an issue created about this? Because I can't find this in the Figma design.
@Bonapara

**Comment by Bonapara** [comment]
Indeed, we shouldn't put the person's name on the chip. Instead, we should display a tooltip when someone clicks on the `to` text, similar to how Gmail does it. We should add a chevron down to the right of the `to` text to indicate it's a dropdown.

https://github.com/user-attachments/assets/0f752dd3-0bb2-4dfa-8192-484e93493517

### Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40644-109692&node-type=instance&t=8dUCvXCxTOcmmFb0-11

Use the prototype to see the behavior by clicking play. tell me if you want to handle it. Otherwise happy to open a new issue!

Thanks @gvkhna

**Comment by bosiraphael** [comment]
Closing this, you can create an issue @Bonapara :)

**Comment by Bonapara** [comment]
https://github.com/twentyhq/twenty/issues/7264

**Pull request closed without merging**
