### PR TITLE
feat: Self-hosting guide (750 points)

### PR DESCRIPTION
**Pull request by Khaan25**
image

### CODE REVIEW

**Comment by FelixMalfait** [comment]
/award 300
AI generated again? There is no POSTGRES_ADMIN_PASSWORD :)

**Review by FelixMalfait — APPROVED** [review]

**Comment by Khaan25** [comment]
Not AI generated :)

It's on the official docs: 
image

Plus, you may see 4 secrets, I only added one because I've another issue in which we've APP_SECRET so this guide won't be outdated :) Hope you got the point.

I took help from the official docs and didn't use AI 😄 @FelixMalfait

**Comment by Khaan25** [comment]
No worries :)

**Pull request merged**
