### PR TITLE
feat: add Settings/Accounts/Emails/Inbox Setting Contact auto-creation

### PR DESCRIPTION
**Pull request by lakshay-saini-au8**
Added Contact Auto Create section.
Added key in mock data as isContactAutoCreationEnabled

Screenshot 2024-01-01 at 7 29 48 PM

### CODE REVIEW

**Comment by lakshay-saini-au8** [comment]
Please Review
https://github.com/twentyhq/twenty/issues/3136

@thaisguigon @Bonapara

**Comment by lakshay-saini-au8** [comment]
@charlesBochet

**Comment by charlesBochet** [comment]
@thaisguigon Assigning this one to you!

**Review by thaisguigon — APPROVED** [review]
Thank you for your contribution! LGTM!

**Pull request merged**
