### PR TITLE
fix: fixed shortcuts population

### LINKED ISSUE #6776: Deactivated objects can still be accessed using shortcuts & cmd+k
**Scenario:**
1. Log in
2. Go to Settings > Data Model
3. Click on any active object, e.g. Companies, then on three dots near "Standard" label and click "Deactivate"
4. Go back to main page and use corresponding shortcut to access deactivated objects

**Actual:** Deactivated objects can still be accessed using shortcuts
[Screencast from 2024-08-28 20-43-15.webm](https://github.com/user-attachments/assets/425d21d4-62a1-43de-86e2-b48049d7baae)

**Expected:** Deactivated objects shouldn't be accessed using shortcuts until they're re-activated by the user.

### PR DESCRIPTION
**Pull request by sid0-0**
This PR fixes #6776 

Screenshots:
image

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Thanks a lot!
Sorry this could have been discussed upfront but tbh I think we should have done a loop and display all non isSystem +active objects like in settings, instead of filtering out from an hardcoded list. That way we could also get the icon directly from the true source in object metadata. 
One thing we would lose is the shortcuts but we can bring them back later.

We have plans to isolate it into a dedicated entry point, not mixed with records:
Screenshot 2024-09-13 at 15 55 31
("Objects" would open the list of objects you can navigate to)
Maybe this would be a good first step towards that.

What do you think?

**Comment by sid0-0** [comment]
@FelixMalfait 
What exactly do you mean by `isolate it into a dedicated entry point, not mixed with records`?

I have made changes to pick all data directly from object data.

Shortcuts are still functional as all initials are different and we won't run into any issues right now, in future we'll have to add a key for shortcut into object data itself (in case conflicts arise).

Note for reviewers: CommandMenu items' id has change from `'go-to-[labelPlural]'` to `uuid` provided by the object. I can revert to using a generic `go-to...` string if required, but I didn't see any issues this would raise.

**Comment by lucasbordeau** [comment]
Please see in `GotoHotkeysEffect` in order to create something dynamic. Right now it's hard coded.

**Comment by sid0-0** [comment]
@lucasbordeau had to use a hacky way to to call react hooks dynamically in `GotoHotkeyEffect.tsx`.
Let me know if there is a better way to achieve this.
Verified, functioning still the same

**Review by lucasbordeau — APPROVED** [review]
Used this PR to refactor a bit the app components and util into a module.

**Comment by lucasbordeau** [comment]
> @lucasbordeau had to use a hacky way to to call react hooks dynamically in `GotoHotkeyEffect.tsx`. Let me know if there is a better way to achieve this. Verified, functioning still the same

That's not really hacky as it's the only proper way to create a loop of hook render !

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
