### PR TITLE
feat: Custom Theme for Twenty

### PR DESCRIPTION
**Pull request by Khaan25**
image

### CODE REVIEW

**Comment by Bonapara** [comment]
Thanks for the theme @Khaan25! Great inspiration

**Review by Bonapara — APPROVED** [review]

**Comment by Khaan25** [comment]
@Bonapara, I can share a blue theme one as well? in another PR?

**Comment by Khaan25** [comment]
Haha, I was expecting to hear that 😄

**Comment by Khaan25** [comment]
Or maybe I could improve the current one and get few more points 😅

**Comment by Khaan25** [comment]
Can I improve the current one? :)

**Pull request merged**
