### PR TITLE
FIx minor issue related to gap between checkbox & menu item label

### LINKED ISSUE #8171: Lower gap between checkbox & menu item label
# Current Behavior

There is a 12px gap between the checkbox and the label in the multi-select dropdown menu values. This consists of a 4px margin on the right of the checkbox and an 8px gap. Additionally, there is an unwanted 4px margin on the left of the checkbox.

image

# Desired Behavior

**Remove the 4px margin around the checkbox.**

CleanShot 2024-10-29 at 12 42 41

### PR DESCRIPTION
**Pull request by parmarKaran01**
## Summary
This pull request addresses a minor issue reported in the #8171 , which was causing misalignment in the content and overall theme spacing.

Fixes #8171

## Fix

> Removed the 5px padding based on the check if its non hoverable, the current gap between the checkbox and the icon is 8px as expected.

> For the small variant the total size of the non hoverable component is 14x14 as mentioned in the design, for hoverable its 24x24

> For the Large variant the total size of the non hoverable component is 20x20 as mentioned in the design, for hoverable
its 32x32 

> checked for the hoverable checkbox component as well working as expected

## Screenshot for the fixes

Screenshot 2024-10-30 at 10 49 39 PM

#### Thank you for considering this contribution! I look forward to your feedback.

### CODE REVIEW

**Comment by Bonapara** [comment]
Hi @parmarKaran01, I believe the issue is a bit more complex than it seems..

In the design system, we should have two types of checkboxes: one that is hoverable and one that is not. The hoverable checkbox component should have a 24px container, while the non-hoverable checkbox should fit the checkbox itself (14px).

CleanShot 2024-10-31 at 11 18 05

By removing the spacing around the checkbox, you eliminated the hover effect on the checkbox in the index table, for instance.

https://github.com/user-attachments/assets/b2ec8824-17cb-41e9-a984-994cfcca5056

They should remain as they were before. 

https://github.com/user-attachments/assets/174a694c-4fc8-4611-8a96-426c6b3cef59

Please check that the components are properly implemented and reflect the Figma design:

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=14603-51328&node-type=frame&t=L4Zw8NIeonoYkIdd-11

Thanks for contributing!

**Comment by parmarKaran01** [comment]
@Bonapara So the dropdown component contains the non hoverable variant? and for the non hoverable variant the size should be 14x14, but if the component is hoverable then it has a size of 24x24 and it should be as it is correct?

**Comment by Bonapara** [comment]
💯 @parmarKaran01 

And 20px / 32px for the large checkbox component

**Comment by parmarKaran01** [comment]
@Bonapara updated the code based on the hover condition, please check and let me know if any issues

Thanks for giving the clarity!

**Comment by charlesBochet** [comment]
**Note:** We are a bit late on reviews! I'm attributing the oss-gg points to all opened PRs as Hacktoberfest event ends tonight. We will review the PR itself shortly

**Comment by Bonapara** [comment]
Thanks @parmarKaran01! Could you check the Figma measurements to ensure they match perfectly?

The left margin is 9px (5px + 4px) instead of 4px, and the margin between the checkbox and chip is 9px (5px + 4px) instead of 8px.

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
