### PR TITLE
Fix overlay positioning for 'Sort,' 'Filter,' and 'Options' menus #1521

### LINKED ISSUE #1521: Positioning of Overlays for 'Sort,' 'Filter,' and 'Options' Menus
### Scope

- 'People' page
- 'Companies' page
- "Opportunities' page

# Current design

Presently, the 'Sort', 'Filter', and 'Options' menus have inconsistent positioning, being too close to their respective buttons. 

https://user-images.githubusercontent.com/102394218/266701082-94e4072e-744b-4b67-a250-9569e7c5c575.mp4

# Expected design

To standardize the positioning, the following adjustments should be made:

- Align the right side of the menu with the right side of the div that contains all those text buttons.
- Position the menu 8px below the same div.

Image

### PR DESCRIPTION
**Pull request by bansalgokul**
Closes #1521

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Hi @bansalgokul, could you reference the issue linked to this PR, and also see why your solution is triggering a TypeScript error.

**Comment by charlesBochet** [comment]
@lucasbordeau It's this one: https://github.com/twentyhq/twenty/issues/1521#issuecomment-1742149396

**Comment by charlesBochet** [comment]
@bansalgokul I've tested locally and I have updated your code to use mainAxis and crossAxis instead which seems to be the correct way to offset using `useFloating`
Thanks for the help!

**Review by charlesBochet — APPROVED** [review]
LGTM, thank you!

**Comment by bansalgokul** [comment]
Thanks a lot. It was my first contribution to a big project. Will my request be merged ?

**Comment by charlesBochet** [comment]
> Thanks a lot. It was my first contribution to a big project. Will my request be merged ?

Yes sir!

**Pull request merged**
