### PR TITLE
Update 3-create-custom-interfact-theme-20.md

### PR DESCRIPTION
**Pull request by rajeevDewangan**
What are you solving : Create a custom theme for Twenty's interface

Points : 300points

Description : Duplicated the Figma file and customized the variables to create a new theme for Twenty’s interface.

Proof : 
Screenshot 2024-10-22 232502
link : https://www.figma.com/design/XE21QdkFuy0IJHtmW7TURa/Twenty-(rajeevDewangan)?node-id=0-1&node-type=canvas&t=BYBulCT6hpJu6E8G-0

### CODE REVIEW

**Comment by Bonapara** [comment]
@rajeevDewangan You should not change the colors of the components directly but the colors of the variables: 

CleanShot 2024-10-23 at 15 23 42

You can either create a new theme column or modify one of the exiting ones to create a new theme. Thanks!

**Comment by rajeevDewangan** [comment]
Modified the light theme as "RajeevDewangan's light version" with my color choices in the variables
link : https://www.figma.com/design/XE21QdkFuy0IJHtmW7TURa/Twenty-(rajeevDewangan)?node-id=0-1&m=dev&t=l3Rd0KhJF0JCe8Fq-1

**Comment by Bonapara** [comment]
Thanks for your theme, love the retro looks and the tag colors!

**Review by Bonapara — APPROVED** [review]

**Review by charlesBochet — APPROVED** [review]

**Pull request merged**
