### PR TITLE
fix:Change Email Sync Status Display from Complete to Active

### PR DESCRIPTION
**Pull request by Avnish-oP**
changed the label of syncStatusOption from complete to active

### CODE REVIEW

**Comment by charlesBochet** [comment]
Hi @Avnish-oP, thanks for the PR, is there any related issue or is it a personal intiative? (in case we will need a review from design)

**Comment by charlesBochet** [comment]
Found it: https://github.com/twentyhq/twenty/issues/5961
It seems to be already assigned but the contributor has not raised a PR yet.
Also we already have another PR: 
https://github.com/twentyhq/twenty/pull/5965

**Comment by charlesBochet** [comment]
@Avnish-oP as there is a previous PR and you were not assigned on the issue, I'll close this one, sorry about that.

Feel free to work on any other good first issue but make sure to be assigned to it first :)

**Comment by Avnish-oP** [comment]
> @Avnish-oP as there is a previous PR and you were not assigned on the issue, I'll close this one, sorry about that.
> 
> Feel free to work on any other good first issue but make sure to be assigned to it first :)

yes i will remeber it for the future ;)

**Pull request closed without merging**
