### PR TITLE
Fixed favicon requests for empty domain names

### LINKED ISSUE #4135: If company.domainName is empty we shouldn't try to load a favicon
Saw a fun bug this morning.
The website was trying to load https://github.com/twentyhq/favicon/blob/main/README.md

Screenshot 2024-02-22 at 15 31 50

The reason was that https://favicon.twenty.com redirects to https://github.com/twentyhq/favicon/blob/main/README.md

When there is no domain name on a company that's created we should try to load a remote icon at all / we shouldn't do a request to https://favicon.twenty.com .

### PR DESCRIPTION
**Pull request by sohalkumar**
fixes #4135

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
Tested it, looks good to me :)

**Comment by sohalkumar** [comment]
Hi @charlesBochet 
> @sohalkumar Your tests are failing though. Could you update `packages/twenty-front/src/utils/__tests__/utils.test.ts` on line 45: `expect(getLogoUrlFromDomainName(undefined)).toBe(undefined);`

I will add that. Thanks.

> Next time, it is best to create a branch in your fork (non main), so we can commit to your branch to help you merge your PR faster :)

Yes I apologise for that, I realised my mistake after I raised a PR :')
Will keep in mind from now on. Thank you.

**Comment by charlesBochet** [comment]
Good to go! Thank you @sohalkumar

**Comment by sohalkumar** [comment]
@charlesBochet Thank you :D

**Pull request merged**
