### PR TITLE
[backend] add cache storage module

### PR DESCRIPTION
**Pull request by Weiko**
## Motivation
The messaging module is running a few jobs that imports emails from mail providers. Those providers have some limit rating and we sometimes import too many. The strategy is to do a first query that fetches all messageIds, which is fast, and to import the message data later, in batches. We need to first store those message ids but it wouldn't make sense to store in DB messages with only their ids and a key-value store might be a better approach.

## Implementation
This PR introduces a new CacheStorageModule which is wrapping NestJS CacheModule which itself wraps cache-manager node package. This means we should be able to accept any store type that this package handles.
For now, we want to expose in-memory cache and redis.
The CacheStorageService can be injected like this
```
@Inject(CacheStorageNamespace.Messaging)
private readonly cacheStorageService CacheStorageService
```
where the token is used as a namespace (prefixing the key with a string separated by a semicolon as convention)

Note: I'm also editing tsconfig to exclude dist folder from import as it caused issues in the past.
Note2: There is an existing MemoryStorageModule however it's not using the CacheModule from NestJS so we need to migrate the existing code to use the new CacheStorageModule instead

## Test
unit tests
+ locally with in-memory 
Screenshot 2024-03-05 at 16 53 12

+ redis (here RedisInsight creates folders to display namespaces)
Screenshot 2024-03-05 at 16 53 27

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
LGTM, would be great to get a review from @magrinj

**Review by magrinj — COMMENTED** [review]
@Weiko As suggested we should rely on the existing module with a Redis implementation in my opinion, this is going to introduce 2 modules that are doing the same thing

**Comment by Weiko** [comment]
> @Weiko As suggested we should rely on the existing module with a Redis implementation in my opinion, this is going to introduce 2 modules that are doing the same thing

The goal is to not keep 2 modules but replace the existing one by the NestJS cache module (cc @charlesBochet)

**Review by magrinj — APPROVED** [review]
LGTM !

**Pull request merged**
