### PR TITLE
Fix missing team member images in calendar event

### PR DESCRIPTION
**Pull request by mritosa**
### Work
Fixed issue: [#5308](https://github.com/twentyhq/twenty/issues/5308)
### Before
Team member images are absent from Calendar events participant chips.
Before
### After
Screenshot 2024-05-14 at 10 53 24

### Fix explained:
Request only returned reference on objects Person and WorkspaceMember so the solution was to use those references and with them fetch urls of their avatar.

### CODE REVIEW

**Comment by charlesBochet** [comment]
Hi @mritosa! Thanks for the contribution
1) Could you create a branch on your fork repository, this ease the collaboration as the core team will also be able to push code to your branch
2) We should not make extra queries as this will slow the application. I'm taking a deeper look to give you hints on how to solve that

**Review by Weiko — COMMENTED** [review]
Hi, thanks for your contribution!
Let's not use extra queries for this, you can use recordGqlFields to redefine selectors of the existing graphql query generated by useFindOneRecord inside RightDrawerCalendarEvent and it should do the trick!

**Comment by charlesBochet** [comment]
Agree with @Weiko this should be the way to go :)

**Comment by charlesBochet** [comment]
Lastly, the lint CI is failing. Make sure to run your linter locally: `npx nx run twenty-front:lint:ci`

**Comment by mritosa** [comment]
Hi, thank you for feedback @charlesBochet @Weiko , I’will try to fix problems as soon as possible!

**Comment by mritosa** [comment]
Hi, i need some help @Weiko. 
When I redefined recordGqlFields like this 
image
Result was:
image
Also can you explain me why it doesnt fetch person and workspaceMember object but it only fetch their ids.

**Pull request closed without merging**
