### PR TITLE
fix: kanban column margin should extend to bottom

### LINKED ISSUE #7868: Kanban columns margin no longer extend to the bottom
## Bug Description
As per title

Screenshot 2024-10-20 at 00 36 04

## Expected behavior

Column margins should extend to the bottom.

Screenshot 2024-10-20 at 00 40 31

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194300&node-type=frame&t=IlVBRHG7XrFQOD7c-0

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
Fixes: #7868 

[Screencast from 2024-11-08 13-33-47.webm](https://github.com/user-attachments/assets/1de620d8-8f05-43f8-bde9-a2c9cbea4b9f)

### CODE REVIEW

**Review by ehconitin — COMMENTED** [review]
not fixed @harshrajeevsingh 

Screenshot 2024-11-08 at 14 10 23

**Comment by harshrajeevsingh** [comment]
@ehconitin Thanks, I see. It worked fine for me because the content list was large and extended to the container. Give me more time to look into it.

**Review by ehconitin — APPROVED** [review]
LGTM! Thanks @harshrajeevsingh! ;)

**Review by FelixMalfait — APPROVED** [review]
Perfect thank you!

**Pull request merged**
