### PR TITLE
[FEAT] Horizontal nav for mobile

### PR DESCRIPTION
**Pull request by siv-io**
twentyhq/core-team-issues#153 

@FelixMalfait as per your feedback, the desktop navbar is reused to display in mobile. 

**[FIX NEEDED BEFORE MERGING]**
**Everything works except the settings link.** 
The settings page is thereon the DOM but is not shown, couldn't figure out why.  

Would love if someone could figure out the settings part. 

Also, I've used some workarounds like reversing the flex which is counterintuitive but doesn't clutter the code. 

 
image

### CODE REVIEW

**Comment by Hitarthsheth07** [comment]
@Bonapara 

Fixed the loading skeleton:
https://www.loom.com/share/005fd1ca17b04e918f56eed378731c95?sid=a7c92cae-f3cf-4b55-93c3-ec661e3cb9bd

And the alignment:
Screenshot 2024-10-29 145034

**Comment by charlesBochet** [comment]
**Note:** We are a bit late on reviews! I'm attributing the oss-gg points to all opened PRs as Hacktoberfest event ends tonight. We will review the PR itself shortly

**Comment by lucasbordeau** [comment]
@ketanMehtaa @Hitarthsheth07 You're both solving the same issue with two different PR, could you please work only on one PR and test more thoroughly before marking it as ready, there are still problems.

Thank you both for your contribution !

**Comment by Hitarthsheth07** [comment]
> @ketanMehtaa @Hitarthsheth07 You're both solving the same issue with two different PR, could you please work only on one PR and test more thoroughly before marking it as ready, there are still problems.
> 
> Thank you both for your contribution !

Sure, would love to work together @ketanMehtaa

**Pull request closed without merging**
