### PR TITLE
[FIX] frontend commands updated to start with 'yarn'

### LINKED ISSUE #8082: Frontend commands must start with 'yarn' instead of 'nx'
## Bug Description

**_Sorry for making another 'docs issue/PR'. I just spend 30 mins figuring out the issue 
and don't want someone else to do the same!_**

Currently the frontend commands start with 'nx' and running them will give an error:
image

All the commands should start with 'yarn' instead of 'nx'.

### PR DESCRIPTION
**Pull request by siv-io**
FIX #8082

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Good feedback thanks for taking the time to contribute!
We actually recommend `npx nx` and not `yarn nx`, would you ming updating?
Also you could add: `npx nx graphql:generate twenty-front --configuration=metadata` which is also useful

Also in backend commands, would you mind adding something like this?

## Migrations

### For objects in Core/Metadata schemas (TypeORM)

```
npx nx typeorm twenty-server  -- migration:generate src/database/typeorm/metadata/migrations/nameOfYourMigration -d src/database/typeorm/metadata/metadata.datasource.ts # replace by core data source if necessary

```

### For Workspace objects (TwentyORM)
There are no migrations files, migration are generated automatically for each workspace, stored in the database, and applied with this command
```
yarn command:prod workspace:sync-metadata -f
```

Note for you / not to be added: yes we use yarn for this one because it's used in the prod environment where there are no dev dependencies / no npx



Thanks a lot!

**Comment by Hitarthsheth07** [comment]
> Good feedback thanks for taking the time to contribute!
> 
> We actually recommend `npx nx` and not `yarn nx`, would you ming updating?
> 
> Also you could add: `npx nx graphql:generate twenty-front --configuration=metadata` which is also useful
> 
> 
> 
> Also in backend commands, would you mind adding something like this?
> 
> 
> 
> ## Migrations
> 
> 
> 
> ### For objects in Core/Metadata schemas (TypeORM)
> 
> 
> 
> ```
> 
> npx nx typeorm twenty-server  -- migration:generate src/database/typeorm/metadata/migrations/nameOfYourMigration -d src/database/typeorm/metadata/metadata.datasource.ts # replace by core data source if necessary
> 
> 
> 
> ```
> 
> 
> 
> ### For Workspace objects (TwentyORM)
> 
> There are no migrations files, migration are generated automatically for each workspace, stored in the database, and applied with this command
> 
> ```
> 
> yarn command:prod workspace:sync-metadata -f
> 
> ```
> 
> 
> 
> Note for you / not to be added: yes we use yarn for this one because it's used in the prod environment where there are no dev dependencies / no npx
> 
> 
> 
> 
> 
> 
> 
> Thanks a lot!
> 
> 
> 
> 

Sure would absolutely do that. 

Also, there is a problem in windows wsl local setup that doesn't reflects the code changes while working on them. 

I am working on that issue will create a PR once that solved.

**Comment by FelixMalfait** [comment]
Thank you @Hitarthsheth07!

**Comment by Hitarthsheth07** [comment]
> Thank you @Hitarthsheth07!


Heyy @FelixMalfait 

Do you think we should add a note/step in windows(WSL) setup that you have to clone when inside wsl and in the /home directory (adding the repo in other dir may give error while installing node modules). 

The command to initiate postgres DB:

psql postgres -c "CREATE DATABASE \"default\";" -c "CREATE DATABASE test;" -c "CREATE USER twenty PASSWORD 'twenty';" -c "ALTER ROLE twenty superuser;"

You need to run this as a 'postgres' user 

sudo -u postgres psql -c "CREATE DATABASE \"default\";" -c "CREATE DATABASE test;" -c "CREATE USER twenty PASSWORD 'twenty';" -c "ALTER ROLE twenty superuser;

Or else it gives error in WSL.

**Comment by FelixMalfait** [comment]
@Hitarthsheth07 yes that makes sense, please also add it to the Linux tab. Thanks!

Sorry for the slow loading time, not sure we can fix that easily. We are using Mac in the core team and it boots in a few seconds :/

**Comment by charlesBochet** [comment]
I would actually recommend the following format:
`npx nx run {project}:{command} --parameter`

For instance: `npx nx run twenty-server:workspace:sync-metadata -f`. I don't remember exactly but there was non working edge case with `npx nx workpace:sync-metadata twenty-server -f`

**Comment by Hitarthsheth07** [comment]
> I would actually recommend the following format: `npx nx run {project}:{command} --parameter`
> 
> For instance: `npx nx run twenty-server:workspace:sync-metadata -f`. I don't remember exactly but there was non working edge case with `npx nx workpace:sync-metadata twenty-server -f`

Which command should be changed to this format. Are you referring to yarn command:prod workspace:sync-metadata -f

So as per your given format it would be 
`yarn twenty-server command:prod workspace:sync-metadata -f` is that correct?

**Comment by FelixMalfait** [comment]
Closing this one since you opened #8161 (ideally you can stay on the same PR, no need to open a new one thanks!)

**Pull request closed without merging**
