### PR TITLE
Adds KeyBoardNavigation and Enter hotkey Click for all DropDowns (#4365)

### LINKED ISSUE #231: All selectable lists should be navigable using arrow keys.
# Current behavior

Some `selectable lists` cannot be navigated up or down using the keyboard:

### UX elements:

- View Menu
Ignore the 15+ views with identical names. 😅
CleanShot 2024-03-07 at 18 06 18

- Filter Menu
CleanShot 2024-03-07 at 18 06 00

- Sort Menu
CleanShot 2024-03-07 at 18 05 42

- Options Menu
CleanShot 2024-03-07 at 18 05 28

- Descending/Ascending menu:
image

- Relation Selection menu:
CleanShot 2024-03-07 at 18 07 53

# Desired behavior

We want all these menus to be navigable by arrow keys. Pressing "Enter" should select the focused item, and pressing "Escape" should close the menu or picker.

### LINKED ISSUE #4365: All selectable lists should be navigable using arrow keys.
# Current behavior

Some `selectable lists` cannot be navigated up or down using the keyboard:

### UX elements:

- View Menu
Ignore the 15+ views with identical names. 😅
CleanShot 2024-03-07 at 18 06 18

- Filter Menu
CleanShot 2024-03-07 at 18 06 00

- Sort Menu
CleanShot 2024-03-07 at 18 05 42

- Options Menu
CleanShot 2024-03-07 at 18 05 28

- Descending/Ascending menu:
image

- Relation Selection menu:
CleanShot 2024-03-07 at 18 07 53

# Desired behavior

We want all these menus to be navigable by arrow keys. Pressing "Enter" should select the focused item, and pressing "Escape" should close the menu or picker.

### PR DESCRIPTION
**Pull request by Faisal-imtiyaz123**
fixes twentyhq/core-team-issues#231

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey @Faisal-imtiyaz123 thanks for the attempt! Unfortunately this isn't really in line with how it's done in the rest of the code base 

See a related only PR https://github.com/twentyhq/twenty/pull/5983/files by @AdityaPimpalkar 

We have existing hooks, e.g.`useScopedHotkeys` ; `useSelectableList`

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait Thanks for your feedback. I was also skeptical about it being accepted. I will definitely check the PR and try to make a new PR along the lines of code base standards. I request you to do the favour of assigning it to me.

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait I saw the PR . To enable navigation for ObjectFilterDropDownSelect, he has changed the code in that component, so one way I am thinking of is to modify the lists mentioned in the PR one by one. Is that ok?? or do you want like a universal feature of keyboard navigation on all drop-downs??

**Comment by lucasbordeau** [comment]
@Faisal-imtiyaz123 We already have a universal useScopedHotkeys to handle hotkeys.

What we should do is try to call useScopedHotkeys in the right places and by trial-and-error reach a level of UX which is satisfying.

**Comment by FelixMalfait** [comment]
Hey @Faisal-imtiyaz123 I'm going to close this because the code is too different from the rest of the code base and doesn't follow the right patterns. But feel free to raise a new PR whenever you want! Thanks a lot for your contributions

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait I stopped working here because @lucasbordeau assigned this to himself.

**Comment by FelixMalfait** [comment]
@Faisal-imtiyaz123 oh sorry for the confusion! when we assign a PR on our side it means "that person from the core teams owns the review and followup", it doesn't mean we take over. When we assign ourselves an issue it means we do though.

**Comment by FelixMalfait** [comment]
Yes of course @Faisal-imtiyaz123!

**Pull request closed without merging**
