### PR TITLE
chore: create security.txt

### PR DESCRIPTION
**Pull request by daallgeier**
Adding a security.txt file enables security researchers to quickly and easily see where they can submit security issues and know that they are being taken serious. From the proposal website:

> When security risks in web services are discovered by independent security researchers who understand the severity of the risk, they often lack the channels to disclose them properly. As a result, security issues may be left unreported. security.txt defines a standard to help organizations define the process for security researchers to disclose security vulnerabilities securely.

See also https://securitytxt.org

Additionally it seems like one can enable Private Reporting for Security Issues under the Security Tab.  See also: 
https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability

### CODE REVIEW

**Review by FelixMalfait — APPROVED** [review]
Great thanks!

**Comment by FelixMalfait** [comment]
Actually I read too quickly, could you please move it here instead of the root? https://github.com/twentyhq/twenty/tree/main/packages/twenty-website/public

(As it's supposed to be on the website)
Thanks!

**Comment by daallgeier** [comment]
moved it there.  Glad you approve it being around.

**Comment by FelixMalfait** [comment]
It won't appear yet as we need to fix the settings on Cloudflare to point either to Framer or to the NextJS site depending on the URL (right now it's 100% Framer). I'll do that in Feb!

**Comment by FelixMalfait** [comment]
Merging! Thanks

**Pull request merged**
