### PR TITLE
added light background for better hover visibility on dark theme

### LINKED ISSUE #7969: Light icon button hover is not visible in Dark mode
# Bug Description

The `filter`, `sort`, and `options` button hovers are not visible in dark mode.

### Light Mode (Desired):

https://github.com/user-attachments/assets/0a347170-92d3-4724-8ada-534b36d40d18

### Dark Mode (Missing Hover):

https://github.com/user-attachments/assets/35889819-ad40-4884-b5fa-d7f412b81bea

### Storybook Component

The Storybook component appears to be properly coded:

https://storybook.twenty.com/?path=/story/ui-input-button-lightbutton--default&args=accent:tertiary

https://github.com/user-attachments/assets/84fb9316-de1c-4be4-a2e3-f3ce9d597e35

### PR DESCRIPTION
**Pull request by abdullah5361k**
fixes: #7969 

## What does this PR do?

Apply a lighter background color to enhance the hover effect in dark mode.

twenty-hover

### CODE REVIEW

**Comment by abdullah5361k** [comment]
@Bonapara Could you please review this pull request? I'm unsure why the last one didn't work as expected.

**Comment by Bonapara** [comment]
Thanks @abdullah5361k, can you also add back the hover on the view switcher dropdown? CleanShot 2024-10-25 at 09.37.30.mp4

**Comment by abdullah5361k** [comment]
> Thanks @abdullah5361k, can you also add back the hover on the view switcher dropdown?

Sure, I’ll. Apologies for the delayed response—I'm currently doing an internship with a daily 70-kilometer commute each way, which sometimes delays my replies.

**Comment by abdullah5361k** [comment]
@Bonapara, could you please take a look at my pull request and provide feedback?

**Review by Bonapara — APPROVED** [review]

**Comment by Bonapara** [comment]
Hi @abdullah5361k, thanks, looks good to me!

**Comment by Bonapara** [comment]
Thank you for contributing, and good luck with your internship! What are you doing?

**Comment by abdullah5361k** [comment]
> Thank you for contributing, and good luck with your internship! What are you doing?

Thank you! I’m currently involved in projects focused on web development.

**Comment by Devessier** [comment]
Hi @abdullah5361k, I reviewed your PR. Your fix worked well! The components you modified weren't well structured; we should rely on a css filter to apply different colors to the background and the text on hover. It's much more predictable to set explicit colors. That's the refactor I made. Thank you a lot for your time!

**Comment by abdullah5361k** [comment]
> Hi @abdullah5361k, I reviewed your PR. Your fix worked well! The components you modified weren't well structured; we should rely on a css filter to apply different colors to the background and the text on hover. It's much more predictable to set explicit colors. That's the refactor I made. Thank you a lot for your time!

Thank you, @Devessier , for the feedback.

**Pull request merged**
