### PR TITLE
fix: created by prefill value for demo instance

### LINKED ISSUE #6924: Update demo data "Created by" values
# Current Behavior

When we create a workspace, it includes samples from 5 companies and 5 people to ensure it doesn't feel empty for first-time users. The "Created by" value is currently set to "System."

CleanShot 2024-09-06 at 14 46 34

# Desired Behavior

We want to update the "Created by" value to "Twenty (Sample data)" and add the Twenty logo to enhance its appearance.

CleanShot 2024-09-06 at 14 47 08

### PR DESCRIPTION
**Pull request by Nabhag8848**
### ISSUE
- Closes #6924

### CODE REVIEW

**Comment by Nabhag8848** [comment]
@Bonapara Ready for review

**Comment by charlesBochet** [comment]
@Nabhag8848 I believe @FelixMalfait wanted to discuss this one with @Bonapara prio to merging it. 
It's likely that we want to introduce another creator source instead of only modifying the createdByName

**Comment by FelixMalfait** [comment]
I'm sorry @Nabhag8848 I didn't see this PR. Someone also raise a PR which I reviewed and ended up doing something else  https://github.com/twentyhq/twenty/pull/7424
(I ended up keeping System and adding a different icon)

**Pull request closed without merging**
