### PR TITLE
Chore/object meta data image

### LINKED ISSUE #181: ObjectMetadata decorator have an imageIdentifier properties
## Scope & Context

Identifiers are used by some client components to represent a record.

Screenshot 2024-01-30 at 18 46 36

Those identifiers are mapped to existing field-metadata and the object-metadata table contains both labelIdentifierFieldMetadataId and imageIdentifierFieldMetadataId.
We want to add a new property to the ObjectMetadata decorator to define those fields in order to have those defined during standard objects creation

This could look like this.
```
@ObjectMetadata({
  namePlural: 'people',
  labelSingular: 'Person',
  labelPlural: 'People',
  description: 'A person',
  icon: 'IconUser',
  labelIdentifier: 'name',
  imageIdentifier: 'avatarUrl',
})
```

## Technical inputs

TBD

See also: https://github.com/twentyhq/twenty/pull/7616#issuecomment-2432067776

### LINKED ISSUE #3710: [Flexible-Schema] ObjectMetadata decorator have a labelIdentifier and an imageIdentifier properties
## Scope & Context

Identifiers are used by some client components to represent a record.

Screenshot 2024-01-30 at 18 46 36

Those identifiers are mapped to existing field-metadata and the object-metadata table contains both labelIdentifierFieldMetadataId and imageIdentifierFieldMetadataId.
We want to add a new property to the ObjectMetadata decorator to define those fields in order to have those defined during standard objects creation

This could look like this.
```
@ObjectMetadata({
  namePlural: 'people',
  labelSingular: 'Person',
  labelPlural: 'People',
  description: 'A person',
  icon: 'IconUser',
  labelIdentifier: 'name',
  imageIdentifier: 'avatarUrl',
})
```

## Technical inputs

TBD

### PR DESCRIPTION
**Pull request by Aditya-PS-05**
closes twentyhq/core-team-issues#181

### CODE REVIEW

**Comment by charlesBochet** [comment]
@Aditya-PS-05 thank you! You seem to have conflicts, could you fix them before we review?

**Comment by Aditya-PS-05** [comment]
Ok, I am trying to fix this as soon as possible.

**Comment by charlesBochet** [comment]
@Aditya-PS-05 any update on this one? :)

**Comment by FelixMalfait** [comment]
Sorry I'll close this as it's been open for some time.
The issue was mis-categorized as "good first issue", the first part you did is correct (and deserve to be merged if there wasn't conflict), but the hard bart is about actually implementing the imageIdentifier in the frontend, for example the imageIdentifier of a company is the domain name so there need to be a special implementation for Links fields, etc. Quite a big task!!!

Please feel free to re-open with the first part.

Thank you!!

**Pull request closed without merging**
