### PR TITLE
Update workflows to optimize CI processes 

### PR DESCRIPTION
**Pull request by yadavshubham01**
This Pull Request addresses the need to optimize our Continuous Integration (CI) workflows for Playwright tests and release processes. The changes implemented aim to reduce unnecessary resource usage by conditionally executing jobs based on relevant file changes and Implement https://github.com/tj-actions/changed-files step 

## Changes logs
- Updated `ci-test-docker-compose.yaml , ci-chrome-extension.yaml ` to check for changed files before running tests.
- Updated `ci-front.yaml , ci-utils.yaml , ci-website.yaml , ci-server.yaml` to check for changed files before running tests.
- Enhanced `playwright.yml` to skip unnecessary tests based on file changes.

### CODE REVIEW

**Comment by yadavshubham01** [comment]
@cyborch please review this PR

**Review by charlesBochet — APPROVED** [review]
Love it!

**Comment by charlesBochet** [comment]
Thank you @yadavshubham01, that's it!

**Comment by charlesBochet** [comment]
@yadavshubham01 could you make the CI work on merge in main?

Changed files is working great for the pull request case where we can compare file between main and the PR but does not work when we push on main (once the PR is merged, it re-triggers the CI)

image

We would need:
- keep the CI logic as it was before for push events (conditional on paths + avoid using changed-files)
- keep the CI logis as in your change for pr events (no conditional paths + using changed-files)

Would be great if you could take care of it!

We can award 300 additonal points :)

**Comment by charlesBochet** [comment]
ok, it's good then!

**Comment by yadavshubham01** [comment]
@charlesBochet thank you for your feedback 🎉

**Pull request merged**
