### PR TITLE
Align Workspace Switcher with Breadcrumb by Adjusting Height

### PR DESCRIPTION
**Pull request by ehconitin**
@Bonapara 
Issue #6375 

This change makes sure the container height is 32px instead of 28px.
should the container inside it should also be 32px, please refer video below for context

https://github.com/user-attachments/assets/fe97f0de-e1fd-4fda-a9a7-e9585469c530

Also skeleton height is 20px (refer video below), the black component in the video is the skeleton for this particular component.
What should be skeletons height?

https://github.com/user-attachments/assets/0956c8d9-8e4e-4c20-bb71-7fb1e2cba4fd

### CODE REVIEW

**Comment by Bonapara** [comment]
@ehconitin, it's okay that the skeleton height is 20px (the height of the icon/text), but it should be vertically centered within the container. Thanks!

**Comment by ehconitin** [comment]
@Bonapara 

This might sound absurd but when I am checking skeleton now its of height 16px which is also the size of logo and text
but the allignment is completely off w.r.t the adjacent skeleton. But your could see in yesterdays PR description the video does show the height as 20px.
I am baffled

Refer the video.
Is this the same for you ?
A bit confused :(

https://github.com/user-attachments/assets/1e584a2a-c345-41b5-8ac4-1771efac125c

**Comment by Bonapara** [comment]
Hi @ehconitin, here is the figma of the skeleton loading. Maybe you can check the measurements on Figma? Tell me if it's still not clear

image

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=25426-60098&t=ISpVG0j2SLv3paOI-11

**Comment by ehconitin** [comment]
Ill have a look at it @Bonapara, if I still cant figure it out will reach out to you.

**Comment by ehconitin** [comment]
@Bonapara 
I hardcoded styles from figma.
please let me know what do you think.
Is this approach good??



Screenshot from 2024-07-25 00-56-44

**Comment by Bonapara** [comment]
Hi @ehconitin, what do you mean by hardcoded? In Figma, I used the same component what about in the code?

CleanShot 2024-07-25 at 09 51 48

**Comment by ehconitin** [comment]
@Bonapara,
In code the skeleton and workspace switcher do not share same component. If that was the case it would be very easy and smooth fix. Thats a good point, I think they should be sharing the same component which will make future changes or implementation way easier. For now its a balancing act on how do I match skeletons styles to that of Workspace switcher. Its the same with `RightPanelSkeletonLoader`
@lucasbordeau what do you think?

**Comment by charlesBochet** [comment]
Hi @ehconitin, thanks for the detailed approach.

Agree, right now we have a big component containing nav skeleton which needs to be updated when we touch the nav which will likely lead to an outdated skeleton. What would be great is 
- to have a React context "NavSkeletonLoaderContext" containing the information if the skeleton should be displayed or not (this way we don't have to compute it in multiple places like what we have right now)
- but then break the big skeleton into smaller ones loaded by each part of the Navbar and reading from this context

I think this can be done in another PR, would be great if you can tackle it!

**Review by charlesBochet — APPROVED** [review]
LGTM, thank you!

**Comment by ehconitin** [comment]
@charlesBochet 
Thanks,
Could u create an issue for me to work on the navskeletoncontext.
Would love to work on it.

**Pull request merged**
