### PR TITLE
Add custom field types on seed

### LINKED ISSUE #6364: Improve `workspace:seed:dev` command to seed all field types
## Scope & Context

When seeding the database in dev mode.

## Technical inputs

Right now we use the seeds that were relevant months ago, but now we have multiple new field types like JSON, Address and Links, and we have to create them manually each time we want to test them while developing our features.

What would really help all the community is to seed people and company with all possible field types, and fill all rows with more demo data so our initial tables aren't so empty.

A nice good first issue !

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #6364

### CODE REVIEW

**Comment by prateekj117** [comment]
@lucasbordeau This is ready for review.

**Comment by lucasbordeau** [comment]
@prateekj117 Nice work !

Final step, could you please add more field types, I'll give you a list : 

```ts 
  DATE = 'DATE',
  BOOLEAN = 'BOOLEAN',
  NUMBER = 'NUMBER',
  NUMERIC = 'NUMERIC',
  LINKS = 'LINKS',
  CURRENCY = 'CURRENCY',
  FULL_NAME = 'FULL_NAME',
  RATING = 'RATING',
  SELECT = 'SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  ADDRESS = 'ADDRESS',
  RAW_JSON = 'RAW_JSON',
  RICH_TEXT = 'RICH_TEXT',
```

**Comment by prateekj117** [comment]
Added some more custom types @lucasbordeau .

**Review by Weiko — APPROVED** [review]
LGTM, thank you 🙏

**Comment by Weiko** [comment]
Ideally, we should also seed viewFields to make them visible in default views. In the meantime we can add them via the UI which is good enough imho!

**Pull request merged**
