### PR TITLE
fix: record board column border spans the available screen height

### LINKED ISSUE #5273: Record board columns design fix (full height borders)
Column separators in the record board should take the full heigh, instead it doesn't look good if the board doesn't have any card 

See current behavior:
Screenshot 2024-05-03 at 15 13 31

cc @Bonapara

### PR DESCRIPTION
**Pull request by orinamio**
Resolves #5273

### CODE REVIEW

**Comment by FelixMalfait** [comment]
I'm going to be annoying but this introduces a small unnecessary vertical scroll, could you try fix that? 

Screenshot 2024-05-04 at 15 59 46


Thanks a lot!

**Comment by orinamio** [comment]
@FelixMalfait I agree the scroll is unnecessary and ugly.

A solution for the vertical scroll is to hide the scroll permanently using `display: none;` or something similar. However, I don't think it's the best approach. When more row items are in a column, the scroll should be visible. This is good for the user experience.

I tried to use [`@container`](https://developer.mozilla.org/en-US/docs/Web/CSS/container) CSS. But this breaks the Drag and Drop component. I couldn't find out why it was happening.

```
  container-type: size;

  .os-scrollbar-vertical {
    display: none;
  }

  @container (height > [SIZE]) {
    .os-scrollbar-vertical {
      display: unset;
    }
  }
```

The container rule breaks the dnd:

https://github.com/twentyhq/twenty/assets/16918891/8267ea7f-d0f8-40d8-87b7-6a30519fd0a1



Furthermore, using JavaScript to fix this doesn't seem appropriate.

Do you have any suggestions? cc: @Weiko

**Comment by orinamio** [comment]
This is the behaviour when the scrollbar is removed:

https://github.com/twentyhq/twenty/assets/16918891/9a11446f-a348-4d58-9659-b78402af9d2e

If this is acceptable, I'll go ahead and add this fix. Otherwise, I ask that someone else looks into it.

**Comment by charlesBochet** [comment]
@orinamio Closing this PR as we still want to keep the scrollbar. Feel free to re-open a PR if you get back to it, we will review it!

**Pull request closed without merging**
