### PR TITLE
Improve error message for Graphql API 

### PR DESCRIPTION
**Pull request by thibaultleouay**
CleanShot 2024-10-17 at 11 39 39

This improves this error message.

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
Good idea :) Thank you

**Comment by charlesBochet** [comment]
@thibaultleouay You have lint issues, could you fix those (npx nx run twenty-server:lint:ci to detect them locally)

 You have created a branch from your main branch so I cannot commit to your branch to help you

**Comment by thibaultleouay** [comment]
@charlesBochet  with gh cli you can do 
`gh pr checkout 7805`

**Comment by charlesBochet** [comment]
> 7805

I've learned something!

**Pull request merged**
