### PR TITLE
Improve the layout of the Workflow Visualizer

### PR DESCRIPTION
**Pull request by Devessier**
- Increase the dimensions of the ReactFlow nodes. This allows to ditch scaling which made it hard to get the width of the nodes as they were visually scaled by 1.3.
- Center the flow when the flow mounts and when the state of the right drawer opens.
- Put the node type inside of the node so it doesn't overlap with the arrow
- Make the edges non deletable

We'll have to make a refactor so the viewport can be animated properly: https://github.com/twentyhq/twenty/issues/8387.

https://github.com/user-attachments/assets/69494a32-5403-4898-be75-7fc38058e263

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Great! Make sure to check dark mode
Screenshot 2024-11-11 at 09 36 20

**Comment by Devessier** [comment]
I will fix the dark mode in another PR.

**Review by martmull — APPROVED** [review]
Nice job, I wonder if we can get rid from the useEffect but I don't see a way to remove it. Behavior looks really nice. LGTM

**Comment by Devessier** [comment]
Thank you, @martmull. I created an issue to refactor the useEffect. Maybe we can give it a look later.

See https://github.com/twentyhq/twenty/issues/8387

**Comment by Devessier** [comment]
Fixed https://github.com/twentyhq/private-issues/issues/131

**Pull request merged**
