### PR TITLE
fix: button group (dropdown) spacing

### PR DESCRIPTION
**Pull request by prakhar1535**

### CODE REVIEW

**Comment by prakhar1535** [comment]
#7386

**Comment by ehconitin** [comment]
Hi @prakhar1535,
I'm closing this PR since we don’t allow merges from the main branch of a forked repository. Please open a new PR from a feature branch instead.😊

**Comment by prakhar1535** [comment]
sure @ehconitin will raise it from a feature branch

**Comment by prakhar1535** [comment]
hey @ehconitin raised a new pr #7409 against the same issue

**Pull request closed without merging**
