### PR TITLE
feat: Write Blog Post About 20 (750 points)

### PR DESCRIPTION
**Pull request by Khaan25**
image

### CODE REVIEW

**Comment by FelixMalfait** [comment]
/award 250 this describes quite well what the product will probably be like in the future but doesn't reflect the current product

**Comment by Khaan25** [comment]
Right. Shall I write another one with current features? @FelixMalfait

**Comment by FelixMalfait** [comment]
Thanks but we wouldn't give all points unless it's a really good article that isn't AI generated

**Comment by Khaan25** [comment]
Okay, Got it. I did took AI help but not whole article. Will write another one about current features.

**Comment by FelixMalfait** [comment]
Just edit the current article instead of creating a new one. And make it a really good article that's useful for people :)

Thanks!

**Comment by Khaan25** [comment]
Okay, Got it! Shall I create new PR or just tag you again once I've created?

**Comment by Khaan25** [comment]
Hey @FelixMalfait, I've updated the blog, I've created a new invoice data model and shared how a person can create his own and benefit from twenty. Hope it's gonna useful for people who are new to Twenty 😄

Let me know your thoughts, haven't used GPT here, all custom written

**Comment by FelixMalfait** [comment]
/award 500 
Much better!!! Thank you @Khaan25

**Pull request merged**
