### PR TITLE
Add industry column to company

### LINKED ISSUE #3048: Add new field on company: industry
Related: https://github.com/twentyhq/twenty/issues/2977

We want to create a new standard fields, of type "select" to represent the industry.

Reference for possible values:
https://docs.peopledatalabs.com/docs/industries

### PR DESCRIPTION
**Pull request by brendanlaschke**
Two questions:
* Is it correct we can edit Select options on an otherwise disabled settings page? 
Bildschirmfoto 2024-04-25 um 10 14 11

* Does the field need to be added to the all companies view or another object/file ?

Bildschirmfoto 2024-04-25 um 10 06 17

closes  #3048

### CODE REVIEW

**Comment by charlesBochet** [comment]
These are very good questions. Here is the product vision on field.options (for SELECT and MULTI-SELECT):
- introduce isCustom on the option
- introduce isActive on the option
- introduce standardId on the option

Then, we need to:
- Settings UI: do not allow to modify/delete `isCustom: false` options except the position and color
- Settings UI: allow to disable `isCustom: false` (we need design for that @Bonapara) + unset records that have this value
- sync scripts: start syncing `isCustom: false` options in sync-metadata script
- remove `isActive: false` options from SELECT and MULTISELECT FieldInputs

**Comment by charlesBochet** [comment]
This can be treated in another PR though (likely in multiple PRs)

**Comment by charlesBochet** [comment]
We don't want to add it in the company view for now

**Comment by charlesBochet** [comment]
@FelixMalfait do you have any though on that?

**Comment by Bonapara** [comment]
CleanShot 2024-04-25 at 15 37 54

For V1, the `Delete option` will only be available Custom Options menu. Only display the "Disabled" section when a field has been disabled.

**Comment by charlesBochet** [comment]
@FelixMalfait should we merge this PR?

**Review by A1exKH — APPROVED** [review]
LGTM.

**Comment by FelixMalfait** [comment]
Hey I'm sorry @brendanlaschke this was great but I think I will close it for now. 
I created this issue in the context of adding multiple fields for automated data enrichment (e.g. Apollo.io). So the "key" (i.e. value not label) isn't the right one to do the matching. We should re-open this when we have a clear strategy on data enrichment

**Pull request closed without merging**
