### PR TITLE
Add event emitter and event listener to workspace-query-runner

### PR DESCRIPTION
**Pull request by jss475**
Reference: [#3736 ](https://github.com/twentyhq/twenty/issues/3736)

Implement event emitter and event listener in place of `triggerWebhooks`. This was done for the workspace-query-runner service.

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey @jss475 thanks for giving it a shot, that's a good start!

First, we don't want to break the webhook feature. The event layer is an intermediate layer but we still want to trigger webhooks. Second, we want to design something elegant to manage events throughout the app.

We would need to create dedicated Events objects (e.g. ObjectCreated, ObjectedDeleted...)
We don't want to implement a generic WorkspaceQueryListener but we actually now want listeners to be on to the business logic side. So for example for webhooks I think we'd want to create a module within /core dedicated to webhooks and move everything there (the existing jobs + create a new listener). 

The issue wasn't very detailed, this requires some creativity and exploration to build the right design - not sure what it will be yet! Still open to iterating?

**Comment by jss475** [comment]
@FelixMalfait Yup I'm open to iterating! That makes sense I will add the web hook feature back in and start experimenting with the listener. 

I'm not sure if I'm understanding the second part correctly. Here's what I gather. I essentially take out the `triggerWebhooks` functionality that's currently in the `/workspace` folder and move it to `/core`. I then add event listeners based on the webhooks that are triggered with dedicated event objects/entities (ObjectCreated, ObjectDeleted...) that I'll create.

If it's easier to explain on a call, I can always hop on! Thank you!

**Comment by FelixMalfait** [comment]
Yes that's correct! We don't really have that pattern in the codebase yet but we want to have the metadata layer through business events ("company created", "person updated", etc.) and be able to implement business logic that responds to those events a separate modules. Webhooks is a first use case. Maybe tomorrow we'll create a module "data enrichment" that listens to company creation events and update them with data pulled from LinkedIn, or we could built an "audit log" module that catches the events and store them in log files.

**Comment by charlesBochet** [comment]
@jss475 Thanks for your PR, we have heavily discussed it internally and decided to go with the following implementation: https://github.com/twentyhq/twenty/pull/3887

Your help is greatly appreciated even if we don't merge this one. Feel free to work on any other issue on the project :)

**Comment by jss475** [comment]
@charlesBochet All good! It was fun trying it out myself!

**Pull request closed without merging**
