### PR TITLE
[FIX] fix navigation overflow

### LINKED ISSUE #7733: Navigation Bar extends beyond the screen size
## Bug Description

When the items in the left navigation bar are filled it extends beyond the screensize. 

overflow

## Expected behavior

When items overflow the navigation bar should allow vertical scroll.

### PR DESCRIPTION
**Pull request by siv-io**
FIX #7733

Fixes the overflow and responsive problem on large and small devices. 

image
image

The 'Workspace' title is fixed and only links under it are scrolled when overflown.

### CODE REVIEW

**Comment by Hitarthsheth07** [comment]
Heyy, is there OSS points on finding and solving issues like this?

**Review by lucasbordeau — APPROVED** [review]

**Comment by Hitarthsheth07** [comment]
@lucasbordeau the merging was blocked for some reason. 

Also, could you please assign appropriate OSS points to issue and PR 

Cheers!

**Comment by charlesBochet** [comment]
@Hitarthsheth07 you have lint issue (see CI) could you fix them?

**Comment by Hitarthsheth07** [comment]
@charlesBochet the ci has failed for CI-front. Is there a issue on my side or a server problem. Thanks.

**Pull request merged**
