### PR TITLE
fix: Fixed LinkedIn links with unicode

### LINKED ISSUE #3873: LinkedIn links with unicode are truncated when displayed
## Bug Description

A LinkedIn button in the People screen with unicode characters in the URL gets truncated at that character.

Example:
A LinkedIn URL such as `https://www.linkedin.com/in/håkan-fisk` is displayed as a button with only the character `h` in the LinkedIn column

## Expected behavior

The button in the LinkedIn column should in this case display `håkan-fisk`

### PR DESCRIPTION
**Pull request by zvolcsey**
Hi! I modified the regex.
```SocialLink.tsx``` - /(?:https?:\/\/)?(?:www.)?linkedin.com\/(?:in|company)\/(.*)/ - allow any chars at the end
```URLDisplay.tsx``` - /^(http|https):\/\/(?:www\.)?linkedin.com(\w+:{0,1}\w*@)?(\S+)(:([0-9])+)?(\/|\/(.*))?/ - allow any chars at the end

First I just changed the ```SocialLink.tsx``` and it worked fine. I also changed the ```checkURLType``` function now. This is the first check and it can return a proper linkedin type. It worked well on the people screen.

In the conversation was mentioned 
https://github.com/twentyhq/twenty/blob/b0b033aec9fed61ddefd31b5f21bb7b7d2464571/packages/twenty-front/src/utils/is-url.ts#L6
but I could not find this function in the ```URLDisplay.tsx``` and in the ```SocialLinks.tsx```. Should I also change this regex? The ```SocialLink``` component displays the ```håkan-fisk``` username well even without it.

https://github.com/twentyhq/twenty/assets/41576384/0d854da1-ddf0-4362-8d99-dcc69eb26ec3

Closes #3873

### CODE REVIEW

**Comment by charlesBochet** [comment]
@zvolcsey Thank you! 
Could you extract these logic into utils.ts : I think we can re-use them later and also it would be great to test them to make sure the case mentionned in https://github.com/twentyhq/twenty/issues/3873 stays covered

**Comment by zvolcsey** [comment]
@charlesBochet Hi! Your welcome. 

Which logic do you think? I should extract the ```checkURLType``` function into a utils file. (twenty-front/src/utils).
And should I make a test for this function to return 'linkedin' string if the url is 'https://www.linkedin.com/in/håkan-fisk'?
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/field/display/components/URLDisplay.tsx#L26

OR Should I write a function for these two if statements. Return the linkedin or twitter username.
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/navigation/link/components/SocialLink.tsx#L37

**Comment by charlesBochet** [comment]
@zvolcsey I would say both! front/src/utils looks to be a good folder for now, we might re-organize them a bit later but the structure is still unclear to us

**Comment by zvolcsey** [comment]
@charlesBochet @FelixMalfait  Hi! I wrote two utils function ```checkUrlType```(return LinkType) and ```getDisplayValueByUrlType``` (return the username from the url). I also wrote tests for each functions.

The ```LinkDisplay.tsx``` and the ```URLDisplay.tsx``` are roughly the same code. The ```LinkDisplay``` is used in other components.
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/field/display/components/URLDisplay.tsx
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/field/display/components/LinkDisplay.tsx

Should I change the twitter regex to accept the usernames with unicode? ```https://www.twitter.com/håkan-fisk``` => ```@h```

**Comment by zvolcsey** [comment]
Hi! @charlesBochet I made some changes based on the previous review.
I wrote about changes here: https://github.com/twentyhq/twenty/pull/3953#issuecomment-1944351624

The PR label is still `awaiting author`. If you have time, would you review the changes? Thank you in advance.

**Review by charlesBochet — APPROVED** [review]
Apologies for the slow review, thanks for adding the tests. Looks good to me :)

**Pull request merged**
