### PR TITLE
Disable buffered logs

### PR DESCRIPTION
**Pull request by brody192**
Hosts like Railway use line scanners and thus when logs are buffered the result is that no logs show up.

### CODE REVIEW

**Comment by charlesBochet** [comment]
@brody192 I've actually looked into this a bit more deeply and I am not sure to understand the problem.
The bufferLog should only delay the logs to wait for the nestjs app to be loaded but not change their format. Why is it an issue on railways?

**Comment by brody192** [comment]
in my testing it just ends up looking like there are no logs coming through, even when ran for an hour, when logs are being buffered instead of immediately flushed. there are no lines for railway to scan so nothing gets sent to the deploy logs

**Comment by charlesBochet** [comment]
can you try again with the latest version of main?
Make sure that you have the following env variables setup:
LOG_LEVELS=error,warn,log
LOGGER_DRIVER=console

It should work, I don't think it is specific to Railways

**Comment by brody192** [comment]
looks like log buffering is still enabled, it's not going to work if logs aren't flushed on every log write, otherwise there's no logs for railways logging infrastructure to scan over.

I've tested twenty with and without log buffering enabled, logs only show when buffering is disabled.

buffered logs is the number one reason we see users ask why they can't see their app's logs.

**Comment by charlesBochet** [comment]
Interesting! I have no deep experience in this part, so I'm going to ask naive questions :p 

I'm having trouble to understand how the fact NestJS log buffering is working locally but not on with railway?
What makes it works in local on my computer but not on railway containers/server?

Here is my local console output when I launch twenty-server on my computer:
image

**Comment by brody192** [comment]
on railway they use a line scanner to parse each log line, but if logs are in a buffer that doesn't work, it only works when each log line is flushed individually, your local terminal has no issues showing you the log buffer.

**Comment by charlesBochet** [comment]
@brody192 Ok, could we add a LOGGER_IS_BUFFER_ENABLED env variable, default true, optional
- in .env.example
- in doc (self hosting > env variables)
- in environment.service.ts
- use it in main.ts, command.ts, queue-worker.ts

**Comment by brody192** [comment]
I do not see any benefits to having log buffering enabled anyway. please share your reasoning for wanting it enabled (by default)

**Comment by charlesBochet** [comment]
@brody192 If you don't enable it, it seems that NestJS is not sending the startup logs through the logger
`In the example above, we set the bufferLogs to true to make sure all logs will be buffered until a custom logger is attached (MyLogger in this case) and the application initialisation process either completes or fails. If the initialisation process fails, Nest will fallback to the original ConsoleLogger to print out any reported error messages. Also, you can set the autoFlushLogs to false (default true) to manually flush logs (using the Logger#flush() method).`

I feel the default behavior should be that all logs go to the desired logger (if you setup a S3 logger, you also want the startup logs to go there)

I think as long as it can be enabled through env vars, so it also works with railway scanner, everybody should be happy!

**Comment by charlesBochet** [comment]
@brody192 I'll go for this approach to unblock Railway users. Beside logs, did you manage to deploy Twenty on Railway?

**Review by charlesBochet — APPROVED** [review]

**Comment by charlesBochet** [comment]
This is great!
@FelixMalfait FYI, we shoud definitely add this to the self hosting guide so people can easily self host on Railway!

**Comment by brody192** [comment]
self-hosting with my template would be as easy as clicking deploy now, saving the configs, filling out the SMTP stuff, and then clicking the final deploy button, wait a bit and you have a ready-to-use install of twenty!

**Comment by FelixMalfait** [comment]
@brody192 that'd be amazing. I had tried to deploy to Railway but I didn't manage to do it because we rely on pg_graphql and they didn't support this Postgres extension / deployment of a custom Postgres through Docker.
Long-term we might have to find an alternative to make it easier for people to deploy, but right now it's a core piece of our backend and Twenty cannot work without this extension

**Comment by brody192** [comment]
Railway supports docker images now and everything in the template deploys from a twenty docker image including the database!

**Comment by FelixMalfait** [comment]
Oh great!

**Comment by brody192** [comment]
I've now added `LOGGER_IS_BUFFER_ENABLED` set to `false` on the template, thanks for everything!

**Pull request merged**
