### PR TITLE
[oss.gg] create-custom-theme

### PR DESCRIPTION
**Pull request by sateshcharan**
image

image

image

Quest:
create-custom-interfact-theme

Points:
750

[Figma URL](https://www.figma.com/design/2qlAPS3llwf8jrWKGHEf6O/Twenty-(sateshcharan)?node-id=1633-94880&t=GIceWxqyY0ajWXnZ-1) Hope you like the design !

### CODE REVIEW

**Comment by Bonapara** [comment]
Thanks for sharing this theme @sateshcharan. Maybe one day we will switch to gradients!

**Review by Bonapara — APPROVED** [review]

**Comment by sateshcharan** [comment]
@Bonapara, may I submit another entry for a chance at higher points?

**Comment by Bonapara** [comment]
You can improve it, sure!

**Pull request merged**
