### PR TITLE
Add env variable docs

### PR DESCRIPTION
**Pull request by brendanlaschke**
We now have so many environment Variables maybe we should document them ? 

Bildschirmfoto 2023-11-12 um 00 35 28

Descriptions may not be perfect - if you find better ones I will change them ;)

### CODE REVIEW

**Comment by charlesBochet** [comment]
@brendanlaschke thanks, I think it's a good idea. We kind of use .env.example to document it. Maybe we could autogenerate the doc based on .env.example?

@FelixMalfait What do you think?

**Comment by FelixMalfait** [comment]
Nice! I agree we would benefit from having a better documentation on this!
But introducing a second source of truth means it will inevitably end up out-of-sync (I'd bet 10:1 on that 😁). 

A generator based on the .env.example doesn't seem right to me because .env is not a great place to add text and comments. 

Maybe we could edit ci-docs.yaml and create a small js script post build that checks both files are in sync?

**Comment by FelixMalfait** [comment]
Maybe we can introduce https://danger.systems/js/ ? I feel like it's complementary to eslint linting and could save some work on PR Reviews ; they document a similar use-case: https://danger.systems/js/tutorials/node-library#keep-your-readme-up-to-date

**Comment by brendanlaschke** [comment]
This sounds like a great idea @FelixMalfait! 

The bot user & setup would need to be added by you but then I would be happy to write some rules ...

**Comment by charlesBochet** [comment]
Awaiting #2452 :)

**Comment by FelixMalfait** [comment]
It seems like the danger setup I did doesn't work with forks... I'll look into it

**Comment by FelixMalfait** [comment]
https://github.com/danger/danger-js/blob/263bcd287b6ad834ebf65b5e215c614ff0c5e06c/source/ci_source/providers/GitHubActions.ts#L160 > I thought this was strange and skipped this initially, but it seems we are forced to echo the token 🤔. Also I don't get the security benefit of splitting it in two.

See also: https://github.com/danger/danger-js/issues/1060#issuecomment-1500766636

Let's just echo the token then... I gave it the most limited permissions

**Comment by FelixMalfait** [comment]
@charlesBochet ok for you to merge? it should fix tests for other recently opened PRs.
I'm not very happy with the solution but I'm pretty sure it's the best we can do

**Pull request merged**
