### PR TITLE
4599-feat(front): Add Copy Button to Floating Inputs

### LINKED ISSUE #4599: Add Copy Button to Floating Input
# Current Behavior

There is no button or shortcut to copy the content of a field.

# Desired Behavior

Add a `copy` button to the floating inputs for `Text`, `Number`, `Phone`, `Link` and `Email` fields, enabling users to easily copy the input content.

CleanShot 2024-03-21 at 09 37 54

image

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3007-69739&mode=design&t=KLtBvS4nmd26fA0m-11

### PR DESCRIPTION
**Pull request by Anchit1909**
Closes #4599 

**Changes:**
- Added copy button to floating inputs of Text, Number, Phone, Link and Email fields.

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Also make sure to check it doesn't break any storybook test. Thank you!

**Comment by lucasbordeau** [comment]
- For text inputs it's not placed correctly : 
image

- For phone inputs, it should be wider : 
image

Reference : 
image

**Comment by lucasbordeau** [comment]
The icon should be smaller also

**Comment by Anchit1909** [comment]
Hey @lucasbordeau , I have made the required changes. Please check if its alright now.

**Review by FelixMalfait — APPROVED** [review]
Great work! It's not a big change but really improves the day-to-day experience! Thank you!

**Comment by FelixMalfait** [comment]
(Not merging because we need to fix Storybook)

**Comment by charlesBochet** [comment]
I'm taking a look at the stories

**Comment by Anchit1909** [comment]
Hey @charlesBochet,
Sorry for not completing this PR. I was unable to start frontend with my setup (Yarn Setup with WSL) after recent changes. I also discussed this problem with you in Discord Help section.

**Pull request merged**
