### PR TITLE
Removed drag grip and accent is now tertiary in hidden fields

### LINKED ISSUE #6115: Fix Disabled fields color in Fields Menus
# Current behavior

CleanShot 2024-07-03 at 17 41 36@2x

# Desired Behavior

CleanShot 2024-07-03 at 17 42 39@2x

Make sure it doesn't impact other menu items somewhere else

### PR DESCRIPTION
**Pull request by ehconitin**
Closes #6115

This change successfully addresses the issue as described. However, it also causes the primary non-draggable field, `Name`, to render without a draggable handle and with a secondary accent. Is this an acceptable outcome?

https://github.com/user-attachments/assets/4bc15e00-6c73-41d4-8342-4e36487d0981

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@Bonapara Should we add a left padding without any icon to align the primary non-draggable field with the rest ?

**Comment by lucasbordeau** [comment]
We want the same effect as today : 

image

**Comment by lucasbordeau** [comment]
+ Add a grab pointer on the draggable items instead of click.
+ Add a not allowed for the first undraggable item
+ Use a default on hidden fields but a pointer on the eye icon to make them visible.

**Comment by ehconitin** [comment]
@lucasbordeau 
recording is a bit laggy, machine is fried :(

https://github.com/user-attachments/assets/a9d441dd-d14c-4f59-8e97-f0b28bba64d5

**Comment by ehconitin** [comment]
@lucasbordeau what about this changes?
introduced cursor property. Or should it be handled in different manner?

**Review by lucasbordeau — APPROVED** [review]
We can improve a little bit but it works !

**Pull request merged**
