### PR TITLE
5425 - Introducing support for all Composite Fields Import

### PR DESCRIPTION
**Pull request by zaryanz**
Adding support for all Composite Fields while using the "import" functionality. This includes:
- Currency
- Address

Edit : 
- Refactored a lot of types in the spreadsheet import module
- Renamed a lot of functions, hooks and types that were not self-explanatory enough

### CODE REVIEW

**Comment by zaryanz** [comment]
@charlesBochet Hi! An observation while importing data using a spreadsheet:
1,000,000$ is being saved as 1$ after submitting and anything less than 1,000,000 is being saved as 0. Is this an existing issue that we are aware of or should we raise an issue for the same?
Screenshot 2024-05-20 at 3 43 59 PM
Screenshot 2024-05-20 at 3 43 23 PM

**Comment by FelixMalfait** [comment]
Thanks @zaryanz! yes it's a best practise to store amounts in "micros" when dealing with currencies since database tend to be flaky with floats - but that's a database stuff that shouldn't be exposed to non-technical users that try to import via csv, so it would be great if you could make sure to automatically convert it by multiplying by 10^6. Thanks!

**Comment by zaryanz** [comment]
Thanks @FelixMalfait for pointing that out! Silly of me to overlook the "micros" part. Could you also please point me to the different Composite Fields for "Address"? As I couldn't mind any information on that in the issue.

**Comment by FelixMalfait** [comment]
Sure! 

Linked issue: https://github.com/twentyhq/twenty/issues/5425

Address field: https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/address.composite-type.ts

**Review by charlesBochet — COMMENTED** [review]
Thanks a lot for the help! I have left comments on the PR

**Comment by zaryanz** [comment]
Thanks for the comments! I'll have a look and make the required changes

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
