### PR TITLE
Added GitHub init

### PR DESCRIPTION
**Pull request by ady-beraud**
- Added github:init to allow full import, as opposed to gitHub:sync which allows partial sync and therefore respecting Github API Limit quota.

### CODE REVIEW

**Comment by FelixMalfait** [comment]
I'm not sure I understand what you are doing, would you mind calling me on Discord to explain quickly? thansk!

**Comment by ady-beraud** [comment]
- Decreased number of PRs and Issues to fetch to 30.
- Added pageLimit flag to determine full vs partial sync

**Review by A1exKH — APPROVED** [review]
LGTM.

**Comment by FelixMalfait** [comment]
Sorry but I think some changes are still required.
I had in mind "page limit X" = only iterate over X pages. But you did "page limit" as in "max number of records per page", but there is no reason to correlate that with not iterating over pages, this is confusing 
Thanks!

**Comment by ady-beraud** [comment]
Ok, should be good now !

**Review by FelixMalfait — APPROVED** [review]
Not tested tbh but looks good now!

**Pull request merged**
