### PR TITLE
Showpage add more actions button

### LINKED ISSUE #2907: I should be able to delete a record from its show page
I should be able to delete a record from its show page, without having to find it in the list view .
Also, we will introduce other actions in the context menu (apps will be able to register custom action, but that could also be system actions). So we probably need to a be able to display a list of actions, not just delete.
Maybe it's just a "..." next to "+" and "♡" ? And for now we only show delete in it?

cc @Bonapara

### PR DESCRIPTION
**Pull request by brendanlaschke**
@FelixMalfait took a try implementing this if needed we can change the icon/layout ;) 

closes #2907

Bildschirmfoto 2023-12-21 um 00 02 06

### CODE REVIEW

**Comment by charlesBochet** [comment]
@Bonapara what do you think?

**Comment by FelixMalfait** [comment]
Oh cool! Thanks again @brendanlaschke!

**Comment by Bonapara** [comment]
Looks good!

**Review by charlesBochet — APPROVED** [review]
Thanks! Will be shipped as part as 0.2.2

**Pull request merged**
