### PR TITLE
fix: Phone dropdown field has extra width

### PR DESCRIPTION
**Pull request by harshit078**
## Description

This PR solves the issue #6865 

## Current Behaviour
Screenshot 2024-09-03 at 2 04 55 AM

## Expected behavior
Screenshot 2024-09-03 at 2 05 46 AM

### CODE REVIEW

**Comment by Bonapara** [comment]
Hi @harshit078, thanks for noticing this one! Can you make the picker as large as the input? 

I've create another issue to improve the detail page inputs style: https://github.com/twentyhq/twenty/issues/6870

**Comment by harshit078** [comment]
Sure @Bonapara , will do that

**Review by martmull — DISMISSED** [review]
Think it is not enough, we have the issue on currency picker also, the issue comes from https://github.com/twentyhq/twenty/pull/6166/files

**Comment by harshit078** [comment]
Hi @martmull, Is the ARR field currency picker that you are referring too ?

Screenshot 2024-09-05 at 2 56 26 PM

**Comment by martmull** [comment]
@harshit078 yes, the input is too large also

**Comment by harshit078** [comment]
Yes, This issue is already referenced under #6870 and I have already created an PR for this #6899.

**Comment by harshit078** [comment]
Since this issue comes under the existing #6870 hence it wouldn't require `max-width` component and only` width=auto` will work.

**Review by bosiraphael — APPROVED** [review]
LGTM, thank you @harshit078 for your contribution.

**Pull request merged**
