### PR TITLE
Update Attachment Table on RICH_TEXT Field Edits (#6565) 

### PR DESCRIPTION
**Pull request by yadavshubham01**
i implements a feature that ensures the attachment table is updated whenever new images are added to a RICH_TEXT field. This enhancement improves the data consistency and integrity of our application's file management system, ensuring that all relevant attachments are correctly linked to their respective entries.

Changes Made:
Image Handling Logic :-
Modified the existing functionality for handling image uploads within the RICH_TEXT field.
Implemented a mechanism to detect when new images are added to the RICH_TEXT content.
Attachment Table Update :-
Added a function that updates the attachment table with the details of newly added images.
Each image upload will now trigger an insert operation in the attachment table, including fields such as fileId, fileName, and fileUrl.
Integration with GraphQL :--
Updated the relevant GraphQL mutations to support the addition of attachments in conjunction with RICH_TEXT field edits.
Ensured proper error handling and logging for failed uploads or attachment inserts.

### CODE REVIEW

**Review by charlesBochet — COMMENTED** [review]
Interesting one, thanks for raising it @yadavshubham01 

Here are my thought on this one:
1) Product behavior: I agree it would be great to store uploaded files as attachments @Bonapara  @FelixMalfait what do you think of the product behavior
2) Eng strategy: we are doing it in two calls: uploadFile, then addAttachment. These two calls belong to the same atomic operations and I would prefer having only one uploadAttachment customResolver doing both. However, taking the look at useUploadAttachment (which is used on Files tab), I can see we are already doing two calls there so I guess we can keep doing it
3) Could we try to re-use useUploadAttachment logic instead?
4) In your PR I don't see the code for addAttachment custom resolver, but with 3 in mind I could prefer that we reuse useUploadAttachment which is doing createAttachment

Putting this on hold the time to get an answer from Product on this

**Comment by yadavshubham01** [comment]
Hey @charlesBochet ,
Thanks you for your feedback

**Comment by FelixMalfait** [comment]
@charlesBochet yes this is a product behavior, here's the related issue: https://github.com/twentyhq/twenty/issues/6565

**Comment by yadavshubham01** [comment]
hey @charlesBochet Is there anything wrong in this PR and i don't understand re-use of useUploadAttachment hook

**Comment by yadavshubham01** [comment]
hey @charlesBochet i just create new PR #7690 that re-use the useUploadAttachment hook in this case

**Comment by charlesBochet** [comment]
Ok, perfect, closing this one

**Pull request closed without merging**
