### PR TITLE
[Bug fix] Reference container name instead of localhost for postgres url in .env file

### PR DESCRIPTION
**Pull request by pmulard**
When trying to start up the dev environment per the docs, I ran into an issue with the database URL in the .env file; specifically when running the database migrations with,

`make server-prisma-reset`

I had the same issue, as described in [this discussion](https://github.com/prisma/prisma/issues/1385). [This comment](https://github.com/prisma/prisma/issues/1385#issuecomment-576695684) describes why the issue is happening (localhost inside docker is bound to the container, not the machine), and [this comment](https://github.com/prisma/prisma/issues/1385#issuecomment-664519367) details the fix, which I tested on my machine with success.

This PR is to change the .env.example file provided by the repo, for when it is copied into the .env file.

### CODE REVIEW

**Comment by pmulard** [comment]
I should have been more patient and thorough with the testing. Currently getting the following error when trying to start the server with `make server-start`:

```
/app/server/src/utils/assert.ts:22
    throw new Error(message);
          ^
Error: An instance of EnvironmentVariables has failed the validation:
 - property PG_DATABASE_URL has failed the following constraints: isUrl 

    at assert (/app/server/src/utils/assert.ts:22:11)
    at Object.validate (/app/server/src/integrations/environment/environment.validation.ts:105:9)
    at Function.forRoot (/app/server/node_modules/@nestjs/config/dist/config.module.js:67:45)
    at Object.<anonymous> (/app/server/src/integrations/environment/environment.module.ts:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
```

The changed URL is not passing internal testing with nest.js. Going to dig deeper...

**Comment by charlesBochet** [comment]
Thanks for your interest in the project!

@pmulard If you are using the docker installation, I think the postgres container has an internal dns called `postgres`.
So your database_url should be: 
`PG_DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/default?connection_limit=1`

We don't want to change the .env.example as we recommend using the yarn installation and not the docker installation. However, we should give the PG_DATABASE_URL in the documentation: https://docs.twenty.com/developer/local-setup#docker-install.

If this url works for you, could you update the doc instead?

**Review by charlesBochet — COMMENTED** [review]
See comment above!

**Comment by pmulard** [comment]
@charlesBochet No problem, happy to update the documentation. The .env.example file already contains the database URL, and the docs mention copying it to .env - Do you mean the database URL should be explicitly mentioned in the official docs? And with what context?

**Comment by pmulard** [comment]
@charlesBochet No problem, happy to help! The database URL you provided worked, so I'll go ahead and make a PR for the doc changes.

**Review by charlesBochet — APPROVED** [review]

**Pull request merged**
