### PR TITLE
fix local-setup docs. redis and docker compose version.

### PR DESCRIPTION
**Pull request by hozza**
plus some extra verbosity.

This may solve https://github.com/twentyhq/twenty/issues/7031 (thanks to Bob on Discord for pointing out!)

Note: I'm not able to build the docs website at the moment, please do check formatting locally before approval. I've not done a complete dry-run through of the instructions, rather updated from my notes from yesterday trial and error.

### CODE REVIEW

**Comment by hozza** [comment]
may be related to: https://github.com/twentyhq/twenty/pull/7369

**Comment by charlesBochet** [comment]
Thanks @hozza!

Indeed, this is solved into https://github.com/twentyhq/twenty/pull/7369

Could you update the PR to only keep the `#### Docker Compose version i.e. `unknown shorthand flag: 'f' in -f` error` section?

**Comment by BOHEUS** [comment]
You're welcome @hozza!

**Comment by charlesBochet** [comment]
Closing this one as there is no activity, feel free to re-open it if it makes sense :)

**Pull request closed without merging**
