### PR TITLE
fix : 7223 Clicking Outside Fields domain link email phone Close Them

### PR DESCRIPTION
**Pull request by prathameshpatil5181**
fixes #7223
https://github.com/user-attachments/assets/1150e96f-4fb5-40ba-ac17-89d8b2ab16e7

### CODE REVIEW

**Comment by prathameshpatil5181** [comment]
@Bonapara  could you please review this request??

**Comment by Bonapara** [comment]
LGTM from a product point of view! Thanks @prathameshpatil5181. Over to the tech team for their review.

**Comment by lucasbordeau** [comment]
@charlesBochet @Bonapara I'll review it as this behavior can be tricky and can easily cause regression.

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
