### PR TITLE
Fix: Enable Vertical Scrolling for Company Filter Dropdown

### LINKED ISSUE #8827: Vertical Scroll Missing in "Company" Filter Dropdown
## Bug Description
The filter dropdown for "**Company**" does not support vertical scrolling when the list of options exceeds the viewable area. This limits the ability to access options that are not immediately visible.

Image

## Expected behavior
The behavior should align with other dropdowns (e.g., The Filter dropdown itself) where vertical scrolling is supported.

### PR DESCRIPTION
**Pull request by mdrazak2001**
Fixes https://github.com/twentyhq/twenty/issues/8827

https://github.com/user-attachments/assets/b6bcb5ee-caf6-4f80-af1d-486c59c7f3a4

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@mdrazak2001 Could you please put the scroll wrapper so that we only have the menu item part scrollable ? 

Capture d’écran 2024-12-02 à 10 06 22

**Comment by Bonapara** [comment]
Is it a regression? Can't reproduce on V33.5

Uploading CleanShot 2024-12-02 at 10.22.38.mp4…

**Comment by mdrazak2001** [comment]
> Is it a regression? Can't reproduce on V33.5
> 
>  CleanShot.2024-12-02.at.10.22.38.mp4

@Bonapara 
Thanks for looking into this. I’m currently on the latest main branch, and the issue persists for me. 
Was this problem addressed in an upcoming release or an internal branch? 
If the issue is resolved in the latest version you’re testing on, I’d be happy to close this PR and the tagged Issue.
Thanks!

**Comment by Bonapara** [comment]
@lucasbordeau maybe you know?

**Comment by lucasbordeau** [comment]
Yes it's a regression, I can reproduce, I could take it in my PR because I'm currently fixing a lot of related regressions on dropdown.

Let's close this one, thank you for your understanding @mdrazak2001

**Pull request closed without merging**
