### PR TITLE
feat: improve menuitem btn design

### LINKED ISSUE #3098: Improved menu item button design
# Current Behavior

- Menu item's icon buttons look too large. 
- its background color in dark mode seems odd.

Screenshot 2023-12-21 at 10 00 07

# Desired Behavior

In menu items, replace "floating buttons" with tertiary "light icon buttons":

https://github.com/twentyhq/twenty/assets/19412894/f61314cb-968d-410c-9b20-e8839f2acb5e

Also, replace the "icon group buttons" with multiple "light icon buttons" placed side by side, with a 2px gap between them:

https://github.com/twentyhq/twenty/assets/19412894/fe8e5acb-a27d-4ac9-9589-f32b68f0e584

Make sure the gap between the text and buttons is 4px. The icon buttons should never be on top of the text as their background is transparent. 

CleanShot 2023-12-21 at 10 15 54

Update the revised Menu Item component:

Screenshot 2023-12-21 at 10 21 37

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2979-174004&mode=design&t=9XKex9M2nYivWERq-11

### Credits ;)

Thanks to @Kanav-Arora  🙌

Screenshot 2023-12-21 at 10 19 52

### PR DESCRIPTION
**Pull request by CzhCN0**
closes #3098

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@Bonapara How should we handle overflowing ? 

image

**Comment by CzhCN0** [comment]
> @Bonapara How should we handle overflowing ?
> 
> image

This is exactly the concern I expressed in the issue. We need a solution.

**Comment by Bonapara** [comment]
Is it possible to crop the text when the menu-item is hovered? Ideally, the text should span the full length by default, but be cropped during hover to avoid overlapping with buttons.

**Comment by CzhCN0** [comment]
> Is it possible to crop the text when the menu-item is hovered? Ideally, the text should span the full length by default, but be cropped during hover to avoid overlapping with buttons.

That sounds great! I'll try to implement this effect.

**Review by charlesBochet — APPROVED** [review]
Thank you!

**Pull request merged**
