### PR TITLE
[oss.gg] create-n8n-template

### PR DESCRIPTION
**Pull request by sateshcharan**
workflow screeshot:
image

working video:
https://drive.google.com/file/d/1D4-RbbXlz-tCrGYM1Bot3bLlzKSdjJ_k/view?usp=sharing

Hi,

I’ve completed the task of integrating TwentyCRM through n8n, but I’m having trouble uploading the [template ](https://drive.google.com/file/d/1PCp_i6y24aIoyhatWec-wz-MOzJbJoww/view?usp=sharing) due to an issue with my email account. I’ve already reached out to their support team for assistance. In the meantime, I kindly request that you consider this as a valid contribution for the challenge until the issue is resolved.

Thank you!

### CODE REVIEW

**Review by Bonapara — APPROVED** [review]

**Comment by Bonapara** [comment]
Hi @sateshcharan, I will award 150 points now, and an additional 150 points if it gets published!

**Comment by Bonapara** [comment]
Thanks for your contribution :)

**Comment by sateshcharan** [comment]
@Bonapara  for the 750-point contest, could we do 350 points now and the remaining 350 after publishing?

**Comment by Bonapara** [comment]
750 points is too much compared to similar coding features, let me have a closer look to your template when it will be published @sateshcharan! Thanks for contributing :)

**Comment by sateshcharan** [comment]
@Bonapara please find the published link below
[n8n link](https://n8n.io/workflows/2509-twentycrm-event-based-updates-on-selective-messaging-channels-with-logs/)

**Comment by Bonapara** [comment]
Thanks for letting me know @sateshcharan! Just awarded an extra 400 points ;)

**Pull request merged**
