### PR TITLE
Adding new one-click deploy option to 1-click-deploy.mdx

### PR DESCRIPTION
**Pull request by cosark**
This PR introduces a one-click deploy button for RepoCloud, enabling an easy and rapid deployment option for the community.

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey happy to merge this if it works but it does not work on our side

Screenshot 2024-03-08 at 13 43 48

**Comment by cosark** [comment]
Thanks for bringing that to my attention. It's now been fixed!

**Review by FelixMalfait — APPROVED** [review]

**Comment by cosark** [comment]
Should this be appearing at https://docs.twenty.com/start/self-hosting/click-deploy ?

**Comment by FelixMalfait** [comment]
@cosark just triggered a deploy, should be there soon

**Pull request merged**
