### PR TITLE
Record horizontal scrolling mobile

### LINKED ISSUE #5745: Disable Horizontal Scrolling on Mobile Record Page
# Current Behavior

There is an unwanted ability to horizontally scroll the record page on mobile.

https://github.com/twentyhq/twenty/assets/19412894/a6445078-1fef-4351-863d-020a7aa0b06e

# Desired Behavior

The width should be set to 100vw, and no horizontal scrolling should be possible. Only the tab bar should scroll horizontally.

### PR DESCRIPTION
**Pull request by RobertoSimonini1**
I have fixed the scrolling the record container page on mobile making it hidden.
This PR aims to fix #5745

### CODE REVIEW

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
Hi @RobertoSimonini1 thanks for your contribution,

The root problem was that one component was too large, I dug up to find it and remove the excess width. 

Also the RecordInlineCell components were overflowing for no reason, they had to use width: 100% instead.

The first solution was only hiding this root problem.

**Comment by RobertoSimonini1** [comment]
@lucasbordeau oh ok, thanks a lot for the feedback, I appreciate a lot!

**Comment by martmull** [comment]
@RobertoSimonini1 @lucasbordeau that pr reintroduced the fix on notes overflow :(
https://github.com/twentyhq/twenty/pull/5853

**Comment by martmull** [comment]
@RobertoSimonini1 @lucasbordeau that pr reintroduced the bug on notes overflow :(
https://github.com/twentyhq/twenty/pull/5853

**Pull request merged**
