### PR TITLE
[oss.gg]: hubspot to twenty company data migration script (750 points) (migration-script)

### PR DESCRIPTION
**Pull request by FaheemOnHub**
HubSpot to Twenty CRM Company-Data Migration Script

Script's github repo: https://github.com/FaheemOnHub/twentycrm-hubspot-companyscript

This Node.js script allows you to migrate company or account data from HubSpot CRM to Twenty CRM. It fetches company data from HubSpot using its API, maps it into the required format, and posts it to Twenty CRM in batch. This can help you seamlessly transfer company data while ensuring the necessary fields are properly mapped.

Video Proof added in oss-gg's twenty-dev-challenges

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Thanks @FaheemOnHub! It seems this has already been reward here https://github.com/twentyhq/twenty/pull/7937

**Comment by FaheemOnHub** [comment]
@FelixMalfait Previous script was for contact data transfer from hubspot , this one is transfer data company data from hubspot, It is a different script

**Comment by FelixMalfait** [comment]
@FaheemOnHub thanks! but 750 points is for a fully functional script (should even include deals, etc)

**Comment by FaheemOnHub** [comment]
@FelixMalfait So if I write a script with different crm like Saleforce , will that be counted or not ?

**Pull request closed without merging**
