### PR TITLE
Custom object import csv

### LINKED ISSUE #3247: Add CSV import for any object
## What we want
We had previously built a feature to import a CSV or spreadsheet of companies/people directly into Twenty.
This feature is live and works well, but since then we have moved to a generic framework where object names and properties are abstracted and driven by the backend. Users can now create any type of object. 

The CSV import feature was not refactored does not rely on the new metadata framework. 
Therefore it's not possible to import a custom field via the csv import. Or to enable the import feature on custom objects.

See:
- https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/companies/hooks/useSpreadsheetCompanyImport.ts
- https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/people/hooks/useSpreadsheetPersonImport.ts

We need to abstract these two files on a single generic hook that takes the object name as parameter, and map the according fields (probably retrieved though `useObjectMetadataItem` - tbc).

## Screenshots
This is the current state of the product.
Nothing would really change from a UI perspective even though this is a frontend ticket. 
But we need to have the "options > import" button on every object, including custom objects.
And during field mapping we will now see every custom field, not just the standard pre-created fields .

Screenshot 2024-01-05 at 09 41 01
Screenshot 2024-01-05 at 09 40 56

### PR DESCRIPTION
**Pull request by brendanlaschke**
Adds the csv import for all objects.

closes #3247

### CODE REVIEW

**Comment by FelixMalfait** [comment]
I don't think you missed anything important, this is the same direction I had in mind!

One challenge will be to handle creating relationships by passing an Id but we can do that in another issue/PR!
(Often people that are migrating have an existing list of people/companies so the workflow would probably be (1) import companies in Twenty (2) Export companies from Twenty to get the ID (3) attach the ID in my google sheet list of people with a vlookup (4) Import people)

**Comment by brendanlaschke** [comment]
> I don't think you missed anything important, this is the same direction I had in mind!
> 
> One challenge will be to handle creating relationships by passing an Id but we can do that in another issue/PR! (Often people that are migrating have an existing list of people/companies so the workflow would probably be (1) import companies in Twenty (2) Export companies from Twenty to get the ID (3) attach the ID in my google sheet list of people with a vlookup (4) Import people)

I think this shouldn't be a problem ... Do we validate these relation ids before the graphql insert ?

**Comment by brendanlaschke** [comment]
Im a bit confused figuring out the problem with the test - shouldn't the mocked response be matched? They seem to be the same ?

```
 Expected variables: 
{"data":[{"address":<undefined>,"annualRecurringRevenue":{"amountMicros":null,"currencyCode":"USD"},"domainName":"example.com","employees":null,"idealCustomerProfile":true,"linkedinLink":{"label":"linkedinLink","url":null},"name":"Example Company","xLink":{"label":"xLink","url":null},"id":"cb2e9f4b-20c3-4759-9315-4ffeecfaf71a"}]}
    
    Failed to match 1 mock for this query. The mocked response had the following variables:
{"data":[{"address":<undefined>,"annualRecurringRevenue":{"amountMicros":null,"currencyCode":"USD"},"domainName":"example.com","employees":null,"idealCustomerProfile":true,"linkedinLink":{"label":"linkedinLink","url":null},"name":"Example Company","xLink":{"label":"xLink","url":null},"id":"cb2e9f4b-20c3-4759-9315-4ffeecfaf71a"}]}
    
    This typically indicates a configuration error in your mocks setup, usually due to a typo or mismatched variable.
```

**Comment by brendanlaschke** [comment]
Apparently it was the undefined - thanks :)

**Comment by FelixMalfait** [comment]
Great! I tested it and it works well!
Small feedbacks:

1) non-blocking error
Screenshot 2024-02-06 at 09 11 22

2) for composite field would probably be best to be consistent with other field types and not send them at all if they're empty
Screenshot 2024-02-06 at 09 14 55

3) I agree with "TODO validate Relation Ids?", I don't think we should do a check on the object itself (server) but we could at least validate it's in a uuid format? 

4) We should only show the relationship where we have a foreign key on the target import table. So for example on the person table we should have companyId, but we should not have Attachments, Activities, Favorites... Because an activity `belongsTo` a company and we only want to import the object a company `has` in my opinion

**Comment by brendanlaschke** [comment]
Should be fixed!

**Review by FelixMalfait — APPROVED** [review]
Perfect! Tested again and it works (including creating the relationship)
Thanks a lot!!!

**Review by lucasbordeau — APPROVED** [review]

**Comment by brendanlaschke** [comment]
@quest-bot loot #3247

**Pull request merged**
