### PR TITLE
Edit opacity from 0.8 to 0.5 and remove forBackdropFilter

### PR DESCRIPTION
**Pull request by jss475**
Update for #4836 

- edit primary and secondary transparency opacities from 0.8 to 0.5
- remove forBackdropFilter from themes
- update components referencing transparency/primary and transparency/secondary to have the following backdrop-filter: blur(12px) saturate(200%) contrast(50%) brightness(130%)

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Thanks a lot @jss475!
Your PR looks great. But I think we need to fix dark mode, it becomes even more obvious now with the changes you made 

@Bonapara can you confirm adjustments we should make to dark mode? 

After:
Screenshot 2024-05-04 at 15 47 45
Screenshot 2024-05-04 at 15 48 59
Screenshot 2024-05-04 at 15 51 04

Before:
Screenshot 2024-05-04 at 15 48 17
Screenshot 2024-05-04 at 15 49 25

**Comment by Bonapara** [comment]
Dark mode should look like this:

CleanShot 2024-05-06 at 10 45 55

To do:
- Remove the hardcoded background on search inputs that makes it look darker (Set background: transparent).
- Remove the border-top on the input when It's at the top of the menu:

CleanShot 2024-05-06 at 10 48 44

- Make the input 36px instead of 38px+ (with the border)

**Current behavior ↓**

CleanShot 2024-05-06 at 10 54 12

**Comment by FelixMalfait** [comment]
Would you mind handling those changes in the PR @jss475 🙏? Thanks a lot

**Comment by jss475** [comment]
Yup you got it @FelixMalfait!

**Comment by Bonapara** [comment]
Hi @jss475,

I think `background:transparent` should be in both light and dark mode.
Also, can you check if we need to add a border-bottom to the menu header if you remove the border-top on the search?

CleanShot 2024-05-07 at 10 01 49

Regarding the padding, it should be 8px left and right, and the height should be fixed to 36px:

You can inspect this component:

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2979-174004&mode=design&t=XnegKqWtGbRaLmeE-11

Thanks!

**Comment by jss475** [comment]
Hey @Bonapara!

You got it! I had to add a bottom-border for the menu header. I've updated it with the latest commit.

Thanks!

**Review by FelixMalfait — APPROVED** [review]
Thanks a lot!

**Pull request merged**
