### PR TITLE
Fix(view): Show Kanban View Creation

### PR DESCRIPTION
**Pull request by Us3r-gitHub**
# This PR
- Revise my previous work (PR #5969)
Because it would break the current logic and cause unexpected behavior. (Issue #5979)
- Solve (Issue #5915) with another way

@lucasbordeau  What do you think about my current approach?
@JarWarren Please check it out—I'd love to get your feedback too!

### CODE REVIEW

**Comment by JarWarren** [comment]
Nice job! I ran it locally and tested it on `People` and `Companies`. I also tried it on two `Custom` objects. It worked perfectly in all 4 cases. Prior to this, I'd been able to repro 100% as outlined in #5915.

As far as feedback and suggestions, hopefully one of the maintainers can give it a more official review haha

**Comment by Us3r-gitHub** [comment]
Thank you, I'm just worried if side effects appear and cause new problems like before

**Comment by lucasbordeau** [comment]
LGTM !

**Review by lucasbordeau — APPROVED** [review]

**Comment by Us3r-gitHub** [comment]
> LGTM !

Thank you

Can we close this issue #5979?

**Pull request merged**
