### PR TITLE
Remove step 1 of new object field

### LINKED ISSUE #6967: Empty screen when creating new field
# Bug description

In the Data Model Settings - When a field is deactivated, clicking on "Add field" produces an empty page. The user has to reload the page to see the content.

https://github.com/user-attachments/assets/fa2364f1-d395-4003-8b70-1c0188b21ec6

### LINKED ISSUE #7102: The settings flash during loading
# Current behavior

The Settings page flashes on load.

https://github.com/user-attachments/assets/6cdbe08c-79ff-44f5-b211-c5297298154c

# Desired Behavior

The White background layout should always be loaded and not flash on every page change. We should put a small Skeleton to indicate the page loading. The breadcrumb should not be part of the loading and already displayed (if possible).

image

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40069-430620&node-type=frame&t=vjg6Ofev4bkaijG1-11

# Techical guidelines

@lucasbordeau

### LINKED ISSUE #7121: Fix Incorrect Step Display When Creating New Field
# Current behavior

When creating a new field, we display `Step-2` on the page to select the field type.

image

# Desired Behavior

We should remove `step-2` and only keep `new-field`

### LINKED ISSUE #7356: Settings cards should use `<a> `instead of `<div>`
# Current Behavior

The field type Settings cards use a `div` container.

CleanShot 2024-09-30 at 17 07 51

This concerns the `field type` settings cards, but not the `emails` and `calendar` settings cards in Accounts (which use an `<a>` tag), even though they share the same component.

c3713d6712bf11aee76f412aa0c7a7f4924c38eb2e06284424cb4ed830438ba7

# Desired Behavior

They should use an `<a></a>` container for accessibility. Design and behavior should remain the same.

# Figma

image

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=35741-193252&node-type=frame&t=YZppWDu8cDmzxDmJ-11

### LINKED ISSUE #7505: New Kanban View -> Redirect to new-field step 2
# Current behavior

When creating a `kanban` view on an object that doesn't have any `Select` field, I'm redirected to the Settings. This redirection goes to `https://app-main.twenty.com/settings/objects/OBJECT/new-field/step-2?fieldType=SELECT` but step-1 is displayed.

CleanShot 2024-10-08 at 16 34 30

https://github.com/user-attachments/assets/2ad55907-2b2d-4cdd-baed-56e8b785aa06

# Desired Behavior

Show step 2 with the "Select" field type pre-selected.

### PR DESCRIPTION
**Pull request by ehconitin**
fixes #7356 
fixes #6967 
fixes #7102
fixes #7121 
fixes #7505

### CODE REVIEW

**Comment by ehconitin** [comment]
@Bonapara removed all the redundant icons code beside breadcrumb! Those Icons are removed right?

**Comment by Bonapara** [comment]
> @Bonapara removed all the redundant icons code beside breadcrumb! Those Icons are removed right?

Thanks Nitin! Do you have a screenshot so I can better understand what you mean?

**Comment by ehconitin** [comment]
> > @Bonapara removed all the redundant icons code beside breadcrumb! Those Icons are removed right?
> 
> Thanks Nitin! Do you have a screenshot so I can better understand what you mean?

Untitled design (3)

There used to be icons here right? and they are now removed I think, because I cant see them even in Figma.
But the code related to it was not cleaned. Just making sure I should clean it or not!

**Comment by Bonapara** [comment]
Yes you can clean it! Thanks @ehconitin

**Comment by FelixMalfait** [comment]
Thank you! This works but I feel we could do even better :)

When you open links in a new tab, it's not working because you created fake links `to = #`
Instead we should probably link `to={`?fieldType=${key}`}`
We should also be able to use the backed button (remove replace: true)

And that will be an issue because if you press the back button, configureStep remains with its previous value.
So I would advocate for a bigger refactoring, either keep the current code and drop `isConfigureStep` to just base it on whether the field type parameter has been provided in the url, or just split into two pages.

Do you see what I mean @ehconitin?

**Comment by ehconitin** [comment]
Yes!
Refactoring it to two separate pages would be much cleaner!
I am dropping isConfigureStep state, its very restrictive. 
Couldnt do to={?fieldtype=${key}} because since its the same page, had to add a useEffect to keep listening for url changes, so opted for a onClick navigation, which is kind of a cheap trick.
Will refactor!
Thanks :)

**Comment by ehconitin** [comment]
@FelixMalfait conflicts made this way more tricky! :(
Refactor is done! Please let me know if I have missed anything.

**Comment by ehconitin** [comment]
sb-test failed, checking!

**Comment by ehconitin** [comment]
Ready for review!

**Comment by Bonapara** [comment]
I just checked from a product perspective, and it looks good! Thanks for the great work, @ehconitin.

**Review by FelixMalfait — APPROVED** [review]
Great work! I think we should merge this as the PR is already big! 
One potential improvements would have been to disable the configure step if no fieldType is passed instead of defaulting to text which can sometimes create weird behavior (e.g. you're on step 2 you come back to step 1 via top bar to check what was selected then come back to step 2 via top bar - your field type has changed). Not a big deal / TBC once we have experience with users!

**Comment by ehconitin** [comment]
@FelixMalfait 
Ah, I missed that one!
It was already done in #6969 but we scrapped it because it keyboard navigation was not required anymore.
I forgot to address it here.
I will address this in some minor fix PR soon!

Thanks!

**Pull request merged**
