### PR TITLE
Add S3 endpoint env variable

### PR DESCRIPTION
**Pull request by brendanlaschke**
This should enable the usage of google storage in the s3 driver by setting region to `auto` and the endpoint to `https://storage.googleapis.com` (#1969)

@joshuajung is this working for you ?

### CODE REVIEW

**Comment by charlesBochet** [comment]
Interesting, looks to be the right solution based on https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html

Let's wait for @joshuajung confirmation

**Review by charlesBochet — APPROVED** [review]

**Comment by charlesBochet** [comment]
I've tested and it seems to work :)

**Comment by joshuajung** [comment]
Thanks a lot for the quick response! I'll make certain to try this on our production setup once I'm back in the office, but I'm sure it will work.

**Comment by joshuajung** [comment]
Hi all, thanks again for your support on this. I installed v0.1.5 on our production server today and set the new configuration variables as I think they are correct:

```
STORAGE_S3_ENDPOINT=storage.googleapis.com
STORAGE_S3_REGION=europe-west3
STORAGE_S3_NAME=twenty
```

The upload request now no longer results in a server log (see #1969 for what happened before), but I get a `An error occured while uploading the picture.` message in the client.

The respective HTTP request looks like this:

Request:
```
------WebKitFormBoundary8nmkAWpSYkvNFb5D
Content-Disposition: form-data; name="operations"

{"operationName":"UploadProfilePicture","variables":{"file":null},"query":"mutation UploadProfilePicture($file: Upload!) {\n  uploadProfilePicture(file: $file)\n}"}
------WebKitFormBoundary8nmkAWpSYkvNFb5D
Content-Disposition: form-data; name="map"

{"1":["variables.file"]}
------WebKitFormBoundary8nmkAWpSYkvNFb5D
Content-Disposition: form-data; name="1"; filename="Weiß.png"
Content-Type: image/png


------WebKitFormBoundary8nmkAWpSYkvNFb5D--
```

Response:
```
{
    "errors": [
        {
            "message": "Invalid URL",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "uploadProfilePicture"
            ]
        }
    ],
    "data": null
}
```

The bucket remains empty. Do you have an idea what I'm doing wrong here?

**Comment by charlesBochet** [comment]
@joshuajung I am not sure, I don't have a proper GCP setup. I can have a look but not before next week :( Maybe someone else can take a look in the meantime. Could you create an issue regarding that?

**Comment by joshuajung** [comment]
Thanks @charlesBochet , I have opened #2235. If there is anything that I can try, happy to help, but I may be a bit slow to answer. No rush from my side either!

**Pull request merged**
