### PR TITLE
Added "Add record" button in kanban view column headers dropdown

### LINKED ISSUE #4629: In the opportunities kanban, put the new button at the top of the page, not the bottom
In the opportunities kanban, put the new button at the top of the page, not the bottom.
Otherwise, it forces to scroll all the way down as soon as you have more than a few oppties

### PR DESCRIPTION
**Pull request by ehconitin**
Closes #4629 
Refactored `RecordBoardColumnNewOpportunityButton` and `RecordBoardColumnNewButton` to use the same logic in dropdown.

I kept those hooks inside `record-board-column` where these buttons are. Let me know if it should be placed somewhere else.

Also Added navigation state preservation when clicked on `edit from settings`

Thanks :)

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Asking @Bonapara for design validation, please hold on a bit.

**Comment by lucasbordeau** [comment]
@ehconitin What we want : 
- Add a "+" button next to the option button
- The card should be created at the top of the list (see with position field)

**Comment by lucasbordeau** [comment]
https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=25496-303506

**Comment by ehconitin** [comment]
https://github.com/user-attachments/assets/ff344dcf-6297-4b19-8f11-eee011908a66

**Comment by Bonapara** [comment]
Amazing, thanks Nitin!!

**Comment by ehconitin** [comment]
@lucasbordeau could you review this pr?
Thanks

**Review by lucasbordeau — APPROVED** [review]
Well done.

**Pull request merged**
