### PR TITLE
Update custom object placeholder

### LINKED ISSUE #3874: Update Custom Object Placeholder
# Current behavior

When creating a new object, the placeholder is set to "Investor / Investors". We don't want to push people to use custom objects to store people
# Desired Behavior

Change the placeholder to "Listing" "Listings" with TbListNumbers as icon

### PR DESCRIPTION
**Pull request by jeet1desai**
Fix: #3874 

image

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Thanks! Searching "Investors" I came across
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/settings/data-model/object-edit/SettingsObjectIconSection.tsx#L26 is this still used anywhere? 
Maybe we should remove the folder that contains it if not? Does that break anything?

**Comment by jeet1desai** [comment]
Hello @FelixMalfait,

I noticed that the "object-edit" folder is not being utilized anywhere, so I've gone ahead and removed it. I've thoroughly checked to ensure that its removal doesn't cause any disruptions and it does not.

If you agree, I can proceed with removing the folder and updating this pull request accordingly.

**Comment by FelixMalfait** [comment]
Yes good for me! Someone else in our team will still review the PR just to make sure we triple check. Thanks

**Review by charlesBochet — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
