### PR TITLE
Fix board column title edit optimistic rendering #1745

### PR DESCRIPTION
**Pull request by Davidkramer1999**
Found as well that the color didn't update...

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
Good point! Thank you!

**Comment by charlesBochet** [comment]
> Hub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please

@Davidkramer1999 could you sign the Contributor License Agreement before merging this one? You might have to make sure that your github email address it the one configured in your local gitconfig

**Comment by Davidkramer1999** [comment]
Yes I already signed Contributor License Agreement second time becuse this is already my second issue. I will check my  github settings as well

**Comment by charlesBochet** [comment]
Ok, merging it! Thanks!

**Pull request merged**
