### PR TITLE
chore(backend): convert all standard prisma models into TypeORM entities

### LINKED ISSUE #1830: chore: convert all standard prisma models into TypeORM entities
## Scope & Context

Scope and context are explained in this main [ticket #1824](https://github.com/twentyhq/twenty/issues/1824)
You must use [nestjs-query](https://tripss.github.io/nestjs-query/), example can be found [here](https://github.com/twentyhq/twenty/tree/main/server/src/metadata/object-metadata).

## Current behavior

Prisma ORM is used for the standards models.

## Expected behavior

Based on the work that has been done on #1828 and #1829
We should now be able to convert all the other models:
`WorkspaceMember`, `UserSettings`, `Workspace`.

## Technical inputs

- Create all the standards entities
- Use [nestjs-query](https://tripss.github.io/nestjs-query/) to generate the services and resolvers
- Test if everything work properly and if we have somme difference between Prisma and TypeORM results

### PR DESCRIPTION
**Pull request by gitstart-twenty**
Fixes #1830

### CODE REVIEW

**Comment by charlesBochet** [comment]
@gitstart-twenty I think there is a miscommunication on this one, we should not migrate all entities into typeORM as most of them will actually be "standard-object" and part of the flexible schema (they are describe as metadata but not hard coded in the code).

We only want to migrate entities that are not within a workspace:
Workspace, Refresh Tokens, Users.

Regarding workspace member, don't migrate it either

**Comment by gitstart-twenty** [comment]
Hey @charlesBochet,
`workspace` has relations with most of these other models. How do we handle that?

**Comment by charlesBochet** [comment]
@gitstart-twenty Don't care about these relations for now :)

**Comment by gitstart-twenty** [comment]
> @gitstart-twenty Don't care about these relations for now :)

Hey @charlesBochet 
So we should also ignore methods like `createDefaultWorkspace` and `deleteWorkspace` because these too require the other entities to be present? This means we just leave the auto-generated resolvers and that's it.

**Comment by gitstart-twenty** [comment]
> @gitstart-twenty I think there is a miscommunication on this one, we should not migrate all entities into typeORM as most of them will actually be "standard-object" and part of the flexible schema (they are describe as metadata but not hard coded in the code).

Does the design intend for the user to engage with a single GraphQL endpoint that consolidates the metadata schema and this particular schema, thereby making all related functionalities accessible from one place?

**Comment by charlesBochet** [comment]
Yes! Exactly :)
I'm working on merging your other PRs regarding the "standard-objects"

**Comment by gitstart-twenty** [comment]
> Yes! Exactly :) I'm working on merging your other PRs regarding the "standard-objects"

Sounds cool (Still curious how the resolvers that TypeORM would have generated from the entities are going to be generated from the metadata though, here to learn).

**Comment by gitstart-twenty** [comment]
> > @gitstart-twenty Don't care about these relations for now :)
> 
> Hey @charlesBochet So we should also ignore methods like `createDefaultWorkspace` and `deleteWorkspace` because these too require the other entities to be present? This means we just leave the auto-generated resolvers and that's it.

Hey @charlesBochet,
I'm I correct here?

**Comment by charlesBochet** [comment]
@gitstart-twenty I'm closing this PR, the scope was unclear and we have ended up doing it differently. You can mark this as completed on gitstart side but I will close the PR

**Pull request closed without merging**
