### PR TITLE
Fix: shadow in relation picker

### LINKED ISSUE #1855: Bug: shadow in relation picker
## Bug Description

Relation picker shadow relation when opening dropdown:

Bildschirmfoto 2023-10-03 um 23 50 12

## Technical inputs

It seems like its the transparent background that produces this effect?

### PR DESCRIPTION
**Pull request by dev-DTECH**
Fixed #1855

### CODE REVIEW

**Review by thaisguigon — COMMENTED** [review]
Hi @dev-DTECH, thank you for contributing!

It seems that the issue is not the background color's transparency, but rather a bug in Chrome when applying a blurred background on nested elements.

Here `TableCellEditMode` uses the `overlayBackground` style, which contains: `backdrop-filter: blur(8px);`.
The dropdown menu where the bug occurs is a descendant of `TableCellEditMode`, this is why the `backdrop-filter: blur(20px);` property is not working on Chrome.

Not sure if we can easily disable the blurred background when the cell contains a dropdown, or if we want to disable the blurred background for all `TableCellEditMode`.

Any thoughts on this @charlesBochet ?

**Comment by Bonapara** [comment]
Looks like the bug identified by SID

**Comment by charlesBochet** [comment]
@dev-DTECH @thaisguigon I'm currently working on a broader fix for this issue. I'll keep you posted tonight

**Comment by charlesBochet** [comment]
@dev-DTECH Thanks a lot for your PR :)

We have been thinking about it internally and we think that that the blur / background should be handled by the FieldInput and not the TableCell (which is causing a double blur in case of the relation picker: one on TableCell + one on RelationPicker, leading to the bug we see).
I've merged the following PR: #2078 

Thanks again for your help, it is very much appreciated, I'll close this PR

**Pull request closed without merging**
