### PR TITLE
Fix broken billing portal when subscription canceled

### PR DESCRIPTION
**Pull request by martmull**
Fix billing portal link for canceled subscription

### CODE REVIEW

**Review by Weiko — APPROVED** [review]
LGTM

**Comment by B4itsG** [comment]
profile/README.md

**Review by B4itsG — COMMENTED** [review]
profile/README.md

**Review by B4itsG — COMMENTED** [review]
profile/README.md

**Review by B4itsG — COMMENTED** [review]
packages/twenty-front/src/pages/settings/SettingsBilling.tsx

**Review by B4itsG — COMMENTED** [review]
packages/twenty-front/src/pages/settings/SettingsBilling.tsx

**Review by B4itsG — COMMENTED** [review]
packages/twenty-front/src/pages/settings/SettingsBilling.tsx

**Review by B4itsG — COMMENTED** [review]
https://github.com/twentyhq/twenty/pull/5082/files

**Review by B4itsG — COMMENTED** [review]
https://github.com/twentyhq/twenty/pull/5082/files

**Review by B4itsG — COMMENTED** [review]
https://github.com/twentyhq/twenty/pull/5082/files

**Review by B4itsG — COMMENTED** [review]
https://github.com/twentyhq/twenty/pull/5082/files

**Review by B4itsG — COMMENTED** [review]
https://github.com/twentyhq/twenty/pull/5082/files

**Review by B4itsG — COMMENTED** [review]
https://github.com/twentyhq/twenty/pull/5082/files

**Review by B4itsG — COMMENTED** [review]
https://github.com/twentyhq/twenty/pull/5082/files

**Review by B4itsG — COMMENTED** [review]
🤷🏾‍♂️🤷🏾‍♂️🤷🏾‍♂️

**Review by B4itsG — COMMENTED** [review]
Mghfdd  I JJ

**Review by B4itsG — COMMENTED** [review]
🪄🥲🦍🦍

**Review by B4itsG — COMMENTED** [review]
🦍🦍🦍✨✨👑👑✨✨✨✨

**Comment by B4itsG** [comment]
🦍🦍🦍🦍

**Pull request merged**
