### PR TITLE
fix: Deactivate & Activate icons should be swapped UI improvements

### PR DESCRIPTION
**Pull request by harshit078**
## Fix

This fixes the minor UI issue #6795 in which it addressed the following two problems- 

1. Fixed the Icon switch
2. Updated the Delete Modal

## Screenshots

Screenshot 2024-08-30 at 1 38 31 AM

Screenshot 2024-08-30 at 1 39 13 AM

Screenshot 2024-08-30 at 1 39 23 AM

### CODE REVIEW

**Comment by FelixMalfait** [comment]
I think the icon for archive/unarchive was the right one :)

Good for the button, we can remove the StyledConfirmationButton if it isn't used anywhere anymore. Thanks!

**Comment by lucasbordeau** [comment]
@Bonapara Should we switch the icons ?

**Comment by FelixMalfait** [comment]
@lucasbordeau no we shouldn't. But we can merge the button change if we revert the change on icons

**Review by charlesBochet — APPROVED** [review]
LGTM, thank you @harshit078

**Pull request merged**
