### PR TITLE
Fix: design improvement for release page

### PR DESCRIPTION
**Pull request by selango1**
updated StyledRelease and StyledDate

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hi @selango1 thannks for the contrib! Could you instead do 1 pull request / issue and mention the issue you're addressing in the pull request description? Thanks a lot!

**Comment by selango1** [comment]
I have added the PR to patch-11, already. I am able to see the changes there

**Comment by magrinj** [comment]
Hello @selango1, by doing one PR @FelixMalfait ment squash the following PR together #4275 #4276 #4277 and add a link in the description on the issue you're fixing :) 
Thanks for your contrib !

**Comment by charlesBochet** [comment]
@selango1 Do you need help on this one?

**Review by FelixMalfait — APPROVED** [review]

**Pull request merged**
