### PR TITLE
Fix design EditableCell 'Hover', 'Focus' and 'Edit Mode' #1663

### PR DESCRIPTION
**Pull request by Davidkramer1999**
image
image

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Nice approach, we still have the top and bottom border of the td visible : 
image

**Comment by Davidkramer1999** [comment]
I think changing from shadow to border will do the job

**Comment by lucasbordeau** [comment]
Ok nice and simple solution.

I did a few tests : 
- we have a glitch when the cell enters/exits soft focus mode, it moves the content inside
- the edit mode container is overflowing from 1 px left and right (but ok top and bottom)

https://github.com/twentyhq/twenty/assets/26528466/ca6afe02-845f-4725-a32c-a707216bc00e

**Review by lucasbordeau — APPROVED** [review]
Nice work

**Pull request merged**
