### PR TITLE
Fixed: Drag and Drop Causes Flashing and Disappearing Cards

### LINKED ISSUE #6001: Drag and Drop Causes Flashing and Disappearing Cards
# Current Behavior

1. I grab the "Twitch" card.
CleanShot 2024-06-24 at 15 35 31

2. I drag the card between "VMware" and "HP." The "Twitch" card disappears from the right column.
CleanShot 2024-06-24 at 15 33 50

3. When I release the click, the card is added to the left column but is displayed again in the right column.
CleanShot 2024-06-24 at 15 37 42

4. The card disappears from the left column, even though we want to drag it there.
CleanShot 2024-06-24 at 15 38 58

5. The card disappears from the right column and finally appears in the left column.
CleanShot 2024-06-24 at 15 40 03

### Full Behavior in Video:

https://github.com/twentyhq/twenty/assets/19412894/d2068f3e-9e5e-4de1-a8c7-42c1ddcda7d7

# Desired Behavior

Prevent any flashing when dragging and dropping a card to another column.

### PR DESCRIPTION
**Pull request by rksingh2001**
Issue was "inView" was setting false due to root being scrollWrapper, instead changed it to viewport.
Fixes: #6001 
[Screencast from 2024-06-27 22-50-59.webm](https://github.com/twentyhq/twenty/assets/59247136/408d5fb5-91ab-4d3a-881d-bbcaf4817a79)

### CODE REVIEW

**Review by charlesBochet — COMMENTED** [review]
Hi @rksingh2001, thanks for your PR :) I'm not sure about this fix. I would expect an optimistic rendering issue (there is a concurrency issue between the queries behind each column / the cache is not properly updated).

Let's have a closer look to your fix tomorrow

**Comment by rksingh2001** [comment]
> Hi @rksingh2001, thanks for your PR :) I'm not sure about this fix. I would expect an optimistic rendering issue (there is a concurrency issue between the queries behind each column / the cache is not properly updated).
> 
> Let's have a closer look to your fix tomorrow

Sure, @charlesBochet, its still optimistic rendering, its just that the root is now viewport. Although I don't full understand this point -> (there is a concurrency issue between the queries behind each column / the cache is not properly updated).

**Comment by lucasbordeau** [comment]
Hi @rksingh2001, could you please look into the logic that updates a board card position in DB, because the problem is that now that we have one Apollo request per column, there's something that is not working with optimistic rendering in Apollo cache.

Here it shouldn't take so long to update a board card and should be instantaneous.

Also we shouldn't try to fix the content of the card disappearing in this issue as it is not our concern here.

**Comment by rksingh2001** [comment]
@lucasbordeau "there's something that is not working with optimistic rendering in Apollo cache", can you be a little more specific on what exactly is not working, so I understand better.

"Also we shouldn't try to fix the content of the card disappearing in this issue as it is not our concern here." <- I don't understand this part, do we not need to fix #6001? Because then there is no need of this PR.

**Comment by rksingh2001** [comment]
I think the label is wrong, I have responded

**Review by lucasbordeau — APPROVED** [review]
@charlesBochet @rksingh2001 This was a tricky bug due to a refetch caused by DELETE directive from Apollo.

I removed the handling of limit (first and last) in the optimistic rendering because it's not required to have an already working optimistic effect in a list, and we can rely on the fetch many return to overwrite incorrect optimistic effect results.

I think my big TODO comment was relevant before the many refactors to have optimistic effect working with fetch more, but since it is now stable, I think we can just remove this entire comment and this part concerning limit also.

It would be difficult to implement an optimistic effect on limit, maybe we want to do it later ? I let you decide @charlesBochet.

**Pull request merged**
