### PR TITLE
Add automatic company logo fetching during workspace creation

### LINKED ISSUE #9151: Load logo automatically during workspace
When someone signs up with a work email and creates a new workspace, we want to load the logo that corresponds to their domain from twenty-icons.com (ex: twenty-icons.com/airbnb.com) and set it as the default logo.

The user can still replace it by a desktop image if he wants to.

Useful: https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/utils/is-work-email.ts

Note: in the future we might want to return additional enrichment infos from the backend (e.g. we could pull company Name from twenty-companies.com etc), so the architecture should take that into account

### PR DESCRIPTION
**Pull request by samyakpiya**
Closes #9151 

## Description
This PR automatically sets a workspace's logo based on the user's work email domain during signup. When a user creates a new workspace using their work email (e.g., @airbnb.com), the system will fetch and set their company logo from twenty-icons.com as the default workspace logo.

## Implementation Details
- Added a new `CompanyEnrichmentService` to handle company-related data enrichment
- Created a modular architecture that supports future enrichment features (e.g., company name, details)
- Integrated with existing work email detection
- Maintains user ability to override the logo later

## Testing
https://github.com/user-attachments/assets/f7855c99-462a-4053-9e52-29649e954275

I tested the following scenarios:
- Signing up with a work email (e.g., @company.com) → Logo is automatically set
- Signing up with a personal email (e.g., @gmail.com) → No logo is set
- User can still upload a custom logo after automatic setting

## Technical Notes
- Uses existing `isWorkEmail` utility
- Structured for future extensibility (additional company data enrichment)
- No breaking changes to existing functionality

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey, this is a great PR. What you did was perfectly in line with the initial issue, but I kind of changed my mind halfway while reviewing your code. It might be over-engineering to introduce this enrichment service now and therefore I removed the company service to simplify things

**Comment by samyakpiya** [comment]
Thanks for the review @FelixMalfait! I understand the decision to simplify the implementation. I've tested your simplified version and confirmed the logo appears correctly during sign-up.

Is there anything else needed from my side, or is this ready to be merged?

Let me know if there's anything else you'd like me to help with! 👍

**Comment by FelixMalfait** [comment]
Thanks for testing it again @samyakpiya 

Feel free to DM me on Discord, happy to point you to different things we're working on!

**Review by FelixMalfait — APPROVED** [review]
Great work!

**Comment by samyakpiya** [comment]
Thanks Felix! Really enjoyed working on this feature. I've sent you a DM on Discord to discuss other areas where I can contribute. Looking forward to working on more issues! 🚀

**Pull request merged**
