### PR TITLE
feat: Add story for Object Filter Dropdown Option Select

### LINKED ISSUE #4316: Add storybook tests on ObjectFilterDropdownOptionSelect
## Scope & Context

Follow-up on this PR: https://github.com/twentyhq/twenty/pull/3656
New components have been added without any storybook test. 

## Technical inputs

File paths are the following:
- packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemSelectTag.tsx
- packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOptionSelect.tsx

### PR DESCRIPTION
**Pull request by Khaan25**
This PR fixes #4316

### CODE REVIEW

**Comment by Khaan25** [comment]
Yes, I'm getting the same error

**Comment by Khaan25** [comment]
I've created story and only imported the component to see but I'm getting this error? Do we've some providers to wrap around the story in decorators?

**Comment by charlesBochet** [comment]
I have taken a close look, looks like the ObjectFilterDropdownOptionSelect component is coupled with many things: 4 recoil states + parent dropdown + selectableList + object filter dropdown. Which is typical from an internal component that is not meant to be used of its context.

Because of that, I don't think it makes a lot of sense to test it as a standalone.

Instead, we should add more cases (including the Select field type here) to multiplefiltersdropdownbutton story
image

**Comment by Khaan25** [comment]
Okay, I'll go ahead and see and create stories for it.

I also reviewed it and saw multiple things linking to it.

**Review by lucasbordeau — APPROVED** [review]

**Pull request closed without merging**
