### PR TITLE
feat: apply temporary filter in the record details page

### LINKED ISSUE #6837: Breadcrumbs Ignore Temporary Filters on Detail Page
# Current Behavior

Temporary filters are not applied to detail page navigation. For example, I used a `name contains: l` temporary filter. However, when navigating to a detail page from that list, the temporary filter is ignored, and all companies appear in the breadcrumb navigation. (13 instead of 6)

https://github.com/user-attachments/assets/4e9ad0af-788f-49d1-a762-7a915448b70a

# Desired Behavior

We want the breadcrumb navigation on the detail page to reflect the filter applied to the list view.

### PR DESCRIPTION
**Pull request by pacyL2K19**
# This PR

- Fixes #6837 

## Demo

https://www.loom.com/share/d9bfb79f6e674956a753e59d400a8a26?sid=291e50d1-8e3c-4d4f-99b9-faa83e48f507

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@Bonapara I propose that we solve this problem in my refactor PR instead : https://github.com/twentyhq/twenty/pull/6810

The problem is that the filters and sorts aren't stored for each view but globally, which implies a lot of complexity to reset / keep the filters and sorts between pages. 

If we refactor the states so that they are stored per view, then it will be easily solvable, because this fix here will create another bug : when we go back to view, it will reset the filters.

**Comment by lucasbordeau** [comment]
@pacyL2K19 I'm closing this PR as it will be best solved in this refactor : https://github.com/twentyhq/twenty/pull/6810

**Comment by pacyL2K19** [comment]
> @Bonapara I propose that we solve this problem in my refactor PR instead : #6810
> 
> The problem is that the filters and sorts aren't stored for each view but globally, which implies a lot of complexity to reset / keep the filters and sorts between pages.
> 
> If we refactor the states so that they are stored per view, then it will be easily solvable, because this fix here will create another bug : when we go back to view, it will reset the filters.

Working on this issue made me realize we needed to clean up our state management
Makes more sense @lucasbordeau 👍🏾

**Comment by lucasbordeau** [comment]
@pacyL2K19 Indeed, I had to refactor a big chunk but the result is now way better, hope that you'll see for yourself.

**Pull request closed without merging**
