### PR TITLE
fix: content getting hide on drag and drop in stage view cards

### LINKED ISSUE #7388: Display Record content when drag & dropping
# Current behavior

The content hides when dragging & dropping a record.

### Kanban

https://github.com/user-attachments/assets/7f32181a-e02d-4846-b858-d40ec72d4d38

### Table

https://github.com/user-attachments/assets/f3ce7252-3670-42a8-b583-5cf18b7c48d7

# Desired Behavior

The fields should remain visible when drag & dropping a record.

### PR DESCRIPTION
**Pull request by Nabhag8848**
## ISSUE

-  Closes #7388 

## Demo

https://github.com/user-attachments/assets/193813aa-def9-406b-9fe7-397627bb1242

- [ ] Table Row Drag WIP

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
Thank you @Nabhag8848, I've played with it and it feels nice except for the drag and drop on the RecordTable: column size do not look to be respected

Could you fix it?

**Comment by charlesBochet** [comment]
@Nabhag8848 up on this one :)

**Comment by Nabhag8848** [comment]
Thanks, was aware, swamped with work. I'll handle it soon!

**Comment by Nabhag8848** [comment]
will need to fix #7290 first **,on it**, 

 column size is still breaking when column size is changed and also checkbox is causing issues for verifying the solution.

**Comment by Nabhag8848** [comment]
@charlesBochet should we merge just kanban changes which are working as expected ? I can revert table record changes from this PR and for table records, we can make a seperate PR while we fix dependant issues ?

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
