### PR TITLE
fix: object activate dropdown

### LINKED ISSUE #8435: Missing aria-label for inactive field button
**Scenario:**
1. Log in
2. Go to Settings > Data model > any object's details
3. Deactivate any field
4. Check in devtools rendered components

### LINKED ISSUE #8436: Activate object button is bugged
## Bug Description

https://github.com/user-attachments/assets/32427c1b-12c7-4009-b5a7-bee448e100d7

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
Fixes: #8436 
Fixes: #8435 
& other duplicate ```DropdownMenu```

### CODE REVIEW

**Comment by ehconitin** [comment]
https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34855-566375&node-type=instance&t=Qd41V7OJhUGr6u0B-0


Screenshot 2024-11-08 at 22 51 41


@harshrajeevsingh we should match width to figma, thanks ;)

@Bonapara its called erase and not delete in figma  :)

**Review by ehconitin — CHANGES_REQUESTED** [review]
looks good --- just need to adjust width

**Comment by harshrajeevsingh** [comment]
@ehconitin Ok! Will change it. Also, should I change the "Delete" text to "Erase" ?

**Comment by harshrajeevsingh** [comment]
I just found the same issue for the Object's Field Disabled Dropdown. Working on it.

**Comment by FelixMalfait** [comment]
Good catch thanks! Same as here: https://github.com/twentyhq/twenty/pull/8374/files

Would you wind also correcting it here?
Screenshot 2024-11-09 at 08 21 38

(need to un hide this in your .env)
```
# SUPPORT_DRIVER=front
# SUPPORT_FRONT_HMAC_KEY=replace_me_with_front_chat_verification_secret
# SUPPORT_FRONT_CHAT_ID=replace_me_with_front_chat_id
```

**Comment by harshrajeevsingh** [comment]
@FelixMalfait There are even more components with ```DropdownMenu``` duplicate. 

Screenshot from 2024-11-09 15-19-59

Screenshot from 2024-11-09 15-32-50

A few of them can't be seen because they are the same width. 
Also, how can I find ```MessageThreadSubscribersDropdownButton``` in UI? I know it's related to Emails, but I can't find it

**Comment by ehconitin** [comment]
I will take care of MessageThreadSubscribersDropdownButton

**Comment by harshrajeevsingh** [comment]
@ehconitin All set on my end! 
This PR also resolves an additional issue, which I’ve detailed in the description. Thanks for your guidance! :)

**Review by FelixMalfait — APPROVED** [review]
Perfect thank you!

**Pull request merged**
