### PR TITLE
3886 - Shortcut Sort/Filter

### LINKED ISSUE #3886: Add a shortcut to sort/filer from column
In Notion it's possible to click on a column to filter/sort. This would make the feature a little bit more discoverable (I had this feedback a few times during customer calls where people didn't see the top right sort/filter buttons).

Should be relatively straightforward to implement I guess.

Screenshot 2024-02-08 at 16 05 01

### PR DESCRIPTION
**Pull request by Kanav-Arora**
Closes #3886

### CODE REVIEW

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I need some help on this one. I have added the functionality for sorting but for filtering I have two problems:
- For below code in handleFilterClick function in `RecordTableColumnDropdownMenu`
  selectFilter?.({
        fieldMetadataId: column.fieldMetadataId,
        value: '',
        operand: getOperandsForFilterType(filterDefinition.type)?.[0],
        displayValue: '',
        definition: filterDefinition,
      });

if the value is '' then view bar is opening but there's no filterchip. Value can't be null as its arising problems with the backend.

- I'm unable to trigger value operand for filterchip

How can I approach this? The filtercode is very nested and I'm unable to find the right function. Please help

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Please update

**Comment by charlesBochet** [comment]
@Kanav-Arora @lucasbordeau This is unblocked and we have refactored this area.

High level arch note:
The RecordIndexContainer is the component orchestrating the RecordTable and the ViewBar. RecordTable and ViewBar cannot talk direclty to each other. It must be done through RecordIndexContainer:
- from the ViewBar (which is aware of standard object ViewFilter and ViewSort) to the RecordTable, this is done through onViewChange callback in RecordIndexContainer
- from the RecordTable (which should deal with Filter and Sort (<> ViewFilter / ViewSort) to the viewBar, the communication does not exist. We need to add a onFiltersAndSortsChange on the RecordTable and to use it in RecordIndexContainer (or through an Effect this is also possible)

Keeping these separate allow easier refactoring and cleaner APIs.

Strategy:
The RecordTable is already aware of Filter and Sort in its own states. We need to:
- create a new component state: onFiltersAndSortsChangeComponentState (similar to onColumnsChangeComponentState)
- set this new state similarly to onColumnsChange in RecordTableWithWrappers. Note that this is not correct, onColumnChange should be passed on RecordTable so there is no code within RecordTable talking about the viewSort or viewFilters which is related to the view. Remove this in RecordTableWithWrappers and set onColumnsChange and onFiltersAndSortsChange from an RecordIndexTableContainerEffect. To update the viewFilters and viewSorts, use useCombinedViewFilters and useCombinedViewSorts hook
- implement the UI

i'm available to give more information if needed. This section of the app stays a bit complex :)

**Comment by lucasbordeau** [comment]
@Kanav-Arora I've merged main and fixed some minor things.

Let's first try to have :  
- Filter button click opening filter as if we were adding a filter directly from the filter and sort bar : 
image

- Sort button click adding a sort directly on the clicked field

**Comment by Kanav-Arora** [comment]
> @Kanav-Arora I've merged main and fixed some minor things.
> 
> Let's first try to have :
> 
> * Filter button click opening filter as if we were adding a filter directly from the filter and sort bar :
> 
> image
> * Sort button click adding a sort directly on the clicked field

Ok I'll start working on it and will update you

**Comment by Kanav-Arora** [comment]
Hi @lucasbordeau
Done with sort functionality. I have created a useObjectSort api to keep sorting functionality separate. I'm starting work on filters.

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
