### PR TITLE
fix #7085 breadcrumb fix for mobile viewport

### LINKED ISSUE #7085: Header overflows in Data model for mobile viewport
## Bug Description

- Go to Settings/Data Model
- Add field and use it on mobile viewports
- Since header has Type and configure properties, it makes the buttons component overflow

## Current Behaviour

Screenshot 2024-09-17 at 11 55 28 AM
Screenshot 2024-09-17 at 12 09 22 PM

## Expected behavior

Screenshot 2024-09-17 at 11 56 43 AM

## Approach

- New field has a lot of unused spacing and padding. Removing that spacing could yield more header room
- Instead of New field and then type, we can directly give type dropdown and remove New fiedl altogether which would give a clean look.
Screenshot 2024-09-17 at 12 08 41 PM

### PR DESCRIPTION
**Pull request by NitinPSingh**
ISSUE
Closes https://github.com/twentyhq/twenty/issues/7085

DEMO 

https://github.com/user-attachments/assets/39692906-c02e-4e4c-9205-82447fa142df

### CODE REVIEW

**Comment by Bonapara** [comment]
The idea is to have a "Back button" that returns to the previous step. What seemed odd during testing?

**Comment by lucasbordeau** [comment]
@Bonapara 
image

For me it seems like "Back to XYZ" isn't relevant here as we would want to just go back to the settings menu. We would like to have the same effect as when clicking on the cog.

**Comment by Bonapara** [comment]
Let's do that @lucasbordeau, great idea!

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
