### PR TITLE
fix: Handling filename overflow in mobile viewports

### LINKED ISSUE #7330: Long File name is not optimised for mobile viewports
## Bug Description

- The files page is not optimised when file name is long for mobile viewports.
- As a result the dates and dropdown menu take up more space for smaller viewports

## Current behaviour

- Iphone 14 pro max
Screenshot 2024-09-30 at 1 26 25 PM

-  Iphone SE
Screenshot 2024-09-30 at 1 26 43 PM

## Expected Behaviour

https://github.com/user-attachments/assets/1d6af080-6e92-4e18-9081-35bdd101a3bf

### LINKED ISSUE #7516: Tasks page overflows on Adding a task
## Bug Description

- When added a task, the page overflows. This behaviour is not connected to task title or body but creating a task makes the page scroll.

## Current behavior

https://github.com/user-attachments/assets/bce2aa99-9c78-4d38-a84e-1aa1472bd7b7

## Expected behaviour

https://github.com/user-attachments/assets/07afcd1b-e508-4347-9076-d92f5292a220

### PR DESCRIPTION
**Pull request by sid0-0**
Fixes #7330
Fixes https://github.com/twentyhq/twenty/issues/7516 

<div style="display: flex">

</div>

### CODE REVIEW

**Review by lucasbordeau — APPROVED** [review]
@sid0-0 Thanks for the fix, I used this nice use case to fix a long-standing problem with the overflow cascade of our page right container.

**Comment by lucasbordeau** [comment]
@Bonapara I refactored the activity list and rows into a common component to harmonize the UI.

Before : 

Capture d’écran 2024-10-10 à 09 43 38
Capture d’écran 2024-10-10 à 09 44 04
Capture d’écran 2024-10-10 à 09 44 09

After : 

Capture d’écran 2024-10-10 à 09 44 18
Capture d’écran 2024-10-10 à 09 44 23
Capture d’écran 2024-10-10 à 09 44 30

**Comment by lucasbordeau** [comment]
@charlesBochet I fixed the show page right container overflow mismatch which was causing a lot of unwanted scrolling behaviors and forcing us to apply CSS tricks to force overflow into deeply nested child components.

**Comment by Bonapara** [comment]
@lucasbordeau related to https://github.com/twentyhq/twenty/issues/7516 ?

**Pull request merged**
