### PR TITLE
Update render.yaml

### PR DESCRIPTION
**Pull request by Apetree100122**

### CODE REVIEW

**Review by charlesBochet — CHANGES_REQUESTED** [review]
@Apetree100122 Thanks for the PR it seems to be some indent issues in your file. (see greptile-apps comments)

Also, could you introduce redis container?

**Comment by charlesBochet** [comment]
Ideally the render.yaml should mirror: https://github.com/twentyhq/twenty/blob/main/packages/twenty-docker/docker-compose.yml

**Comment by charlesBochet** [comment]
Closing the PR as it does not seem to work on my side and no fresh activity. Feel free to re-open it :)

**Comment by KazeroG** [comment]
@charlesBochet 

I updated the render.yaml, tested it on my side and should work

To-do : 

- [ ] it's missing a Redis
- [ ] test in production env
- [ ] deploy

`render.yaml`
```
# Exported from Render on 2024-10-12T14:37:13Z
services:
- type: worker
  name: twenty:worker
  runtime: image
  image:
    url: docker.io/twentycrm/twenty:latest
    creds:
      fromRegistryCreds:
        name: dockerhub
  plan: standard
  envVars:
  - key: REFRESH_TOKEN_SECRET
    sync: false
  - key: LOGIN_TOKEN_SECRET
    sync: false
  - key: FILE_TOKEN_SECRET
    sync: false
  - key: ACCESS_TOKEN_SECRET
    sync: false
  - fromGroup: Twenty
  region: oregon
  dockerCommand: yarn run worker:prod
- type: web
  name: twenty:server
  runtime: image
  image:
    url: docker.io/twentycrm/twenty:latest
    creds:
      fromRegistryCreds:
        name: dockerhub
  plan: standard
  envVars:
  - key: REFRESH_TOKEN_SECRET
    sync: false
  - key: LOGIN_TOKEN_SECRET
    sync: false
  - key: FILE_TOKEN_SECRET
    sync: false
  - key: ACCESS_TOKEN_SECRET
    sync: false
  - fromGroup: Twenty
  region: oregon
  dockerCommand: yarn run start:prod
  disk:
    name: disk
    mountPath: /.local-storage
    sizeGB: 5
version: "1"
```

**Pull request closed without merging**
