### PR TITLE
fix: Invite by email table overflows in mobile viewport

### PR DESCRIPTION
**Pull request by harshit078**
##Description

- This PR solves the issue #7253
- Made the invite table mobile friendly for all media width

## Before

https://github.com/user-attachments/assets/458bd47d-38fb-4ddc-a996-c1bb3908d014

Screenshot 2024-09-27 at 1 30 52 AM

## After

Screenshot 2024-09-27 at 1 34 11 AM

https://github.com/user-attachments/assets/7a4f6f9a-7fef-42f1-a226-59a1d73767f4

> [!Note]
> I've added 2 implementations and if either doesn't follow design rules then it can be changed- 
> - Made the trash icon `accent danger`
> - When emails are long, given scroll for ease of convience.

### CODE REVIEW

**Comment by ehconitin** [comment]
> Note
> 
> I've added 2 implementations and if either doesn't follow design rules then it can be changed-
> 
> * Made the trash icon `accent danger`
> * When emails are long, given scroll for ease of convience.

@Bonapara

**Comment by Bonapara** [comment]
The video won't play, but scrolling through the emails sounds cool! We should keep the icon gray since our design system currently doesn't include colors for icon buttons.

**Comment by ehconitin** [comment]
video reupload - 
@Bonapara 

https://github.com/user-attachments/assets/aa7b75e5-fa43-4fff-a348-97a84e43815f

**Comment by harshit078** [comment]
@Bonapara Fixed the icon !

**Comment by ehconitin** [comment]
@harshit078 Thanks for this PR, could you also handle these changes?
1) Align the `Email` column header and its corresponding content to the left.
2) Align the `Expires In` column header to the left.
3) Ensure that the email icon stays fixed in place while the email text scrolls if necessary.

**Comment by harshit078** [comment]
> 
> 
> @harshit078 Thanks for this PR, could you also handle these changes?
> 
> 1. Align the `Email` column header and its corresponding content to the left.
> 2. Align the `Expires In` column header to the left.
> 3. Ensure that the email icon stays fixed in place while the email text scrolls if necessary.

> [!Note]
> - Fixed email column header to left
> - The expires in column is aligned with its content when refreshed then only the tag takes width
> - Gave smooth and fixed scroll animation which makes it scroll back to its position and only gave scroll to mobile viewport


https://github.com/user-attachments/assets/7544aeec-d26d-4e02-8532-cfa11214dd67

**Comment by ehconitin** [comment]
@Bonapara 

https://github.com/user-attachments/assets/6994ed99-e39c-410b-8131-94fd6c674cf1

**Comment by Bonapara** [comment]
Looks 1) is not fixed yet, right @harshit078?
We can keep 2) aligned to the right; it's the desired behavior.
3) couldn't view in video, are icons scrolling to the left? It's a good idea to keep them sticky indeed!

Thanks to you both ;)

**Comment by harshit078** [comment]
@Bonapara, I fixed all the concerns that you mentioned. 

- Fixed email icon and emails scroll behind it for a smooth UI
- Fixed (1)

https://github.com/user-attachments/assets/5a440b68-cf43-4003-9616-5de52b125583

**Comment by ehconitin** [comment]
Before:
image

After:
image

Before:
image

After:
image

(1) seems to be still broken, its not just headers left alignment but also its corresponding cells :)
for now it seems to be broken on desktop width also

**Comment by Bonapara** [comment]
@ehconitin thanks! Can we keep the Text/primary color for the emails & icons? Looks it was changed to "secondary" in the "after" screenshot. Also Looks like the mail icons are no longer properly vertically aligned with the email in the desktop "after" screen.

**Comment by harshit078** [comment]
@ehconitin, I've made the changes. 
- Align icons under TableHeader
- Fixed( 1)

Could you check for on your localhost (1) ?

**Comment by harshit078** [comment]
- Webapp
Screenshot 2024-10-06 at 2 39 53 AM

- Mobile
Screenshot 2024-10-06 at 2 40 05 AM

**Comment by harshit078** [comment]
There are two edge cases with the Members table - 
- If name of the user is long
- If email of the user is long

To tacke these edge cases - 
- To handle user name long, name has  `white-space: pre-line;` which be ideal scenario
- To handle long emails, same propety as invite by email table is given which is scroll.

https://github.com/user-attachments/assets/dec5840e-25e8-4369-bf78-029840c39c5a

## When name not long and email is long

Screenshot 2024-10-07 at 2 47 36 AM

## General Scenario 
Screenshot 2024-10-07 at 2 49 54 AM

**Comment by ehconitin** [comment]
@charlesBochet could you please take a look?
Thanks

**Review by martmull — APPROVED** [review]
LGTM

**Pull request merged**
