### PR TITLE
Fixed: Select fields now selects on pressing the enter key

### LINKED ISSUE #5556: In the Companies table, Select fields don't select on pressing the enter key
## Bug Description

When I'm entering companies into the main table view, I have a select field.  I can jump between text fields with 'enter' or 'tab', but when I type into a select field and only one option is filtered down, 'enter' doesn't select it and move to the next field

**Example:** 

image

## Expected behavior

I'd expect to be able to press enter to select the option if I've typed enough to filter down to a single option

### PR DESCRIPTION
**Pull request by shashankvish0010**
Now while pressing the `Enter` button, the select field selects the relevant option.

- Added a `handleKeyDown` function to set the `persistField` with the selected option.
- Added an `onKeyDown` event on `DropdownMenuSearchInput` component, to trigger `handleKeyDown` when `Enter` is pressed.
- Fixes: #5556

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Hi @shashankvish0010, 

Thanks for contributing. 

We handle keydown event with a specific logic in twenty, because we have many components that listen at the same time for the same shortcuts (enter and escape mainly), we have to use a system of priority to allow only one component to listen at the same time.

We use what we call hotkey scopes for managing this, and we switch back and forth between hotkey scopes to give the focus on only the component that needs it.

In order to make a proper implementation, here are the steps that you should go through : 
- Look at the hook : `useScopedHotkeys`, to understand how hotkey scopes work
- Look at an example (in Dropdown for example)
- Look at the already existing hotkey scopes in SelectFieldInput.

Hints : Look in `RecordTableCellFieldContextWrapper`, maybe you just have to add another condition here for `isFieldSelect` : 

```tsx 
 const customHotkeyScope = isFieldRelation(columnDefinition)
    ? RelationPickerHotkeyScope.RelationPicker
    : TableHotkeyScope.CellEditMode;
```

**Comment by lucasbordeau** [comment]
The documentation has been updated to explain this more in depth : https://docs.twenty.com/contributor/frontend/hotkeys

**Comment by shashankvish0010** [comment]
> The documentation has been updated to explain this more in depth : https://docs.twenty.com/contributor/frontend/hotkeys

Thanks for sharing the documentation, I have pushed the changes, waiting for your feedback over it.

**Comment by lucasbordeau** [comment]
@shashankvish0010 This is ok, there are other things to fix in this component though, we'll fix it later.

I just refactored a bit according to our coding style.

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
@shashankvish0010 For reference https://github.com/twentyhq/twenty/pull/6322

**Pull request merged**
