### PR TITLE
Record Page Navigation Arrows Cause Unnecessary skeleton loading

### PR DESCRIPTION
**Pull request by ehconitin**
@Bonapara 
Issue #6325 

- Desired Behavior
The navigation should always be visible. Clicking on a Next/Previous arrow should immediately increment the number without switching to the skeleton loading step.
**Done** 

Please let me know what do you think about this approach.

Thanks :)

https://github.com/user-attachments/assets/bda3608f-87e3-45bd-a7c8-4a6b48391cf2

### CODE REVIEW

**Comment by Bonapara** [comment]
Thanks @ehconitin! Could the "Chevron icon button" remain active so a user can click it multiple times? For instance, if I'm on record 8 and want to access record 11, I would like to click the `chevron down icon button` three times without waiting for records 9 and 10 to load first.

**Comment by ehconitin** [comment]
Hey @Bonapara, let me get back to you regarding `chevron down icon button` being active.

Yes I am on discord, would love to have a chat with you.
username - **neeko2853**

**Comment by ehconitin** [comment]
@Bonapara 
- Could the "Chevron icon button" remain active so a user can click it multiple times? For instance, if I'm on record 8 and want to access record 11, I would like to click the chevron down icon button three times without waiting for records 9 and 10 to load first.

I looked into how this can be achieved. Could it be done on counting the number of clicks and calling the function which navigates the records prev or next that many times? 
what do u think about this approach? 
This is the only way I could think of without making a major changes to the `useRecordShowPagePagination` hook. which is a complex change and would need some help with.
:)

**Comment by Bonapara** [comment]
Hi @ehconitin, thanks for your answer. I think you're right; this requires a deeper refactor by @lucasbordeau. Instead of fetching the next ID when the page loads, we should fetch the next five and the previous five at once. This way, we can handle navigation without waiting for the page to load each time we want to move to the next record.

@lucasbordeau WDYT? Should I create an issue? I think we can merge this PR in the meantime

**Comment by martmull** [comment]
@Bonapara there is a bug when we refresh the page, the display `1 of 13 companies` turns into `companies (13)`, not related to that PR but I wanted you to know

**Review by martmull — APPROVED** [review]

**Review by martmull — CHANGES_REQUESTED** [review]
@Bonapara asked for a complete removal of the loader
EDIT: Forget it, wrong PR

**Review by martmull — APPROVED** [review]

**Pull request merged**
