### PR TITLE
Devenv setup via devenvious

### PR DESCRIPTION
**Pull request by gotjoshua**
This PR adds a devenv template based on [devenv.sh](https://devenv.sh/),  this is a nice to have for devs that use nix, direnv, and devenv.
It provides a quick and easy way to ensure that all packages that are needed to start up the dev environment are installed.
I've initialized using devenvious, which is a @tennox creation: [source on gitlab](https://gitlab.com/txlab/dx/devenvious).

I acknowledge that this "clutters" the root dir with some less common files, but they are harmless for those that don't use the tools, and helpful for those that do... a bit like .vscode and .idea folders.

### CODE REVIEW

**Comment by gotjoshua** [comment]
wow, greptile is bada$$ !
before i engage to address their concerns, i would like a reality check from a maintainer... is this worth pursuing?

**Comment by FelixMalfait** [comment]
@gotjoshua really appreciate the effort and you sharing the work with us, but it does go against a few principles we have which are to (1) keep the root as clean as possible (although we could do better already) (2) not merge things that we can't maintain ourselves/that aren't used daily by the core team and properly tested.
So most likely is that we would close this, I'm sorry :(
@charlesBochet what do you think?

**Comment by gotjoshua** [comment]
> keep the root as clean as possible @FelixMalfait 

totally get that, and i know it is a serious challenge in a monorepo.

this PR can still serve any devs who want a similar setup.

> appreciate the effort 
well its the nearly the only way i can get a repo running on my nearly fully declarative system, the effort is not exactly optional ; -D

**Comment by FelixMalfait** [comment]
Hey @gotjoshua we discussed it internally and decided not to merge it because we wouldn't be able to maintain it properly.
That being said, I added the files to .gitignore that way you can keep them locally without needing to maintain a fork. 

If anyone is looking for "devenv" keyword on Github or in the codebase+git blame, then at least this PR should come up and then they would be able to find your config here: https://github.com/twentyhq/twenty/tree/0f50c3ab716c3f7520ab46fba79457d5a5c74534 
(please don't delete your fork)

Thanks!

**Pull request merged**
