### PR TITLE
Fixed Issue 6278 : Existing filter value isn't passed to the component …

### PR DESCRIPTION
**Pull request by ViditJain123**
I Fixed Issue number #6278 . It has the desired behaviour now. Looking for review on it.

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Thanks! Can you try tackling those without `useEffect`?
We only use useEffect in very limited use-cases
https://react.dev/learn/you-might-not-need-an-effect

**Comment by FelixMalfait** [comment]
Also I didn't try it but make sure all the filter is reflected so if I selected "date is greater than X", the "GREATER THAN" should also remain when editing the filter. Thanks :)

**Comment by ViditJain123** [comment]
On it

> Thanks! Can you try tackling those without `useEffect`? We only use useEffect in very limited use-cases https://react.dev/learn/you-might-not-need-an-effect

On it!

**Comment by Weiko** [comment]
Closed the PR since it has been stale for a while. Feel free to take another issue!

**Pull request closed without merging**
