### PR TITLE
fixed Object settings font weight fixes

### LINKED ISSUE #3319: Object settings font weight fixes
# Current behavior

The font-weight of icons is regular
The tag font-weight is medium

image

# Desired behavior

The font-weight of icons should be light
The font-weight of tags should be regular (Just on this page, should not change the weight of tags on the object detail page)

CleanShot 2024-01-09 at 11 02 29

### PR DESCRIPTION
**Pull request by abdul-irfan-k**
fix #3319
Screenshot from 2024-01-09 19-49-12

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@Bonapara We use icon stroke for icons, we could lower the "sm" stroke size from 1.6 to 1.4 to match the Figma stroke size what do you think ?

**Comment by Bonapara** [comment]
@lucasbordeau, when Charles and I implemented it, we observed that the font-weight of icons appeared lighter in Chrome compared to Figma. That's why it's 1.6 instead of 1.4) It would be great if the properties were consistent, ensuring that they render the same way but not sure it would work!

Also, in this specific case, the weight should be lighter than SM, (1.0 on Figma)

**Comment by abdul-irfan-k** [comment]
can i change it

**Comment by charlesBochet** [comment]
@abdul-irfan-k I have checked with @Bonapara 
Let's only fix the Tag weight :)

**Review by charlesBochet — APPROVED** [review]
Thank you @abdul-irfan-k :)

**Pull request merged**
