### PR TITLE
feat:  twenty raycast integration

### PR DESCRIPTION
**Pull request by Nabhag8848**
<h1 align="left"> 🔥 Twenty Raycast Integration </h1>

codebase link: https://github.com/Nabhag8848/twenty-raycast-integration
tweet Link: https://x.com/NabhagMotivaras/status/1850496053474422870

 With this Raycast integration, record creation across standard and custom objects is now at your fingertips, making your workflow effortless and efficient. Experience how easy it is to use this Raycast for seamless record creation!

> 🤝 Create records instantly across Standard and Custom  Objects

### <i>Create Object Record</i>
With `Create Object Record` command, effortlessly create records in any standard or custom object. Search command press Enter to see active objects, then press `CMD + Enter` to unveil a form that fills in your record seamlessly into the CRM table — making CRM magic happen!

---

## Getting Started

Get your API Keys from [twenty developer settings](https://twenty.com/settings/developers) , navigate to Raycast Command settings or try to access command which will open up view to provide your API key. 
<table>
  <tr>
  <td>Twenty Api Token View</td>
  </tr>
</table>

if you are selfhost user navigate to `<self-host-url>/settings/developers`, once you have your key, go to Raycast Command Settings to provide your `selfhost api url` and `API key`. If you don't provide selfhost url, Integration will assume [https://api.twenty.com](https://api.twenty.com) as your instance.

<table>
  <tr>
    <td>Raycast Settings</td>
  </tr>
</table>

---

## User Guide
To use the integration, search for the `Create Object Record` command, which will display all your `active` standard and custom objects currently in your twentyCRM. Its very flexible - if you create new objects or deactivate existing ones, this will automatically reflect those changes.

https://github.com/user-attachments/assets/fca0f71d-3c04-43ad-afb4-4e5b0a9d4d13

When you deactivate any standard or custom object, it will no longer appear, ensuring you only see the information and objects you want to access. This makes the integration extensible and enhances your productivity.

https://github.com/user-attachments/assets/f357b91b-dd2e-4043-af8c-9328235c0aa8

If you create new custom objects, they will appear, allowing you to quickly create your records instantly from Raycast.

https://github.com/user-attachments/assets/f0d8fa96-468b-42e4-a11c-a9e4a47ce412

To create a record for any object, select your target object and press ` ENTER`. This will open a form that matches the exact table schema you created in your CRM, following any validations it suggests to successfully create your record by pressing `CMD + ENTER`. Records cannot be created with an empty first column (such as Name, Title, etc.).

https://github.com/user-attachments/assets/6f8d7127-63a6-4113-ac6a-5ea3003c5f0c

Similar to creation of standard objects record you can create custom objects record

https://github.com/user-attachments/assets/098e120c-ac58-4f41-9560-2782c798d6bd

It's much more flexible—similar to objects, if you deactivate any fields, they will no longer appear in your object schema during record creation.

https://github.com/user-attachments/assets/2686c7c0-dfde-4445-93be-17d10cf22d60

No worries! If you add or update any fields in your standard objects, they will automatically appear in your object schema form in Raycast, looking closely you will see, if you add a select field with a default value provided some icon, it will display exactly what you’ve set when creation.

https://github.com/user-attachments/assets/697da72b-1ca2-4493-b61c-d393b77b34f6

## Roadmap

- [x] Currently we support `FULL_NAME`, `TEXT`, `LINKS`, `EMAILS`, `SELECT`.
- [x] Supporting other fields are easy as we have build the foundation and its quite similar to what we have already build.
- [ ] PHONE_NUMBER, CURRENCY similar to LINKS
- [ ] RATING (1, 2, 3, 4, 5 as option), BOOLEAN (True or False as option), MULTI_SELECT are similar to SELECT
- [ ] RELATION Similar to SELECT but requires additional work but doable
- [ ] support seeing records of all objects

### CODE REVIEW

**Comment by Nabhag8848** [comment]
@CoreTeamTwenty @FelixMalfait @charlesBochet @Bonapara Excited to share v1 of the most flexible twenty raycast integration.

- [x] we support creation of all active standard and custom objects.
- [x] create new objects or deactivate existing ones, this will automatically reflect those changes.
- [x] with Validations of table fields. 
- [x] Support of self host users.
- [x] deactivate any fields, they will no longer appear in your object schema during record creation.
- [x] currently we support `FULL_NAME, TEXT, LINKS, EMAILS, SELECT`.
- [x] extended capabilities such that we can provide additionalLinks, similarly additionalEmails. If we look closely on SELECT field in one of above demos. I have matched colors of `options Icons`  to match ours. here: https://github.com/Nabhag8848/twenty-raycast-integration/blob/main/src/enum/icons.ts#L12

**Comment by Nabhag8848** [comment]
Looking for feedbacks on how we can improve this much more, If this is a kind of solution, what you folks were looking for, I would love to release this to raycast marketplace and we can do that from a twenty's account which will help for better visibility and much much more.

**Comment by FelixMalfait** [comment]
Hey @Nabhag8848 sorry for the delay - I've been wanting to look at Raycast integration more in-depth but we've been busy with other fixes. I'll be checking it soon. Thanks a lot!

**Comment by FelixMalfait** [comment]
/award 2000 (great work on abstracting the objects)

**Comment by lucasbordeau** [comment]
Please @Nabhag8848 see with @chrisdadev13 for not duplicating your work and work together for a great raycast extension !

**Comment by charlesBochet** [comment]
Hi @Nabhag8848,

First I would like to apologize for the slow review. I have taken a deep look at your code and this is very interesting. Your extension is actually more in line with our flexible data model philosophy powered by objectMetadata than the existing one: https://github.com/raycast/extensions/tree/main/extensions/twenty/src.

We have been debating this internally and we would love to have the community build and maintain a Raycast extension. I'm happy to guide you if you need any help. 

I'm not going to need this PR as oss.gg event is closed the folder has been removed but if you want to update https://github.com/raycast/extensions/tree/main/extensions/twenty/src and take over it I would support this community maintained extension

Thanks again for all the work

**Pull request closed without merging**
