### PR TITLE
fix: dropdowns should have a max-height & padding from screen

### LINKED ISSUE #6105: Dropdowns should have a max-height and a scroll bar
I was shadowing a client that had created lots of field and the Filter dropdown was bigger than their screen's height.
We might (or might not?) want to set a max-height.
Also we want to make sure there's a scroll bar upon scroll (when I added a max-height directly in Chrome, the dropdown become scrollable but I couldn't see any scroll bar)

cc @Bonapara for recommandation

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
Fixes: #6105 

### Problem

- The dropdown gets clipped when the number of filters increases. 

### Solution

- Added scroll property to the ```DropdownMenu``` 
- Added size middleware to the floating UI hook.
- Provided padding of 20px to the size middleware, so that it maintains distance from the bottom of the screen.

[Screencast from 2024-10-25 13-47-04.webm](https://github.com/user-attachments/assets/c2315ee2-6092-4c4a-8126-dba7ac3bf49b)

### CODE REVIEW

**Comment by FelixMalfait** [comment]
/award 500
I'm not confident enough to approve but rewarding the effort at least! Thanks!

**Comment by harshrajeevsingh** [comment]
@FelixMalfait Thanks for your constant support :)

**Review by martmull — APPROVED** [review]
LGTM, thank you that's nice fix. I have just updated the padding value so it matches figma design

**Comment by harshrajeevsingh** [comment]
@martmull Thanks for the merge. But due to some recent changes to this component (before raising this PR), I found an issue with this solution. In the attached screencast, you can see that at some point, the dropdown behaves weirdly. 
However, I found a solution for this. Can you raise an issue? Then, I can make a PR with a different solution.

[Screencast from 2024-10-29 13-51-57.webm](https://github.com/user-attachments/assets/6c837798-08e0-44fc-8e6f-ae53e0a56b25)

**Comment by martmull** [comment]
@harshrajeevsingh ok thank you for checking that. I will revert that merge and then open a new issue so you can add a proper solution to that issue

**Pull request merged**
