### PR TITLE
Fix task text overflow

### LINKED ISSUE #5552: Adding a task with attached text containing a long first line isn't truncated, and breaks layout
## Bug Description

Adding a task either without attached text, or with attached text containing a short initial line, keeps layout fine:

Screenshot 2024-05-23 at 17 15 20

Screenshot 2024-05-23 at 17 17 56

If however text is attached with a longer first line, then the full line is displayed without truncation, which breaks the table layout:

Screenshot 2024-05-23 at 17 18 21

## Expected behavior

Expected attached text to be truncated regardless or content or length, to ensure table layout remains consistent.

## Technical inputs

- Create a new task
- Add text with a very long single line and save

Observed on v0.11.2 installed via Docker.

### PR DESCRIPTION
**Pull request by brendanlaschke**
closes #5552

Bildschirmfoto 2024-07-19 um 23 35 25

### CODE REVIEW

**Comment by ijreilly** [comment]
Hey @brendanlaschke thank you for your multiple contributions!!
just checked out your PR, looks much better - I just wonder if we wouldn't want to get rid of the scrolling behaviour and fix a maximum width instead - what do you think?

**Comment by brendanlaschke** [comment]
> Hey @brendanlaschke thank you for your multiple contributions!! just checked out your PR, looks much better - I just wonder if we wouldn't want to get rid of the scrolling behaviour and fix a maximum width instead - what do you think?

Maybe im a bit confused but where is a scrolling behavior? For me the task row,task body and task text look all normal without scrolling?

**Comment by ijreilly** [comment]
@brendanlaschke sorry I meant to attach a recording but it didnt go through or I just forgot to:

https://github.com/user-attachments/assets/e0fa3fb6-7bd6-476a-ae85-a0cb88fb75c0

**Comment by brendanlaschke** [comment]
> @brendanlaschke sorry I meant to attach a recording but it didnt go through or I just forgot to:
> 
>  scrolling.mov

Oh i was on the /tasks page. But this is not a task specific problem it also exists for all the other tabs but a regression on the layout on the object page ...

 
Bildschirmfoto 2024-07-23 um 11 39 29

**Comment by ijreilly** [comment]
I see - thanks :) merging !

**Review by ijreilly — APPROVED** [review]

**Pull request merged**
