### PR TITLE
Extract a major chunk of modules/ui to twenty-ui

### PR DESCRIPTION
**Pull request by mabdullahabaid**
PR to extract a major chunk of modules/ui to twenty-ui. Maintained the folder structure from modules/ui for ease. Left a few components in twenty-front due to their nested dependencies.

Ran `yarn nx build twenty-front` and the application built successfully.
Ran `yarn nx start twenty-front` and the dev server started up successfully.
Ran `yarn nx coverage twenty-front`, but got a ton of errors - testing is broken due to extraction.

Challenges to resolve from here on:
- Extract the remaining components.
- “twenty-ui” namespace has become too cluttered. Could be worth it to nest things (e.g., icons should be imported from “twenty-ui/icons” and theme should be imported from “twenty-ui/theme” for convenience).
- Had to remove tests within twenty-ui when extracting components (they were throwing errors). Will need to re-integrate them.
- Testing within twenty-front needs fixing - coverage job will fail when Github workflows run.
- Work on individual components to make the library generic.
- Work on storybook to display and document components.
- Work on twenty-docs to help contributors.

Screenshot 2024-03-18 at 5 42 31 AM
<br />
<br />
Screenshot 2024-03-18 at 5 42 55 AM

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@mabdullahabaid I see two problems with tests : 
- (difficult) Jest struggles to parse css in js with styled with @emotion/styled in `InternalDatePicker.tsx`.
- (less difficult) Old paths are still hardcoded and mocked in some tests.

I already spent some time on the first problem but couldn't find anything.

**Comment by mabdullahabaid** [comment]
@lucasbordeau fixed both the mentioned issues, but ran into a few more which I could not resolve.

For the first issue, Jest was having trouble parsing both emotion/styled and .css within the same component. Had to install `identity-obj-proxy` and update `moduleNameMapper` inside jest.config.ts. Also added `transformIgnorePatterns: ['<rootDir>/../../node_modules/']` to jest.config.ts.

**Comment by mabdullahabaid** [comment]
Apparently, GitHub only ran two checks, which is strange. Not sure what happened there.

**Comment by mabdullahabaid** [comment]
Turns out I did not actually solve the second problem. That issue still persists and the files containing that issue can be found by searching `('twenty-ui',` globally in the code base. I have no prior experience working with tests, can use some help fixing those paths. 

For reference, the following paths need to be fixed.

useAvailableScopeIdOrThrow
extractComponentState
useSetHotkeyScope
usePreviousHotkeyScope

**Comment by mabdullahabaid** [comment]
We are down to this from 96 test suites failing yesterday. Per my research, the module `twenty-ui` is not being mocked, and the actual module is being imported in `useMoveSoftFocusToCurrentCellOnHover.test.tsx`, `useCloseRecordTableCell.test.tsx`, and `useOpenRecordTableCell.test.tsx`. My last commit fixed a similar issue for `useEmailThreadStates.test.ts`. This might also be the issue with `useKeyboardShortcutMenu.test.tsx` although another angle to consider is the enum behavior in Typescript.

Screenshot 2024-03-21 at 5 15 36 PM

**Comment by thaisguigon** [comment]
Hi @mabdullahabaid!
Thank you for your contribution, it's really helpful!
I reworked this PR a little bit, however there are a lot of conflicts that are becoming difficult to solve, so I will split this PR into smaller ones. Hopefully this will allow us to fix the tests issues and merge the changes soon!

**Comment by mabdullahabaid** [comment]
Hi @thaisguigon

Thank you for reworking this PR and fixing some of the things I missed. I tried extracting most of it in a single PR to speed things up, but it might have been better to extract things in smaller PRs due to conflicts.

I like the idea of splitting it into smaller ones now - feel free to pull me in if you want to delegate some work. Also, if splitting this PR is hard to pull off, I can redo the extraction in smaller chunks and we can close this PR altogether - not a problem, ofc.

**Comment by charlesBochet** [comment]
@mabdullahabaid 
@thaisguigon has made good progress, she will ping you once we are ready to proceed!

**Comment by mabdullahabaid** [comment]
@charlesBochet following the progress regularly, sounds good!

**Pull request closed without merging**
