### PR TITLE
fix: Correct space between menu icons and menu items text #423

### PR DESCRIPTION
**Pull request by deepaksing**
this pr solves issue #423 

**issue**:
margin-left for currentWorkspace.displayName was 4px

i have set it to 8px by using :  **{ props.theme.spacing(2) }**

### CODE REVIEW

**Comment by charlesBochet** [comment]
@deepaksing Thanks for the PR! Are you sure you have linked the right issue?

**Comment by deepaksing** [comment]
@charlesBochet, yes

**Review by FelixMalfait — APPROVED** [review]
At first I thought @Bonapara had described something different too (the list with multiple items is what is confusing), but I checked the Figma and can confirm that was the intended change! Thanks again @deepaksing 🙌

**Comment by FelixMalfait** [comment]
Storybook [tests](https://www.chromatic.com/build?appId=647862655ef7071d35328bb2&number=546) show many differences because it wasn't rebased on `main` recently, but since it's a small PR with a predictable change I'm merging 🚀

**Comment by charlesBochet** [comment]
Ok, great!

**Pull request merged**
