### PR TITLE
Fix keyboard cmds table soft focus

### LINKED ISSUE #2533: Cannot refresh with cmd + r in table
## Bug Description

When in table focus mode, we cannot refresh the page with cmd + r, maybe use other shortcuts as well.

## Expected behavior

If no useful shortcut is detected on the table, then just allow the default browser shortcut to work.

## Technical inputs

See maybe in `RecordTableCellSoftFocusMode` component in the `useScopedHotkeys('*',`

### PR DESCRIPTION
**Pull request by brendanlaschke**
Fixes the keyboard commands by calling stopPropagation only if really needed. 

closes #2533

### CODE REVIEW

**Comment by charlesBochet** [comment]
@brendanlaschke @lucasbordeau I actually cannot reproduce the issue. Is it still there on main?

**Comment by brendanlaschke** [comment]
Yes it is still there:

1. go into a cell edit mode
2. click outside until you are in the soft focus state for one cell
3. press Cmd+R

**Comment by charlesBochet** [comment]
Ok, got it, I could reproduce!
@lucasbordeau could you have a look at @brendanlaschke 's change?

**Review by Weiko — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
