### PR TITLE
Submission for new logo design side quest

### PR DESCRIPTION
**Pull request by Ionfinisher**
This is my submission for the new logo design side quest

### CODE REVIEW

**Comment by Ionfinisher** [comment]
Quick question for the maintainer. Please how can I submit my entry for the starry-eyed supporter side quest for this repo?

**Review by charlesBochet — APPROVED** [review]
Thanks @Ionfinisher 
Looks bit 29 to me but we could buy twentynine.com :p

**Comment by charlesBochet** [comment]
/oss.gg 300

**Comment by Ionfinisher** [comment]
Thanks @charlesBochet :p. What about my earlier question please?

> Quick question for the maintainer. Please how can I submit my entry for the starry-eyed supporter side quest for this repo?

Thanks @charlesBochet :p. What about my question?

**Pull request merged**
