### PR TITLE
Bug: Datepicker overlaying year and buttons filter menu

### PR DESCRIPTION
**Pull request by jobayer12**
Bug: Datepicker overlaying year and buttons filter menu #1856

### CODE REVIEW

**Comment by charlesBochet** [comment]
@bosiraphael our Dropdown expert, could you take a look?

**Comment by bosiraphael** [comment]
@charlesBochet I will take a look.

**Comment by bosiraphael** [comment]
@jobayer12 we created a new issue which follows this one https://github.com/twentyhq/twenty/issues/1891#issuecomment-1749408094, to update the width only when the component is a Datepicker.

**Comment by charlesBochet** [comment]
Thank you! See my comment here: https://github.com/twentyhq/twenty/issues/1856#issuecomment-1752638245

**Pull request closed without merging**
