### PR TITLE
AB-1 fix: Change the light icon button color back to tertiary

### LINKED ISSUE #8492: Phone, Email, Domain input Light Icon Button color change
# Current behavior

The button color has changed to secondary.

CleanShot 2024-11-14 at 09 02 41

CleanShot 2024-11-14 at 09 04 17

# Desired Behavior

Use the "Light Icon Button" in its `Tertiary` variant.

CleanShot 2024-11-14 at 09 05 02

Make sure to do it for Domain, phone, and email inputs

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=28562-74852&node-type=instance&t=PcKBW7G3Bj3eu6UD-11

### PR DESCRIPTION
**Pull request by aushwin**
**Description**
- Changed the Light Icon Button color back to tertiary
- Resolves #8492

**Screenshots**
Screenshot 2024-11-14 at 10 10 16 PM

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey @aushwin thanks! We want to change not the default value but the value in the specific contexts that are mentioned in the issue. cc @Bonapara

**Comment by Bonapara** [comment]
Hi @aushwin, thanks for the PR! We should keep the default color of `Light Icon Buttons` to `Secondary` but apply the `Tertiary` variant in the specified locations. Does it make sense?

**Comment by aushwin** [comment]
@Bonapara @FelixMalfait My Bad, will make the correction 😀

**Comment by aushwin** [comment]
@Bonapara  Could you take a look and let me know if the approach I've implemented is viable? I’ll apply it to the rest if it’s good to go.

**Comment by aushwin** [comment]
@Devessier bumping this..

**Comment by FelixMalfait** [comment]
Hey @aushwin, sorry it was just a simple fix so @Bonapara made it in another PR #8517
Thanks a lot for giving it a try!

**Comment by aushwin** [comment]
@FelixMalfait yep did see that. Maybe it's because i wasn't aware of the codebase. I thought the menuitemdropwdown component is used in more places than the whats been told in the issue 😔 .. will be hanging around with more prs thou 🏃‍♂️

**Comment by FelixMalfait** [comment]
Great thanks @aushwin

**Pull request closed without merging**
