### PR TITLE
ossgg: article, blog, migration script, n8n workflow 

### PR DESCRIPTION
**Pull request by RajuGangitla**
Total points : **3750 points** 

1. Self hosting guide (750 points)
[link](https://dev.to/raju_gangitla_91920e1427f/self-hosting-twenty-crm-a-complete-guide-559n)

2. Blog posted on my company website  (750 points)
[blog](https://zedblock.com/blog/twenty-crm)

3. i wrote a script for data migration from zoho to twenty (750 points)
here is the [github link](https://github.com/RajuGangitla/twenty-migration-scripts)
here is the [video link](https://www.loom.com/share/f072bf31fb46449d98d6826a3a824fe9?sid=21f2c3f4-f286-43a2-98aa-d1fb92c3a86e)

4. created a n8n workfow for which will add, update and delete people data in google sheets whenver we change in twenty dashbaord (750 points)
i attached the template json down below 
here is the [video](https://www.loom.com/share/89f86ef895e946fbbbbae3cc90559bb7?sid=5015c1da-b472-46c3-b144-1d170bdf5c9f)

[twenty_leads_to_google_sheets.json](https://github.com/user-attachments/files/17576685/twenty_leads_to_google_sheets.json)

5. Wrote a comprehensive guide on " integrate Twenty with marketing automation tool (n8n, Zapier). " (750 points)
Here is the [link](https://dev.to/raju_gangitla_91920e1427f/automating-people-data-sync-n8n-workflow-for-twenty-crm-and-google-sheets-5789)

### CODE REVIEW

**Comment by RajuGangitla** [comment]
@charlesBochet @FelixMalfait @Bonapara 
Could you please review this? Today is the final deadline for OSS.gg submissions. Thank you!

**Comment by FelixMalfait** [comment]
The second article is much better than the first one, could you please make sure it's this one that's linked from the index of your blog? Thanks a lot!

https://zedblock.com/blog/share-your-experience-using-twenty-a-detailed-blog-post
https://zedblock.com/blog/twenty-crm

**Comment by RajuGangitla** [comment]
sure @FelixMalfait

**Pull request merged**
