### PR TITLE
2495 fix cmdk removal and added toggle functionality

### LINKED ISSUE #2495: Remove cmkd package from CommandMenu
## Scope & Context

In the early days, we were using cmdk package to power our CommandMenu. We would like to get rid of it.

## Technical inputs

Search for `import { Command } from 'cmdk';` in the codebase. We want to remove all of these. In most cases, we use Command.XXX as a styled component base: e.g `const StyledGroup = styled(Command.Group)`. We want to replace it by: `const StyledGroup = styled.div`

However, we still want to have a nice user experience (especially regarding the arrow up and down behavior). To re-implement this, you can take a look at the arrow up and down behavior for SingleEntitySelect in `useEntitySelectScroll`

### PR DESCRIPTION
**Pull request by Kanav-Arora**
Closes #2495 

PR consists of following changes:
- cmdk package removed
- As cmdk.Input was removed so custom search handler added
- As discussed, toggle functionality added on `ctrl+k`

PFB walkthrough of the same

https://github.com/twentyhq/twenty/assets/62852363/11bc7e52-0a64-45b5-ad10-e905af43c97b

### CODE REVIEW

**Comment by charlesBochet** [comment]
@Kanav-Arora It looks promising. 
We are missing the following behaviors:
- when I click on an option, the option is triggered ; right now when I click on a row, nothing happens
- we should be able to browse options with arrow up and down
- we could remove the cmdk package from project dependencies in package.json

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
For adding arrow up and down functionality I was thinking of creating a state with index of focused element and use `useEffect` hook for event listener.

**Comment by charlesBochet** [comment]
@Kanav-Arora I took a look and It's actually not trivial.

We would like to do something exactly like useEntitySelectScroll but a bit more abstract so we could re-use it on any list of components. (abstract as we do for DraggableList for example)

It would be great to introduce a SelectableList that would be similar to Draggable list in the intent (provide a re-usable component) but implementing what useEntitySelectScroll is doing. 
And yes, i agree you would need to have a state to track the index of what element is selected and add listen to the keyboard using `useScopedHotkeys`

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I need some suggestions on this!

I have added the ArrowKeys for focusing on CommandMenuItems
But I'm facing two problems:
- Where should I define the scope of key in `useScopedHotkeys` for ArrowKeys and Enter
- Automatically get MenuItems in view on press of Arrow Key

**Comment by charlesBochet** [comment]
@Kanav-Arora I took a look and it looks good regarding the arrows. I think we should still:
- provide an abstract component to handle arrow selection, it could be useful somewhere else
- fix style regressions

**Comment by charlesBochet** [comment]
@Kanav-Arora @lucasbordeau I have made a proposal about an abstract SelectableItem that could be reused anywhere. I'm still unsatisfied about a few things that I need to discuss within our react team tomorrow:
- React clone to pass select state in SelectableItem. We avoid React clone per project guidelines
- RecoilStateScopedFamily family getter feels weird in the dev XP, especially when no itemId is passed or when I want to access a specific "familystate" item
- InternalEffect naming
- selectableItemIdsSelectedMapScopedFamilyState naming

**Comment by Kanav-Arora** [comment]
> @Kanav-Arora @lucasbordeau I have made a proposal about an abstract SelectableItem that could be reused anywhere. I'm still unsatisfied about a few things that I need to discuss within our react team tomorrow:
> 
> * React clone to pass select state in SelectableItem. We avoid React clone per project guidelines
> * RecoilStateScopedFamily family getter feels weird in the dev XP, especially when no itemId is passed or when I want to access a specific "familystate" item
> * InternalEffect naming
> * selectableItemIdsSelectedMapScopedFamilyState naming

Hi @charlesBochet 
Update me once you have planned.

**Pull request merged**
