### PR TITLE
feat: Custom Light Theme for Twenty

### PR DESCRIPTION
**Pull request by Khaan25**
image

### CODE REVIEW

**Comment by Bonapara** [comment]
@Khaan25 didn't see any custom theme in your file: 

CleanShot 2024-10-23 at 15 18 46

**Comment by Khaan25** [comment]
I changed the light mode directly, Do I have to create another column?

**Comment by Bonapara** [comment]
Oh, I didn't see @Khaan25. Sorry, but the changes cannot be considered a new theme. We expected something beautiful that would truly change how Twenty looks! 

e.g
CleanShot 2024-10-23 at 15 30 45
CleanShot 2024-10-23 at 15 30 10
CleanShot 2024-10-23 at 15 30 59

**Comment by Khaan25** [comment]
Ohhh. You wanted totally different color schema and UI, Got it.

I thought it should be similar to current version.
Shall I create a new PR for it?

**Comment by Bonapara** [comment]
Yes, would be awesome!

**Pull request closed without merging**
