### PR TITLE
fix: validate emails in record-fields

### LINKED ISSUE #7149: Emails doesn't follow regex pattern in table
> [!Caution]
> User can add any email without any pattern.
> On adding emails in **Companies** or **People**, the email doesn't follow any regex pattern and accepts any email.

## Current behavior

Screenshot 2024-09-19 at 6 24 07 PM
Screenshot 2024-09-19 at 6 26 49 PM

## Expected behaviour

Screenshot 2024-09-19 at 6 25 32 PM

### PR DESCRIPTION
**Pull request by sid0-0**
fix: #7149 

Introduced a minimal field validation framework for record-fields.
Currently only shows errors for email field.

image
image

### CODE REVIEW

**Review by bosiraphael — COMMENTED** [review]
Hello @sid0-0! Thank you for contributing. For validation in the front end we use zod. You can look at an example of validation in `packages/twenty-front/src/modules/settings/accounts/components/SettingsAccountsBlocklistInput.tsx`. Could you use this framework for consistency with the rest of the codebase? Thank you :)

**Comment by FelixMalfait** [comment]
@bosiraphael I think it's cool to have it on the frontend. Ideally we would also have backend driven constraints but maybe it's okay to start with that for some field types. 
Thanks for the contribution @sid0-0!

**Comment by Bonapara** [comment]
For V1, I think we should change the border to red instead of writing "invalid email" under the field. @sid0-0 can you manage that? Thanks for contributing!

CleanShot 2024-09-26 at 09 20 50

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=28562-75025&node-type=frame&t=P5326GhVoupZCaI8-11

**Review by FelixMalfait — APPROVED** [review]
Love this improvement! Thank you for your contribution!

**Pull request merged**
