### PR TITLE
multiselect for onetomany relations

### PR DESCRIPTION
**Pull request by ehconitin**
Issue #4345 
used `useUpdateRelationFromManyFieldInput` hook from `FieldInput` to `updateRelation`.
Creating a seperate hook didnt made sense when it basically does the same thing.
However renaming the hook to something generic would make sense so that its not tied to `FieldInput` according to naming convention

followup issue to tackle - #6890 

https://github.com/user-attachments/assets/452372ea-2699-45fd-9edf-ded36abdbca2

### CODE REVIEW

**Comment by Bonapara** [comment]
Awesome @ehconitin! Do you know why the checkboxes are blinking?

**Comment by ehconitin** [comment]
I think its happening because of re renders but ill dig more just to be sure.
Its happening on tables too!

**Comment by ehconitin** [comment]
flickering fixed!



https://github.com/user-attachments/assets/4744eff2-1d2e-4499-8306-9b418c92c2b2

**Review by Weiko — APPROVED** [review]
LGTM, thank you @ehconitin

**Pull request merged**
