### PR TITLE
enhance picture uploader, change justify content

### LINKED ISSUE #6966: Enhance picture uploader
# Current behavior

1. The Remove button is red
2. The label is not well positioned

CleanShot 2024-09-10 at 11 38 31

# Desired Behavior

### Buttons

The button should be secondary and set to "hug content" rather than "fill content"

Activated:

CleanShot 2024-09-10 at 11 34 51

Deactivated:

CleanShot 2024-09-10 at 11 35 23

### Label

The label should be under the buttons and not at the bottom of the container

CleanShot 2024-09-10 at 11 37 11

### PR DESCRIPTION
**Pull request by heber59**
Fixes https://github.com/twentyhq/twenty/issues/6966

to put label in the place and change remove button to gray.

sorry you dont assign this to me but I want to help, hope that if 6 hours pass u could check it

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hi @heber59 thanks! Could you please reference the issue you're solving here?

**Comment by heber59** [comment]
enhance picture uploader, change justify content #6974 
thats the issue

**Comment by FelixMalfait** [comment]
So #6966 - thanks

**Comment by heber59** [comment]
oh sorry, next I'll put it correct

**Review by lucasbordeau — APPROVED** [review]

**Pull request merged**
