### PR TITLE
Added Side Panel compact header

### PR DESCRIPTION
**Pull request by ehconitin**
Fixes issue #6487 
Added a new prop, `isInRightDrawer` to both the `ShowPageSummaryCard` and `ShowPageRightContainer` components. This prop allows for different styles to be applied based on the specific needs of the drawer..

Rather than creating a new component, I opted to add this prop to avoid code duplication. However, if you would prefer a separate component for this functionality, I'm happy to make that adjustment—please just let me know!

Also added  `box-sizing: border-box` to `ShowPageSummaryCard` to make sure it aligns with figma designs.

https://github.com/user-attachments/assets/38e8d85e-55d5-471e-884a-11c67467f56f

### CODE REVIEW

**Comment by FelixMalfait** [comment]
You're on fire @ehconitin!

**Comment by FelixMalfait** [comment]
Great work!
- It's nice so I feel like we also want this when it's in mobile display, not just in right drawer mode
- I find it nice that you leveraged the existing component and didn't create a new one.
- It was an interesting idea to try to wrap the rich text editor into a grey property box, but I think we want to stick to having a full width/full height text. Even better would be if you can click anywhere on the zone up until the bottom (on show page or in right-drawer mode) and you would always get the pointer to be focused upon click, being able to write directly even if you clicked at the bottom of the drawer

**Comment by ehconitin** [comment]
> It's nice so I feel like we also want this when it's in mobile display, not just in right drawer mode

U mean in the left summarycard and fields?

image

this one? this should be easy.

> I find it nice that you leveraged the existing component and didn't create a new one.

Your reviews helped alot!

> It was an interesting idea to try to wrap the rich text editor into a grey property box, but I think we want to stick to having a full width/full height text. Even better would be if you can click anywhere on the zone up until the bottom (on show page or in right-drawer mode) and you would always get the pointer to be focused upon click, being able to write directly even if you clicked at the bottom of the drawer

So should the grey box be in full height and width ? And if yes just for TextEditor right?

**Comment by FelixMalfait** [comment]
> U mean in the left summarycard and fields?

Yes, I meant that you only display this compact header when in right drawer. But usually the right drawer view ~ the mobile view. There's no reason to deprive our mobile user from this beautiful compact header, we should also show it in that context :)

We already do things like  `const isMobile = useIsMobile() || isInRightDrawer;`  (maybe naming could have been better to reflect that it's mobile OR right drawer)

> So should the grey box be in full height and width ? And if yes just for TextEditor right?
I think for rich text we shouldn't even have a grey box, I like how it is today:

Screenshot 2024-08-07 at 08 35 05

The only thing I don't like with how it is today, is that if you click at the bottom of the white zone, it doesn't automatically focus your cursor on the text zone (like it would in Google Docs or Notion for example)

Thanks!

**Comment by ehconitin** [comment]
Got it!

**Comment by ehconitin** [comment]
Hi @FelixMalfait ,

I've made the changes based on your review.

Regarding the prop naming, what do you think about using `isMobile` for the header? If you have any other suggestions that might improve code readability, I'd love to hear them.

> The only thing I don't like with how it is today, is that if you click at the bottom of the white zone, it doesn't automatically focus your cursor on the text zone (like it would in Google Docs or Notion for example)

 I'll address this behavior in the indent bullet points issue.

I've also fixed the bug where empty icons were not being rendered in the center.  (refer video):


https://github.com/user-attachments/assets/358cc8b3-4cdf-49ab-adc9-3df70f448ffc


Here is how the code behave after this changes:

https://github.com/user-attachments/assets/40e50c87-b35d-4d9d-b32c-c60887c845d4


Let me know your thoughts!
Thanks

**Review by FelixMalfait — APPROVED** [review]
Great work!!!

**Pull request merged**
