### PR TITLE
added settings page load fallback on route change

### LINKED ISSUE #7102: The settings flash during loading
# Current behavior

The Settings page flashes on load.

https://github.com/user-attachments/assets/6cdbe08c-79ff-44f5-b211-c5297298154c

# Desired Behavior

The White background layout should always be loaded and not flash on every page change. We should put a small Skeleton to indicate the page loading. The breadcrumb should not be part of the loading and already displayed (if possible).

image

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40069-430620&node-type=frame&t=vjg6Ofev4bkaijG1-11

# Techical guidelines

@lucasbordeau

### PR DESCRIPTION
**Pull request by Muralidhar22**
Closes: #7102 
### After Change:
Screenshot 2024-09-24 at 12 04 36 AM

### CODE REVIEW

**Comment by ehconitin** [comment]
@Muralidhar22 Nice! Thanks for contributing!
The page header skeleton seems to be misaligned, could u fix it? :) (it should be top left as shown in your screenshot)
Also make sure you match skeleton styles from figma designs ;)

Screenshot from 2024-09-24 10-19-43

**Comment by ehconitin** [comment]
@charlesBochet Could you confirm if this approach is correct? I believe you [mentioned](https://github.com/twentyhq/twenty/issues/7102#issuecomment-2370369592) it was related to caching the layout?

**Comment by Muralidhar22** [comment]
@ehconitin am drafting this PR for now

**Comment by ehconitin** [comment]
@Muralidhar22 are you still working on it?

**Comment by Muralidhar22** [comment]
@ehconitin no, Can I close this PR?

**Comment by ehconitin** [comment]
@Muralidhar22 Yes you can, thanks!

**Pull request closed without merging**
