### PR TITLE
Improve performance of demo workspace

### LINKED ISSUE #3514: Improve performance of demo workspace
In demo workspace we are storing 1000+ image as base64 in the DB.
This slows down the database and we need to move to another solution (use a profile pic generator website and link to these urls, host our own images on S3, etc.)

### PR DESCRIPTION
**Pull request by gitstart-twenty**
### Description

1. We've created another PR [here](https://github.com/twentyhq/placeholder-images/pull/1) here that adds the placeholder images to the `placeholder-images` repo

2. For now, [pages](https://github.com/twentyhq/placeholder-images/settings/pages) is deploying to the `TWNTY-3514` on `placeholder-images`. If the PR is merged, we'll need to update [pages](https://github.com/twentyhq/placeholder-images/settings/pages) to deploy from `main`

### Refs

- #3514
- https://github.com/twentyhq/placeholder-images/pull/1

### Demo

https://github.com/twentyhq/twenty/assets/140154534/88fa6cc1-a84d-48d4-9b17-e3a29bd9d1d0

Fixes #3514

### CODE REVIEW

**Comment by gitstart-twenty** [comment]
### How to set up the demo workspace locally

1. Go to the `.env` file in the `twenty-server` package and look for the line `# DEMO_WORKSPACE_IDS=REPLACE_ME_WITH_A_RANDOM_UUID`
2. Uncomment the line and replace `REPLACE_ME_WITH_A_RANDOM_UUID` with a random UUID4 string
3. Run the command `yarn nx run twenty-server:command workspace:seed:demo`
4. You should now be able to log in with any of the seed demo users
   1. Refer to `packages/twenty-server/src/database/typeorm-seeds/core/demo/users.ts` for the user's credentials

**Comment by FelixMalfait** [comment]
Thanks!

1. For the 6 prefilled objects since those are famous people, could you please keep the original base64 image? (but fetch it from the url / host them on the repo you created). Note, we need to make sure never to delete this url since now these urls will be hardcoded for each new workspace creation @charlesBochet 

2. Could you please look into why it's not displayed in chips? 
Screenshot 2024-07-10 at 14 11 30
Screenshot 2024-07-10 at 14 12 01

3. Since we want to discourage using base64 coming from the database, I'd advocate renaming `getImageAbsoluteURIOrBase64` to `getImageAbsoluteURI` and removing the possibility to load it via base64 (cc @charlesBochet let us know if you disagree)

**Comment by gitstart-twenty** [comment]
Hello @FelixMalfait 👋 

The problem with the chips happens with these files, here is the trace:
`useLoadRecordIndexTable`  => `useRecordTableRecordGqlFields` => `useRecordTableRecordGqlFields` => `getObjectMetadataIdentifierFields`

Inside `getObjectMetadataIdentifierFields` the `imageIdentifierFieldMetadataItem` is `null`, because none of the fields pass the `.find` check, and this happens because `objectMetadataItem.imageIdentifierFieldMetadataId` is `null`. and this causes the Graphql query not to add the `avatarUrl` key on the request.

It's seems this property is should be added in the backend when these fields are created, or when the data model itself is created, but in the case of the demo data, it doesn't happen since they have their own creation flow in the database. considering this only happens in the demo workspace, is this also happens on the production app?
Could you give us more context about how objectMetadataItem.imageIdentifierFieldMetadataId is handled by the server?


About renaming the function, there are 3 images that still use base64 (company logo images), and they are also passed to the function, if we remove the possibility of loading it via base64, it will not be possible to load these images, should we add these images to the placeholder repo too?
image

**Comment by charlesBochet** [comment]
I have taken a look to this one:
- if we add the right imageIdentifierFieldMetadataId to person object, it does display the image:
image
==> so I let's wait for @Weiko to fill the imageIdentifierFieldMetadataId and it will fix the issue. LGTM for this PR

- Regarding the new worskpace data prefill (not the demo one), let's do the same (and I see you have done it in your PR). LGTM

- Regarding the last issue which to deprecate the getImageAbsoluteURIOrBase64, let's also upload it on our new placeholder pages and agree with @FelixMalfait that we can remove the base64 possibility which does not seem to be a good pattern

**Review by charlesBochet — APPROVED** [review]
LGTM, merging
@gitstart-twenty could you take care of the workspace logo base64 in a follow-up PR?

**Pull request merged**
