### PR TITLE
Allow input and display of floats for Number fields

### PR DESCRIPTION
**Pull request by ijreilly**
All our number fields so far only allow for saving and display of integers (through the product), while in the db they can actually handle floats.
Let's change that

### CODE REVIEW

**Comment by charlesBochet** [comment]
@ijreilly I have discussed with @Bonapara 

The vision is to introduce a setting on fieldType of type 'NUMBER'.
NumberFieldTypeSetting {
   decimals: number
}

(saying decimals but maybe precision is a better naming)

He is working on a design. By default we want to keep decimals to be 0.

Proposal while waiting for design is to:
1. introduce the NumberFieldTypeSetting in the backend (we already have the column) and make sure this is sent to the FE in /metadata call
2. in the FE leverage this setting, add a decimal parameter in castAsNumberOrNull and canBeCasted as number or null
(For later: 3. I think we need to add it to the FieldMetadataDecorator too + to the field creation process)

I think in this PR we can introduce 2 only

**Comment by ijreilly** [comment]
@charlesBochet thank you ! 
I am curious about how this works in other CRMs. Maybe I am biased by excel usage (in a previous life) but I would expect to be able to change this setting on the table view directly, to be able to round the value for view's convenience while keeping the exact value stored (for calculation purposes for instance). 
I am aware we don't have this kind of mechanism yet in the table views though

**Comment by Bonapara** [comment]
@ijreilly I think this case is about what we store, such as whether you can store a 3-decimal number or are limited to integers, rather than what the user sees. So, it makes sense to include it in the data model. 

Interesting point about customizing the display. I'm sure we will introduce some options for display customization at some point.

Here is the design! The middle part is an input, and the - and + buttons are simple icon buttons.

image

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-127971&node-type=FRAME&t=VDLWWLoDs8y1H2Gj-11

**Comment by charlesBochet** [comment]
@Bonapara we will actually always store Float:
- so we don't have to migrate data when user changes the number of decimals
- so the user gets back its decimals if they change their mind

So @ijreilly is right : this is about display and data validation mostly. However, I feel this should still be in the Settings as we want all occurences of this field to be formatted in the same way, this is not view related to me

**Comment by ijreilly** [comment]
@charlesBochet not sure to fully follow here

"so the user gets back its decimals if they change their mind" / "this is about display and data validation mostly"
If we run data validation on this field type (which I understand as: it's not possible in the product nor through the api to persist a value with two decimals if the setting is set to 0 decimal), it's not possible to get your decimals back as you were never allowed to persist them ? 

Let's say we have set the number of decimal to 0, but then input the value 2.6
Are we expected to
1.  round the input value to the expected number of decimals: we persist and display 3. But then you can never get back to your decimals, the 2.6 is lost. 
or
2.  to reject the input value if it exceeds the limit of decimals (we don't persist anything) 
or 
3. always persist the input value if it's a number (so 2.6 is persisted) but display the value according to the decimal settings (so we display 3)
?
@Bonapara

**Comment by charlesBochet** [comment]
@ijreilly I was thinking about the user changing the settings.

Scenario:
- field is configured to accept 3 decimals
- user enters some data
- user change the field to accept 0 decimals
- user change its mind and get back to 3 decimals

I think we should keep the data as float and don't care about the decimals in storage. Only care about it while validating and displaying it

**Comment by charlesBochet** [comment]
The only drawback we could have is that float have a limited precision that could lead to inaccuracy while doing operations of them. That's why we store currency amount in micros (integer not a float) because the precision of computation is important there. 

I think it should be a known limitation of number field to be subject to floating rounding errors

**Comment by ijreilly** [comment]
Closing this, check out issue https://github.com/twentyhq/twenty/issues/6987

**Pull request closed without merging**
