### PR TITLE
feat: Develop a script to facilitate the migration of data from another CRM to Twenty

### PR DESCRIPTION
**Pull request by Khaan25**
Develop a script to facilitate the migration of data from another CRM to Twenty (750 points)

I had to write a script to add data to HubSpot CRM :)
I wrote migration script to move data from HubSpot --> Twenty.

Here's the GitHub [Repo](https://github.com/Khaan25/twenty-migration-script) - Video attached in files

Hope it will be beneficial for people and Twenty Community :)

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
Thank you @Khaan25, I have taken a look at the video and the repo, hope it will help :)

**Comment by Khaan25** [comment]
@charlesBochet, Can I create another script as well? for salesforce maybe?

**Comment by charlesBochet** [comment]
It's up to you! It's likely to be too late for oss.gg though

**Pull request merged**
