### PR TITLE
Update SettingsObjectAboutSection.tsx changed "Disable" CTA to "Deact…

### PR DESCRIPTION
**Pull request by selango1**
changed "Disable" CTA to "Deactivate"

### CODE REVIEW

**Comment by bosiraphael** [comment]
Hello @selango1, thank you for your contribution. Another change is mentioned in #4153: rename "Disabled" sections to "Inactive". Could you also add this to your PR ? Thank you very much :)

**Comment by selango1** [comment]
I am assuming you meant Disable drop down to Deactivate, which are the changes I made in this file  SettingsObjectAboutSection.tsx

**Comment by charlesBochet** [comment]
@selango1 Really appreciate the help :)

You have opened 5 PRs:
- https://github.com/twentyhq/twenty/pull/4175 (this one)
- https://github.com/twentyhq/twenty/pull/4179
- https://github.com/twentyhq/twenty/pull/4186
- https://github.com/twentyhq/twenty/pull/4188

regarding the following ticket: https://github.com/twentyhq/twenty/issues/4153

It makes it very hard to review as missing parts might be in other PRs.

Let's keep only this one, I will close the other ones. Could you cherry-pick (I think it's the best way) your other commits into this one so we have 1 PR and we can test it and review it?

**Comment by selango1** [comment]
Hi, so this is the first time I am cherry picking so I am not sure If I did it right.
git checkout e599a13d56b197b632cdfc449ce441efe0fae117
git cherry-pick deed812cc60836590eee94826ec62ff4c97be77a
git cherry-pick d77d05a4a162b754fa71a01494b56c1f7de1d2dc
git cherry-pick b0a224632cdb18e05e5727e363b3fe209fc15dd2

git cherry-pick 6a46cc0f3ee027a1334822af2d8ab520a509579 (last one: Update SettingsObjects.tsx #4188)
while merging this I am getting merge conflict, Is it because Its the same file that I edited twice?

**Comment by bosiraphael** [comment]
Hello @selango1, the tests are broken because of some typescript and lint issues.
Tell me if you need any help :)

**Comment by selango1** [comment]
I changed the dropdowns, please try again.

**Comment by selango1** [comment]
> Hello @selango1, the tests are broken because of some typescript and lint issues.

how can I effectively change the file name without running into error, next time it is testes? Is there a way to find other files that import SettingsObjectInactiveMenuDropDown.tsx  ?

**Review by thomtrp — APPROVED** [review]

**Pull request merged**
