### PR TITLE
Uploading img assets in view of read-me visual update

### PR DESCRIPTION
**Pull request by Bonapara**
One asset (preview-light.png) has been replaced

12 other assets have been uploaded. Coming next: a PR to update the Readme to the new Twenty branding style

Screenshot 2024-02-16 at 11 17 31

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Cool! I think "_gather_ your email", "create _some_ tasks" and "in a sleek looking design" could probably be improved

Here are some suggestions - which you can discard if you disagree!

"Explore your data
With advanced sort and filtering"
"Sync your emails
To share them with your team"
" Capture notes
With a (block-based) rich text editor"
"Schedule tasks
On any record"
"Navigate with keyboard
Through cmd+k and shortcuts"

In the future it would be nice to have something on developers and data modelling tabs!

**Comment by Bonapara** [comment]
Updated! Thanks for the feedbacks

**Comment by charlesBochet** [comment]
@Bonapara we should avoid using case sensitive file names for static assets. Some OS are case sensitive, and some are not this will likely result into issues + poor dev experience as most git config are not taking the case into account properly.
Could you rename the files to be in lowercase?

**Review by charlesBochet — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
