### PR TITLE
fix: New Relation Design hot fix

### PR DESCRIPTION
**Pull request by harshit078**
## Description

- This PR solves the issue #7353 

- [x]  Improved layout for mobile and desktop

-    [ ] Added tooltip on hover

### CODE REVIEW

**Comment by ehconitin** [comment]
@harshit078 its still broken, Ill suggest to use useIsMobile hook instead!

https://github.com/user-attachments/assets/342ae391-9952-46f6-91d2-3f195ae1aa98

**Comment by ehconitin** [comment]
@Bonapara we should merge this right? since its broken on main branch

https://github.com/user-attachments/assets/cc0fcbb4-fc26-4246-8384-e6497f99ef17

**Review by ehconitin — APPROVED** [review]
LGTM!

**Comment by Bonapara** [comment]
On mobile, we could display the relation type above the object destination to prevent the text from being cropped.

**Review by FelixMalfait — APPROVED** [review]
Thank you!

**Pull request merged**
