### PR TITLE
[Enter] key autosave for new API key and webhook

### LINKED ISSUE #3928: In settings I should be able to press "enter" instead of clicking "save"
When I create a webhook or an API key, I would like to be able to press "enter" to move to the next step instead of having to use the mouse.

Screenshot 2024-02-13 at 12 15 14

Screenshot 2024-02-13 at 12 15 25

There's also the issue here - although it's a bit more dangerous since we have a multi-line text field and that we can't erase an object that's been created. I still think we should implement it here too for consistency.

Screenshot 2024-02-13 at 12 14 22

### PR DESCRIPTION
**Pull request by Jonathanlemon**
Added functionality for onKeyDown for new webhook and new API key, to save when the user presses the [Enter] key

Fixes #3928

### CODE REVIEW

**Review by charlesBochet — APPROVED** [review]
LGTM, thank you :)

**Comment by charlesBochet** [comment]
@Jonathanlemon The linter is failing, could you fix it? 
`nx run lint:ci twenty-front` to run it

**Review by Jonathanlemon — COMMENTED** [review]
Updated to follow best practices via the linter

**Comment by charlesBochet** [comment]
@Jonathanlemon still some issues :)

**Review by Jonathanlemon — COMMENTED** [review]
Got rid of the extra space to hopefully pass linter.

**Comment by charlesBochet** [comment]
@Jonathanlemon Please run locally: "yarn nx lint:ci twenty-front". You'll likely keep having issue if you don't run it ;)

**Comment by FelixMalfait** [comment]
Fixes #3928

(fyi @Jonathanlemon best practise to add this to your PR so that it's linked to the issue and get closed automatically once PR is merged)

**Pull request merged**
