### PR TITLE
Fix/1734/selecting and releasing mouse

### LINKED ISSUE #1734: Selecting and releasing the mouse outside of an edit mode cell closes it
## Bug Description

When we open a cell with an input (for example email) and we select the text, and the mouse up event ends up outside of the input, the cell is closed.

https://github.com/twentyhq/twenty/assets/26528466/5a58f7d1-501e-436a-94a9-6b95c53ed94d

## Expected behavior

We want this to be avoided for those specific inputs. We shouldn't modify the useListenClickoutside, but instead find a way to have the right events listened.

Maybe use onMouseUp or ouMouseDown on GenericCellEditMode ? 

The fix shouldn't break existing behaviors, ensure for example that a click outside of a cell doesn't open another cell directly, the first click outside should only exit the edit mode of the current cell.

### PR DESCRIPTION
**Pull request by abhithory**
Fixed #1734 

## OnMouseDown and onMouseUp Flow:
- When we click on any input box (cell ) then onMouseDown is called
- And then if we leave the mouse in that input box then onMouseUp is called
- but if we leave the mouse outside the input box then onMouseUp is not called

## How i fixed:
- Setting `isOutsideMouseReleased.current` true in onMouseDown and then setting false it in onMouseUp
- it means if the user leaves the mouse outside the input box then `isOutsideMouseReleased.current` will be true
- then based on this we are calling the outsideclick function (whether it is clicked outside or not)
- then after that, we are again setting `isOutsideMouseReleased.current` false

 
[Screencast from 09-10-23 02:31:35 AM CDT.webm](https://github.com/twentyhq/twenty/assets/76877003/76ebc75a-1223-4de8-a47c-ccf5afd40519)

### CODE REVIEW

**Comment by abhithory** [comment]
Hi @charlesBochet @lucasbordeau , can you please review this?

**Comment by charlesBochet** [comment]
@abhithory sorry about the slow review, I will do it tomorrow, I promise!

**Comment by abhithory** [comment]
@charlesBochet , no problem. Take your time

**Comment by lucasbordeau** [comment]
@tomalexing @abhithory actually, we could think of a new property `skipIfMouseDownInsideButMouseUpOutside` on `useListenClickOutside`.

@tomalexing could you help on this PR ? We shouldn't refactor the other places you mentioned though, but feel free to open another PR to do it on Dropdowns.

@abhithory We don't allow useRef as state management in our codebase.

**Comment by charlesBochet** [comment]
@abhithory Thanks a lot for the PR. This has triggered a discussion on how we should handle this case and we have decided to go with the following implementation: #2434. I'm closing this PR, thanks again for the help, really appreciated

**Pull request closed without merging**
