### PR TITLE
feat: enable generic oidc signin

### PR DESCRIPTION
**Pull request by xanderio**
This PR is currently untested and just a "simple" search and replace based on #5103.

I think I've got everything that's need to enable generic OIDC support in twenty, but until I test this it's just a speculation :D

I'm looking forward to reviews :)

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Hey @xanderio thanks a lot for the effort!

We'd like to build SAML/OIDC support not as a server-level/environment variable config, but instead something that's dealt with at the workspace level, where each workspace is able to configure its own auth individually. We actually planned to start working on it this week (@AMoreaux will take care of it)

Also, we've always been transparent on the fact that SSO would probably be our main leverage to monetize entreprises long-term. We need to find ways to build a great sustainable business to fund Twenty's development, and it seems sso is a great proxy to separate "big corporation that can afford to pay" from smaller businesses. So this will most likely be under a different license, maybe with ways for smaller companies or non-profit entities to have access to it freely - we still haven't figured out the detail and need to find the right balance. 

I'm sorry to close the PR, it's not something we usually do. Happy to chat over a call if this decision doesn't make sense to you!

**Comment by gotjoshua** [comment]
> smaller companies or non-profit entities to have access to it freely - we still haven't figured out the detail and need to find the right balance.

oh, i really hope so. we are a small non profit running our own nextcloud, and would be cool to be able to use that for OIDC!

**Comment by FelixMalfait** [comment]
@gotjoshuay we'll release it publicly in December (still running some tests now). You can just use any value in the entreprise key env variable it'll work for now, until we figure out the right program (no doubt your use-case should be covered)

**Comment by gotjoshua** [comment]
> no doubt your use-case should be covered

@FelixMalfait  i think this isn't really the right place to track this,  so please let me know if i need to open an issue or use the [merged PR #7246](https://github.com/twentyhq/twenty/pull/7246) or ?

so far:
 i can get access to the SSO config by running the server and frontend prefixed with the env var:
`ENTERPRISE_KEY=foo npx nx start twenty-server`

then in settings/security i see the ui and can add a oidc provider 
behind the scenes, twenty calls the our.server/.well-known/openid-configuration  (via the openid-client lib discover(uri) fx ) 

after adding the oidc provider in the security settings for a workspace:
1. logging out and in does NOT show the provider
2. does not show up after logout and login, but if i add it again it shows up twice (so seems to be in db but not loaded at first)
3. switching away and then back to the workspace, does show the provider but clicking it sends me to:
http://localhost:3001/undefined/auth/oidc/login/8a608255-fa87-43b1-901d-1ea39d99cdab)
 instead of going to the correct login url 

so it seems i am on the right track but its not quite ready yet

**Comment by FelixMalfait** [comment]
Sorry, the public release is planned for December, @AMoreaux is on it

**Pull request closed without merging**
