### PR TITLE
Blocknote custom slash menu

### PR DESCRIPTION
**Pull request by brendanlaschke**
Bildschirmfoto 2024-03-17 um 22 41 04

First step for #3518 - maybe we want to do the nesting later ? 

also updated blocknote to v12 & cleaned up the block specs/schema with the types of the new version.

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Brendan striking again. Really cool!!! cc @Bonapara

**Comment by Bonapara** [comment]
Amazing @brendanlaschke🤩

**Comment by FelixMalfait** [comment]
I just tried it locally, file upload works but image doesn't (no backend request). Is it the same for you? Something I missed @brendanlaschke?

**Comment by brendanlaschke** [comment]
Seems like its the same for me, but also #4160 logged that - so I didn't brake it :D 
Will open an issue at blocknote for this as the version upgrade din't resolve this.

**Comment by FelixMalfait** [comment]
Ah I didn't see that issue! Let's merge it like this then. Thanks again!

**Review by FelixMalfait — APPROVED** [review]

**Pull request merged**
