### PR TITLE
[FIX] Text overflow on timeline

### LINKED ISSUE #6977: [bug 🐛 ]: Tasks with longer body overflows in Timeline summary
## Bug Description

This issue is related to the already existing issue #6968.

- when a task with long title and body, it makes timeline summary scrollable.

## Current behaviour

Screenshot 2024-09-11 at 1 22 21 PM

https://github.com/user-attachments/assets/992c8b7a-04b2-4550-bcab-1f6e9706bf95

## Expected behavior

Screenshot 2024-09-11 at 1 21 58 PM

### PR DESCRIPTION
**Pull request by siv-io**
FIX: #6977 

Implementation:

1. Parent (Summary componenet) width is set to 100%. (dosen't grow even if the child exceeds width)
2. span element is set to `text-overflow: ellipses` when overflown.

### CODE REVIEW

**Comment by Bonapara** [comment]
Looking good! Can you check why some values are not taking the full width? 

CleanShot 2024-11-05 at 14 55 59

**Comment by Hitarthsheth07** [comment]
Is there a bug with the timeline? 

https://www.loom.com/share/de72e092dc024af89e27f0ff2d334ae3?sid=2b14e0f7-4731-4e33-a584-b180942388f0

**Comment by Bonapara** [comment]
I had the same problem @Hitarthsheth07 but running the worker solved my issue: `npx nx run twenty-server:worker`

**Comment by Hitarthsheth07** [comment]
> I had the same problem @Hitarthsheth07 but running the worker solved my issue: `npx nx run twenty-server:worker`

Gotcha!

**Comment by Bonapara** [comment]
> > I had the same problem @Hitarthsheth07 but running the worker solved my issue: `npx nx run twenty-server:worker`
> 
> Gotcha!

Did it work?

**Comment by Hitarthsheth07** [comment]
@Bonapara 

The latest commit fix the problem you mentioned. 

However, some components still overflows when the size shrinks... 
Should I open a new issue for this? 

https://www.loom.com/share/159d5c3a376641c2b162fecfbd116be0?sid=3184e459-38bd-43f0-84c8-699be4cdd7ae

**Comment by Bonapara** [comment]
Yes, please @Hitarthsheth07! Good observation

**Comment by Hitarthsheth07** [comment]
> Yes, please @Hitarthsheth07! Good observation

Sure, you can merge this if you want.

**Review by FelixMalfait — APPROVED** [review]
Great thanks!

**Pull request merged**
