### PR TITLE
Update Blocknote

### PR DESCRIPTION
**Pull request by brendanlaschke**
Updates block note to add images via url and tables. Also fixes line breaks in the note preview.

 
Bildschirmfoto 2023-12-08 um 08 54 18

### CODE REVIEW

**Comment by bosiraphael** [comment]
Hello @brendanlaschke, thank you very much for contributing.
I found a few bugs while testing your PR:
- Adding an image in the first block throws an error


https://github.com/twentyhq/twenty/assets/71827178/a1d619a2-b156-4370-89ae-0da9d7af916a



- Resizing after selecting and moving the image throws an error


https://github.com/twentyhq/twenty/assets/71827178/dc554af0-f218-4a6d-b62b-1233d7c29b6e



- We can add an url which doesn't point to an image. I think we should only allow some specific file types : jpg, jpeg, png, webp, sgv, gif ...


https://github.com/twentyhq/twenty/assets/71827178/e5351283-369f-4400-9d6c-a1336c58b2cd

**Comment by brendanlaschke** [comment]
@bosiraphael We could look into the errors, but I changed nothing but the block note version :) and fixed some changed properties. Everything you see is default behavior of block note - everything on top would have to be a custom block/content/? ... 

I will create a issue for 1 and 2 at https://github.com/TypeCellOS/BlockNote ... good catch I tested a bit but not in this depth ;) 

For 3 we would need to create a custom version of the ImageBlock

**Comment by brendanlaschke** [comment]
https://github.com/TypeCellOS/BlockNote/issues/472

**Comment by charlesBochet** [comment]
@brendanlaschke For 3, could we also create a ticket on BlockNote?

Lastly, could we put a Feature Flag in place (see IS_MESSAGING_ENABLED on main for example). This will allow us to progressively deploy the feature! Then we will be able to merge without breaking the latest version, even if BlockNote hasn't fixed the issues yet

**Comment by brendanlaschke** [comment]
If I think a bit more about 3 im not sure if I like the idea:

What if I have an api to generate an image with an url like: https://ui-avatars.com/api/?background=0D8ABC&color=fff
This wouldn't work with such constraints to the url. I think we should allow the user at this point some freedom even if sometimes it can be quite ugly with the image missing icon ...

**Comment by bosiraphael** [comment]
@brendanlaschke you're right about 3. Maybe we should leave it as it is for now.

**Review by charlesBochet — APPROVED** [review]
Let's merge it as it's behind a feature flag and the code is clean :)
Thank you @brendanlaschke, always there to enhance the product!

**Pull request merged**
