### PR TITLE
update example docker-compose to bitnami postgres path

### PR DESCRIPTION
**Pull request by theRealWardo**
it appears the twenty postgres is based on a bitnami postgres that has a different pgdata dir than the one in the example.

just wanted to update this so that other people are aware!

### CODE REVIEW

**Comment by theRealWardo** [comment]
actually this isn't quite it. please hold off on reviewing this 😞

**Comment by theRealWardo** [comment]
the tldr is that the bitnami postgres is not easy to configure to persist data to a volume locally. the existing documentation makes it seem that the container will indeed persist data to the volume, but it doesn't.

rather than leaving this slightly mis-leading volume & mount, maybe just remove it and leave a note? not sure what the community feels is best here.

**Comment by charlesBochet** [comment]
Good point, we should maybe be more explicit:
- docker volume works if you are stateful on your own server
- maybe give some hints on how to do that on stateless arch on AWS (Elastic Block Store) or Azure (Persistent volumes?)

**Comment by FelixMalfait** [comment]
Thanks! Let's add this disclaimer, I agree it can be useful
I'll still keep the volumes in the docker compose because as Charles mentions, it can still be useful if your server is stateful

@Freebios will upgrade the docker-compose/dockers soon and it should become much more clear than it is today :)

**Review by FelixMalfait — APPROVED** [review]

**Pull request merged**
