### PR TITLE
Prevent indexing on docs outside of production

### LINKED ISSUE #550: Generate robots.txt through CI for documentation when env != prod
URLs such as docs-dev.twenty(dot)com are getting indexed by search engines
Instead we only want docs.twenty.com to be indexed

### PR DESCRIPTION
**Pull request by emilienchvt**
This PR closes https://github.com/twentyhq/twenty/issues/550

Following the [google documentation](https://developers.google.com/search/docs/crawling-indexing/robots/intro), robot.txt is not the preferred way to prevent a page from being indexed, instead they recommend using [`noindex` meta tags](https://developers.google.com/search/docs/crawling-indexing/block-indexing).

This is also what docosaurus recommends [from their doc](https://docusaurus.io/fr/docs/next/seo#robots-file). And they have a specific [config item](https://docusaurus.io/fr/docs/next/api/docusaurus-config#noIndex) that can be leveraged to serve our purpose.

### CODE REVIEW

**Review by charlesBochet — COMMENTED** [review]
Good point, see comment above

**Comment by FelixMalfait** [comment]
@emilienchvt much better idea than original proposal! Thanks!

**Comment by emilienchvt** [comment]
Added the env variable management.
The `SHOULD_INDEX_DOC` param is well setup in the infra repo and for the docs build, see output of the intermediary log here (see this commit https://github.com/twentyhq/twenty/pull/1054/commits/58ee111e86042a27946d834a082c980edd0a1797 for the log statement):
Screenshot 2023-08-07 at 14 19 53

These commits implement the variable passing on the infra side: https://github.com/twentyhq/twenty-infra/commit/91f548c97884bacb08ddc67d19b435eaea8c3ee2 https://github.com/twentyhq/twenty-infra/commit/e59b4dd0293ebd68d626040cd970c9a70ba9ef04

**Review by charlesBochet — APPROVED** [review]

**Comment by charlesBochet** [comment]
LGTM, I've checked on docs-main
image

**Pull request merged**
