### PR TITLE
Feat: Adjust the overlay style for changing the phone number's country

### LINKED ISSUE #1505: Adjust the overlay style for changing the phone number's country
# Current design:

### Cell editable mode:
when you click to modify the cell, the flag has no hover

https://github.com/twentyhq/twenty/assets/102394218/fdb85275-29aa-4262-b2b4-c8225e81115b

### PickerMenu 

Currently, the picker component's design does not adhere to the Twenty style guidelines. It lacks the following key design elements:

- The appropriate background color.
- Correct font.
- Correct border and hover effects.
- A selected state.

Image

# Expected design

### Cell editable mode:
add a hover transparent light

Image

### PickerMenu 

Adjust the design to align with the Twenty style. (Picture below)
if possible add flag, telephone index and a search.

Image

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=7184-122423&mode=design&t=aiEVp36gXiI1JZeu-4
```[tasklist]
### Tasks
- [ ] Right now, the phone input from libphonenumber-js is displaying a native dropdown. We should hide this existing dropdown (I'm not sure it's possible with the given API, we can use CSS if not)
- [ ] Introduce a new PhoneCountry Picker using MenuItemSelect and MenuItems
- [ ] Connect this picker to the existing input: we should update the country once selected and update the county once a format is detected
```

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
Closes #1505 

- Implement Country Code select component for PhoneInput.

https://github.com/twentyhq/twenty/assets/54364088/3b80bddf-0856-4329-94de-543fc8fd9cba

### CODE REVIEW

**Review by lucasbordeau — COMMENTED** [review]
We should use the generic DropdownButton component we have for this use case.

**Comment by AyushAgrawal-A2** [comment]
@lucasbordeau 
Done

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 Please use `DropdownMenu` component with the associated `useDropdown` hook.

**Comment by AyushAgrawal-A2** [comment]
@lucasbordeau 
Done

**Review by charlesBochet — APPROVED** [review]
This is awesome. I don't have much to say!

Congratulations: this PR is the 1000th we are merging!

**Pull request merged**
