### PR TITLE
Eslint prevent duplicate import

### LINKED ISSUE #2515: Find a plugin / eslint-rule or anything that can prevent vscode to add duplicate imports automatically
## Scope & Context

VSCode can import automatically anything that is missing in imports that we use in the code.

## Technical inputs

Right now we have a lot of issues with this feature, it imports two times or more the same missing function / hook and we have to manually remove the duplicates.

Example : 

```ts
import { Key, Key } from 'ts-key-enum';
```

We can create our own rule in the package `eslint-plugin-twenty`, it should auto fix this problem.

### PR DESCRIPTION
**Pull request by brendanlaschke**
Pack every import from the same library on one line only.

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Sorry I should have been more clear in the issue, I completed it with an example : 

```ts
import { Key, Key } from 'ts-key-enum';
```

**Comment by lucasbordeau** [comment]
But we can also merge this improvement which is useful as well.

**Comment by brendanlaschke** [comment]
Then I think we have to write our own rule ... I don't think this is available for this special use case

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
I'm merging this one.

**Pull request merged**
