### PR TITLE
fix: API ObjectMetadata labelSingular and labelPlural which eventually solves typo in dropdown

### LINKED ISSUE #7478: Typo in Settings > Advanced > API & Webhooks > webhook details
**Scenario:**
1. Log in
2. Go to Settings
3. Turn on Advanced settings
4. Go to API & Webhooks > webhook details
5. Click on first dropdown in Filters section

**Actual:** There is `Api key` option
image

**Expected:** There must be `API key` option

### PR DESCRIPTION
**Pull request by Nabhag8848**
## ISSUE 

- Closes #7478 

## Description 

- Fixes typo in dropdown + in general any apikeys label around.

### CODE REVIEW

**Comment by Nabhag8848** [comment]
@CoreTeamTwenty

**Comment by charlesBochet** [comment]
@Nabhag8848 LGTM but you have conflicts, could you solve them?

**Comment by Nabhag8848** [comment]
@charlesBochet 🙌🏼

**Review by charlesBochet — APPROVED** [review]
LGTM

**Comment by ketanMehtaa** [comment]
@Nabhag8848 are these changes working in frontend ?

**Comment by Nabhag8848** [comment]
@ketanMehtaa  yes, we are storing in database, you need to run database:reset command to have updated records.

you can see this under metadata database, objectMetadata table.

**Pull request merged**
