### PR TITLE
Added "Select an option" as default none selector on Workflow Visualizer

### LINKED ISSUE #7432: Add an empty default value to the select components for trigger step in workflow visualizer
Currently, the selects show a value but they don't have one actually. We should have a default "None" value for these fields.

image

The file to update: https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/workflow/components/WorkflowEditTriggerForm.tsx.

Resources: 

- https://stackoverflow.com/questions/8605516/set-the-select-option-as-blank-as-default-in-html-select-element sent by @martmull

### PR DESCRIPTION
**Pull request by AndrewHamal**
## What does this PR do?
Shows "Select an option" as a default selector on the select component for the trigger step in the workflow visualizer

Fixes #7432

Screenshot 2024-10-20 at 12 48 39 AM
Screenshot 2024-10-20 at 12 48 50 AM

### CODE REVIEW

**Comment by lucasbordeau** [comment]
@Bonapara I think we want something like No value in our select field type ?

**Comment by AndrewHamal** [comment]
@Bonapara you mean with out anything remove "Select an option" and have empty nothing selected at first?

**Comment by Bonapara** [comment]
After further thought, I think it's okay to have the empty state only when no object has been selected "Select an Option", and to only have the ability to switch between objects without the option to reset to null/select an Option when one gets selected.

**Comment by Devessier** [comment]
Hello @AndrewHamal, I pushed an update to your code to use pre-existing solutions I didn't know about when I created the issue. You will get the OSS points. Thanks for your contribution.

**Review by Devessier — APPROVED** [review]
We can merge.

**Pull request merged**
