### PR TITLE
fix: dropdown max-height and padding bottom

### LINKED ISSUE #6105: Dropdowns should have a max-height and a scroll bar
I was shadowing a client that had created lots of field and the Filter dropdown was bigger than their screen's height.
We might (or might not?) want to set a max-height.
Also we want to make sure there's a scroll bar upon scroll (when I added a max-height directly in Chrome, the dropdown become scrollable but I couldn't see any scroll bar)

cc @Bonapara for recommandation

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
Fixes: #6105 

Also fixed side effect due to previous PR:

[Screencast from 2024-10-29 13-54-44.webm](https://github.com/user-attachments/assets/f15db853-ca1c-4be8-9362-610122c4d988)

### CODE REVIEW

**Comment by harshrajeevsingh** [comment]
@martmull ready for review :)

**Review by martmull — APPROVED** [review]
LGTM, far more simple than previous solution, thank you. I approve, but I will also let @lucasbordeau review that code

**Comment by lucasbordeau** [comment]
LGTM

**Comment by lucasbordeau** [comment]
This is causing other issues, we'll see how to have our dropdown generic component properly handle scroll in another issue.

**Pull request merged**
