### PR TITLE
Fixed: Inline Field data overflowing on Kanban cards

### LINKED ISSUE #6000: Inline Field data overflowing on Kanban cards
# Current Behavior

The inline field data overflows on Kanban cards.

image

# Desired Behavior

The content should be cropped with ellipses to prevent overflow.

### PR DESCRIPTION
**Pull request by rksingh2001**
Fixes: #6000 
image

### CODE REVIEW

**Review by charlesBochet — COMMENTED** [review]
This masWidth approach is working but I wonder if we can find a simpler solution that would avoid passing maxWidth.

Let's discuss this with @lucasbordeau tomorrow

**Comment by rksingh2001** [comment]
> This masWidth approach is working but I wonder if we can find a simpler solution that would avoid passing maxWidth.
> 
> Let's discuss this with @lucasbordeau tomorrow

Sure, let me know if there is a simpler solution, will change the implementaion, although I tried and unable to make it work, also some ellipsis implementation on other pages in this codebase, they were also passing max width from props.

**Comment by lucasbordeau** [comment]
Closing this PR as it has already been fixed by a recent change.

Also for reference, this approach is not optimal as we should only rely on CSS for detecting the container width and not telling it max width. 

We have it in the codebase but ideally we shouldn't.

**Comment by lucasbordeau** [comment]
For reference this issue was fixed by https://github.com/twentyhq/twenty/pull/6061

**Pull request closed without merging**
