### PR TITLE
#6094 Prevent creating a custom field with an existing name

### LINKED ISSUE #6094: Prevent creating a custom field with an existing name
## Scope & Context

Field creation in data model.

## Current behavior

We can input whatever name we want in the name input in field creation form.

## Expected behavior

We want the field to become in error state with a message displayed that says that this name is already taken.

We should also deactivate the Save button to prevent from sending anything to the backend which would throw an error anyway.

### PR DESCRIPTION
**Pull request by deval2498**
Fixes #6094 
Description: Added logic inside SettingsObjectNewFieldStep2.tsx to prevent form submission
Current Behaviours:
Screenshot 2024-07-03 at 1 45 31 PM

### CODE REVIEW

**Review by ijreilly — COMMENTED** [review]
Thank you for your contribution @deval2498! 
The code is functional but I added a few indications to try to follow our best practices!

**Comment by deval2498** [comment]
On it. Thanks for this review

**Comment by deval2498** [comment]
Updated the code as per the guidelines. Updated:
1. FieldMetadataItemSchema to accept an array of strings, so that we can throw an error directly from zod resolver
2. Used inbuilt error controls of Controller in SettingsDataModelFieldAboutForm
3. Updated types to incorporate the changes made to FieldMetadataItemSchema

**Comment by ijreilly** [comment]
great work @deval2498 , thanks for your contribution :) i allowed myself to add some minor improvements.
I think this also fixes #5428 :) great

**Comment by deval2498** [comment]
Will take a look and update you on this, thanks for helping here

**Comment by Bonapara** [comment]
Hi @deval2498, thanks for the PR! Could you remove the red error icon on the right side of the field and add a `Border Danger` around the field?

CleanShot 2024-07-15 at 17 26 41

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3007-69739&t=hrDkyWQ3cs5iGjno-11

**Comment by deval2498** [comment]
@ijreilly color exists in theme.border.color.danger

**Review by ijreilly — APPROVED** [review]
great work @deval2498 this will be very useful ! :)

**Pull request merged**
