### PR TITLE
Added ability to search objects and fields

### LINKED ISSUE #6770: Add ability to search objects and fields
# Current Behavior

Today, searching for objects and fields in the data model settings is impossible. This makes it difficult for users to find what they're looking for when there are many items.

CleanShot 2024-08-28 at 16 27 28

# Desired Behavior

We want to introduce an input field to search these tables. It should have an 8px bottom padding and use the standard input component:

image

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-129115&t=DznyWuGmdqYLC3zq-11

### PR DESCRIPTION
**Pull request by ehconitin**
Closes #6770 

https://github.com/user-attachments/assets/e3134389-30d2-48c8-bbca-34209d5ae66d

### CODE REVIEW

**Comment by ijreilly** [comment]
great work @ehconitin !
I would just like to check a couple things with product (@Bonapara ):

- in this search the fields are searchable by label or type (text, address..). is this what we want? or shall we stick to label?
- an entire new search input component is introduced here. Can you think of a different place in the product where the exact same design is in use (I can't)?

**Comment by ehconitin** [comment]
It could be used in #6700
So there are like 3 places including #6700 and this pr where it could be used.
Although folder placement and name scheme is debatable.
For now I just kept in common component folder.
Let me know where to place it.
Thanks.

**Comment by Bonapara** [comment]
@ehconitin, on the video, the search input background is white, is it just on your screen?

For the search, I think we can keep both (label & type) indeed @ijreilly 

In Figma, this search component is just an "input" component. However, do you need one for the code? This component will primarily be used in the Settings for now indeed, for #6700 and Settings table search

**Comment by ehconitin** [comment]
@Bonapara 
yep it was transparent haha. Good eyes!
corrected it
image

**Comment by Bonapara** [comment]
Out of curiosity, why was it possible that it was transparent? It's should not be an option of the input component: https://storybook.twenty.com/?path=/story/ui-input-textinput--filled

**Comment by ehconitin** [comment]
@Bonapara 
Oops mb, i styled a new input element and did not used the existing one.
Done!
now its cleaner, no need of a new component SearchInput
Thanks

**Review by ijreilly — APPROVED** [review]

**Comment by ijreilly** [comment]
thanks @ehconitin for being so reactive on this one! :)

**Pull request merged**
