### PR TITLE
minor fix - email thread reply button stylings/corrections

### LINKED ISSUE #7155: Email thread action bar UX improvements
# Current behavior

The action bar on the email thread is too big and lacks a top border

CleanShot 2024-09-19 at 09 35 48

# Desired Behavior

Use the same action bar that we will use for #7069. (Today the email thread action bar is too big and lacks a top border)

image

### PR DESCRIPTION
**Pull request by ehconitin**
fixes #7155

### CODE REVIEW

**Comment by ehconitin** [comment]
@bosiraphael 
is this change okay? for mobile devices I increased the height of buttonContainer, before it was misaligned.
or is there a more elegant way to do this?

**Comment by bosiraphael** [comment]
@ehconitin Hello ! I think the right approach for the mobile isn't to increase the button size, but to fix the fact that the right drawer shouldn't take the whole screen on mobile and should not extend on top of the bottom navbar.

**Comment by ehconitin** [comment]
Ah, make sense. Will make the change.
Thanks

**Comment by ehconitin** [comment]
@bosiraphael 
How about this? we would have a height state of navigationDrawer handy at all times.

**Comment by bosiraphael** [comment]
@ehconitin I don't think this is the right approach. The issue is coming from the `RightDrawer` component style `packages/twenty-front/src/modules/ui/layout/right-drawer/components/RightDrawer.tsx` ;) maybe you can take a look.

**Comment by ehconitin** [comment]
@bosiraphael got it!
Will have a look.

**Comment by ehconitin** [comment]
@bosiraphael haha, it was a one line change.

**Review by bosiraphael — APPROVED** [review]
LGTM ! Thank you @ehconitin ! Now it looks good :)

**Pull request merged**
