### PR TITLE
feat: Set preselect field type on new field of object page

### PR DESCRIPTION
**Pull request by Us3r-gitHub**
#5661

### CODE REVIEW

**Review by lucasbordeau — COMMENTED** [review]
To complete this issue, we should have a way to know that we're creating a select field because we want to create board view, and then go back directly to the board view when we click on "Save" in the field creation form, and not to the settings field list, as it would be the case normally.

**Comment by Us3r-gitHub** [comment]
Thank you for your feedback
> go back directly to the board view when we click on "Save"

It makes sense.

By the way, could we implement react router history to address this?
Or perhaps use `navigationMemorizedUrlState`?

**Comment by lucasbordeau** [comment]
> By the way, could we implement react router history to address this? Or perhaps use `navigationMemorizedUrlState`?

Let's use `setNavigationMemorizedUrl` yes !

**Comment by FelixMalfait** [comment]
Hey sorry for the very long delay. I removed "navigateBack" not because it wasn't properly implemented but because we're careful not to bloat the API with edges cases and this implem seemed to specific to our use-case and not worth the complexity it adds in code.

**Review by FelixMalfait — APPROVED** [review]
Thanks a lot for your contribution! Sorry for the long delay to review!

**Pull request merged**
