### PR TITLE
fix: record object chip background color when idle (not hovered)

### LINKED ISSUE #4651: Update Card Name Chip Design on Kanban Views
# Current behavior

The Kanban card name chips are `plain` and darker when being hovered.

image

# Desired Behavior

The kanban card name chip should be transparent when not hovered, and `Transparent/Light` when hovered

image

CleanShot 2024-03-25 at 19 02 11

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=24955-194300&mode=design&t=xKOKPr1F1nQcJSIR-11

### PR DESCRIPTION
**Pull request by emadbaqeri**
Fixes #4651 

https://github.com/twentyhq/twenty/assets/50639499/c4b604a1-4e73-422a-bc13-a2764f564a75

### CODE REVIEW

**Comment by emadbaqeri** [comment]
> StyledBoardCardHeader

I not sure I understand this so I'm asking a dummy question, you mean I should do something like this?

```ts
enum RecordChipVariant = {
	Regular = 'regular',
	Transparent = 'transparent',
}

<RecordChip variant={RecordChipVariant.Transparent} />
```
And this way we can control the `RecordChip` variant property from outside and this should be better I think as you mentioned.

**Comment by FelixMalfait** [comment]
Yes that's how I would have done it too! That way we can follow the design that's on the issue

**Comment by emadbaqeri** [comment]
> Yes that's how I would have done it too! That way we can follow the design that's on the issue

I've updated the `RecordChip` component to get a variant prop as you said, now ready to merge :)

**Review by bosiraphael — APPROVED** [review]
LGTM, thank you for contributing @emadbaqeri :)

**Review by FelixMalfait — DISMISSED** [review]
You should pass the variant in StyledBoardCardHeader, not change the default variant for all RecordChips :)
(look at the design on the issue, it's only the header of the card)

**Comment by ijreilly** [comment]
@FelixMalfait is it ok for you now?

**Review by ijreilly — APPROVED** [review]

**Pull request merged**
