### PR TITLE
feat (improvement): update the createOneObjectMetaItem

### LINKED ISSUE #5278: Object creation takes too long
# Description

Creating a custom object takes around 4s. If you mistakenly click the create button twice, an "object already exists" error will appear.

https://github.com/twentyhq/twenty/assets/19412894/06a95c7b-f5de-4ac0-80d8-6ad5d33d24fc

# Desired Behavior

- We want to show a loading indicator in the button after clicking. (See below)
- We want to prevent the "this object already exists" error from appearing when the button is clicked twice.
- We should also cut down the loading time.

Button loader:

https://github.com/twentyhq/twenty/assets/19412894/53f51de3-2ec2-4320-a972-aa6e6019bda5

### PR DESCRIPTION
**Pull request by pacyL2K19**
# This PR

- Fix #5278 
- Updates the implementation of the `createOneObjectMataItem` hook to reduce the number of api calls
- Users can now navigate to the newly created object first and the graphql api calls to cache data are happening in the background - this will improve the user experience and reduce the create object api call time by >2
Screenshot 2024-05-30 at 12 00 15

In the issue description, it also suggested to have a loading indicator while creating the object, it seems like on #5352 we adopted to disable it while creating the object - which looks good to me and it works, let me know if we still need the loading indicator instead @Bonapara 

Looking forward to getting your feedback
cc: @charlesBochet

### CODE REVIEW

**Review by thomtrp — COMMENTED** [review]
@Bonapara can you test and tell if we still need other improvements?

**Comment by Bonapara** [comment]
Hi @pacyL2K19,

Thanks for the PR 🙌. Disabling the button instead of setting a loader could work, but could you deactivate the `Save` button? Clicking it twice still triggers a `QueryFailedError`.

**Comment by pacyL2K19** [comment]
> Hi @pacyL2K19,
> 
> Thanks for the PR 🙌. Disabling the button instead of setting a loader could work, but could you deactivate the `Save` button? Clicking it twice still triggers a `QueryFailedError`.

Hi @Bonapara 
The current behavior already disables the `Save` button, no way one can click on it anymore, here is the record:
https://www.loom.com/share/cccaaf95595b47e580fee1d648601953?sid=ac5a7032-5c2a-490e-b143-97781f0ddd30
Is there any other work that needs to be done on this Button? Please let me know

**Review by thomtrp — APPROVED** [review]
@pacyL2K19 thanks for your contribution ! 🔥 

The logic is already there to disable the button indeed.

Closing this issue @Bonapara !

**Pull request merged**
