### PR TITLE
feat: improved table scrolling

### LINKED ISSUE #7515: Improve scrolling in the table
## Bug Description

- In Tables, when scrolled the animation is not smooth and always snaps to cursor to follow it instead of making a smooth transition
- This is very noticeable in mobile and can be frustating at times as if the user wants to read the value of first column then it is quite difficult to adjust the scoll accordingly

## Current Behaviour

https://github.com/user-attachments/assets/f4775401-55b7-4c9f-9e57-3d7351c0f2de

https://github.com/user-attachments/assets/b9ae180e-f590-4d64-a996-0bb61954b0e6

## Expected behavior

A smooth transition should be occupied when scrolled

### PR DESCRIPTION
**Pull request by Khaan25**
This PR fixes twentyhq/twenty#7515

Demo:

https://github.com/user-attachments/assets/8181cda0-3b77-43bf-b605-ba43f2290b84

### CODE REVIEW

**Comment by Bonapara** [comment]
Hi @Khaan25 we want to keep the following behavior on mobile: 
image

**Comment by Khaan25** [comment]
Alright. Will do it

**Comment by Khaan25** [comment]
https://github.com/user-attachments/assets/0f6514e8-2f92-4ca9-9faa-789ac8217bb6



@Bonapara 🤝

**Comment by Khaan25** [comment]
@Bonapara Can you please close this? I can see another issue open, I cna work on that?

**Comment by Bonapara** [comment]
@Khaan25, this looks great! Can you make this two fixes?

### Desired:

The shape of mobile chips should be square:

image

### Current:

the chip has an extra right padding

CleanShot 2024-10-16 at 17 47 59

---

Also can you add a small margin at the right of the chips & + button?

### Desired

CleanShot 2024-10-16 at 17 49 15

### Current

(No margin right)

CleanShot 2024-10-16 at 17 50 11

**Comment by Khaan25** [comment]
Sure. I was thinking to ask you about this - Great you brought it up 💪

**Comment by Khaan25** [comment]
One more question, Can I unassign myself from the Issue and assign myself to any other issue?

Will I get points for this PR as well or first finish it then move on?

**Comment by Bonapara** [comment]
We should finish so we don't lose track of things. Additionally, the bot doesn't allow assigning oss.gg issues to someone if they are already assigned to another issue..

**Comment by Khaan25** [comment]
RIght. It was a simple CSS fix so I thought I could get points for that one as well while you review this one :)

Anyway, Thank you. It's my first time contributing open source

**Comment by Bonapara** [comment]
If it's a minor CSS fix, let's make an exception. Tag me, and I'll assign it to you if no one else is assigned ;)

**Comment by Khaan25** [comment]
But now it's too late, someone assign himself 😄 - I'll tag you next time. Thank you for the support

**Comment by Khaan25** [comment]
Can you assign this to me? https://github.com/twentyhq/twenty/issues/7757

**Comment by Khaan25** [comment]
Can you assign this to me? https://github.com/twentyhq/twenty/issues/7757

**Comment by Bonapara** [comment]
Sorry, I wasn't quick enough, which is why it's not that simple 😅

**Comment by Khaan25** [comment]
You can unassign him and assign me? 😂

P.S. wrapping up this one as well

**Comment by Bonapara** [comment]
That would not be fair :)

**Comment by Khaan25** [comment]
Quick question, if you don't mind, How do I see the issues that have points and are not assigned? Can't figure that out from the search :(

Have to search from the long list.

**Comment by Bonapara** [comment]
https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%95%B9%EF%B8%8F+oss.gg%22+no%3Aassignee

**Comment by Khaan25** [comment]
Can you please assign this to me? #4588

**Comment by Bonapara** [comment]
You need to comment on it

**Comment by Khaan25** [comment]
it says that I'm already assigned this issue and am about to finish but someone might assign to himself.

**Comment by Bonapara** [comment]
Assigned!

**Comment by Khaan25** [comment]
There you go:
https://github.com/user-attachments/assets/4e15ab0a-7edc-4b8e-a3d5-dd2eadadefbe

**Comment by Khaan25** [comment]
By the way, Thank you for your support. Means a lot

**Comment by Bonapara** [comment]
Still have a glitch on desktop, don't you?

https://github.com/user-attachments/assets/4a5a8955-d23e-489e-98cd-28157adfdf98

**Comment by Khaan25** [comment]
I'm not facing that issue. Would you mind trying out again?

**Comment by Bonapara** [comment]
Yes, the first column shakes when I start scrolling

https://github.com/user-attachments/assets/57810840-5151-49c1-bff8-9ac1c9daf0de

**Comment by Khaan25** [comment]
Strange, can't reproduce it on my end. I've pushed another change, maybe that would help out.

Is there any chance of deploying this branch on Vercel or some temporary link?

**Comment by Khaan25** [comment]
https://github.com/user-attachments/assets/4e430b19-d3d2-49b1-945c-4b20bd6039bd

**Comment by Bonapara** [comment]
@lucasbordeau do you have the glitch too?

**Comment by Khaan25** [comment]
Hey @Bonapara, I was thinking if you could assign me points for this and I can move on fixing other bugs and issues?

If any problem in this issue, I'll be here to resolve? What do you think? I got the understanding of the codebase and I believe I can solve few bugs :)

**Comment by Bonapara** [comment]
@Khaan25 unfortunatly, there is still some bugs one this one. Can you activate the "Toggle Device Toolbar" `⌘⇧M`

CleanShot 2024-10-18 at 10 40 37

in mobile we can still see the chip name, and the animation is still bumpy.

https://github.com/user-attachments/assets/6ee897b9-f9b6-42ec-8239-e752628dbd56

You can fix the chips & I'll let @lucasbordeau guide you for the animation

**Comment by Khaan25** [comment]
Perfect. Sounds great. I'll address the chip issue.

**Comment by lucasbordeau** [comment]
@Bonapara We cannot avoid the bump effect with our current implementation. Because the browser cannot give us a predictable scroll position in real time, it's a constraint we have to deal with.

I think we'll have to see for this bump effect with @charlesBochet let's not try to fix it in this PR.

**Comment by Bonapara** [comment]
Ok so @Khaan25 there is only the chip issue to fix and we're good!

**Comment by Khaan25** [comment]
Perfect. Gimme few minutes

**Comment by Khaan25** [comment]
Hey, could you review it? I can work on other issues?

**Comment by Khaan25** [comment]
Hey hey, any update on this? :)

**Comment by Khaan25** [comment]
Any update :)

**Comment by Bonapara** [comment]
@lucasbordeau will review it today @Khaan25 ;)

**Review by lucasbordeau — APPROVED** [review]

**Comment by Khaan25** [comment]
@Bonapara Finally it's done 🎉:)

**Comment by Khaan25** [comment]
@Bonapara, could you please assign me points for this one? :)

**Comment by Devessier** [comment]
I'm unsure if we want to rely on the `data-testid` attributes for styling. It should be used only in e2e tests.

**Comment by lucasbordeau** [comment]
@Bonapara Is it ok for you ?

**Comment by Bonapara** [comment]
Yes @lucasbordeau, I think it was!

**Review by lucasbordeau — APPROVED** [review]

**Comment by lucasbordeau** [comment]
Follow-up issue : https://github.com/twentyhq/twenty/issues/8307

**Pull request merged**
