### PR TITLE
Workspace Schema Extension Module (Schema First Approach)

### PR DESCRIPTION
**Pull request by alias404**
Implemented Workspace Schema Extension module. This enables the creation of custom Schemas, including personalized Queries and Mutations.

To add a custom GraphQL Schema:

- Create a `.graphql` file within the `workspace-schema-extension/typedefs` directory.
- Develop a Resolver service for it, by Implementing the `ExtensionResolverService` interface. (Refer to `workspace-schema-extension/resolvers/sample.extension.service.ts`)
- Utilize the `ExtensionResolver` decorator to designate the root type of Resolver (**Query**, **Mutation**, or **GraphQL Object**) for each method in the extension service.
- Include the service within the `ExtensionResolverServices` array in the `workspace-schema-extension/resolvers/index.js` file.
- That's it! Your Extended schema is now accessible.

In the image below, you'll observe the `bonjour` GraphQL query in action, configured within the `sample.extension.service.ts` file.

image

### CODE REVIEW

**Comment by DGamer007** [comment]
Your approach sounds more precise. I did not consider the seperation for custom code and core logic. Actually the twenty-app approach is far better than what I have proposed. I think I understand the terminology and I am definitely up for making changes.

**Comment by FelixMalfait** [comment]
Thanks @DGamer007 fyi here's an abandoned PR that goes into that direction if you want to take over, leveraging NestJS Decorators https://github.com/twentyhq/twenty/pull/4700

The idea is that long-term we'll have the core engine dedicated to transverse function (e.g. data modelling layer, layout layer, etc.), and then all business modules (internal or external) will be built as apps. The more we progress the more business apps will be just a folder of config files (you will be able to insert custom frontend/backend code but we should provide advanced layout/data modelling capabilities so many business use-cases could be tackled through a low-code/config-driven approach once the engine is powerful enough)

**Comment by FelixMalfait** [comment]
I think most of the PR was okay (if you take into account Jeremy's comment). This was just a first step in a multiple step refactoring to let emerge that app concept which will become crucial to Twenty

**Comment by charlesBochet** [comment]
Happy to assist into merging this work, this will help a lot people to add their custom code to Twenty

**Comment by DGamer007** [comment]
> Thanks @DGamer007 fyi here's an abandoned PR that goes into that direction if you want to take over it, leveraging NestJS Decorators https://github.com/twentyhq/twenty/pull/4700
> 
> 
> 
> The idea is that long-term we'll have the core engine dedicated to transverse function (e.g. data modelling layer, layout layer, etc.), and then all business modules (internal or external) will be built as apps. The more we progress the more business apps will be just a folder of config files (you will be able to insert custom frontend/backend code but we should provide advanced layout/data modelling capabilities so many business use-cases could be tackled through a low-code/config-driven approach once the engine is powerful enough)

Thanks man ! Will definitely look into this PR.

**Comment by DGamer007** [comment]
> Happy to assist into merging this work, this will help a lot people to add their custom code to Twenty

Sounds awesome ! Thanks.

**Comment by FelixMalfait** [comment]
Closing this for now but happy to support you if you raise another PR more inspired by the annotation/app system. Thanks a lot!!!

**Pull request closed without merging**
