### PR TITLE
Implement a masked currency input

### LINKED ISSUE #4358: Implement a masked currency input
## Scope & Context

Currency input.

## Current behavior

The input only supports raw text.

## Expected behavior

We want a masked input that adapts to the currency : 

currency_input_demo

We should benchmark existing libraries while keeping in mind that : 
- The masked input should handle the different currencies we have : USD, EUR, YUAN, ... Because every currency behaves differently with thousands/hundreds separators.

Resources : 
- https://www.nicknish.co/blog/react-currency-input
- https://www.npmjs.com/package/@react-input/mask
- https://sanniassin.github.io/react-input-mask/demo.html

### PR DESCRIPTION
**Pull request by gitstart-twenty**
### Description
Implement a masked currency input

### Refs
#4358 

### Demo
https://jam.dev/c/93da117c-b193-488f-b9f9-906b33ac5190

Fixes #4358

### CODE REVIEW

**Comment by FelixMalfait** [comment]
Could you please check why it's not possible to type a decimal number? 2 decimals should be allowed (for most people it will stay like it is, we don't want to display ".00" obviously - but maybe some people sell low cost product and care about the decimals)

**Comment by FelixMalfait** [comment]
The rest looks good to me!

**Comment by gitstart-twenty** [comment]
Hey @FelixMalfait 
The issue is the check for whether the value can be case as an integer

`packages/twenty-front/src/modules/object-record/record-field/meta-types/hooks/useCurrencyField.ts`
Screenshot 2024-04-18 at 13 56 22

`packages/twenty-front/src/utils/cast-as-integer-or-null.ts`
Screenshot 2024-04-18 at 13 55 15

**Review by FelixMalfait — APPROVED** [review]
Thanks!

**Pull request merged**
