### PR TITLE
Fix: 814 - Drag opportunity under new button

### LINKED ISSUE #814: I can drag an opportunity card under the "New" button
Currently, if you drop the card below the new, it comes back to its original column.
Instead, we would like the card to go the to target column, even if it's dropped below the "add new" button

https://github.com/twentyhq/twenty/assets/19412894/dfec095e-4250-4e01-8fe3-3fc66d579c26

### PR DESCRIPTION
**Pull request by brendanlaschke**
Use full column height (also under new button) for the drop area.

closes #814

### CODE REVIEW

**Comment by charlesBochet** [comment]
Thank you for the help!
Your feature work as long as the pipeline view does not scroll. I've tested with 6+ cards in a column and the column does not extend below the scroll view:
image

We would need to fix this before merge!

**Comment by brendanlaschke** [comment]
> Thank you for the help! Your feature work as long as the pipeline view does not scroll. I've tested with 6+ cards in a column and the column does not extend below the scroll view: image
> 
> We would need to fix this before merging!


This wasn't working before either ;) but I fixed it to work like in the Asana Board where each column scrolls independent ...

**Comment by FelixMalfait** [comment]
Thanks a lot @brendanlaschke 🙌

**Comment by brendanlaschke** [comment]
I found another issue with that: 


Bildschirmfoto 2023-07-24 um 09 48 34

But im not sure on how one could solve this ...

**Comment by brendanlaschke** [comment]
Opened a new issue for the Datepicker problems as this should not be covered here (#907)

**Comment by charlesBochet** [comment]
@brendanlaschke We have discuss several time this issue with our product team and engineering team, we will do the following implementation: https://github.com/twentyhq/twenty/pull/970/files

Thanks for giving a shot, this has raised a lot of interesting discussions about board behavior

**Pull request closed without merging**
