### PR TITLE
Add a ⏎ shortcut on Select options

### LINKED ISSUE #5540: Add a ⏎ shortcut on Select options
# Desired Behavior

When I type an `option value` while creating a new `Select Field`, pressing `⏎` should validate the option, create a new one, and move the focus to it.

CleanShot 2024-05-22 at 18 12 11

### PR DESCRIPTION
**Pull request by RamK777-stack**
fixes #5540 

Added onkeyDown to 
1. Create new option and 
2. Move focus to it.

[screen-capture (6).webm](https://github.com/twentyhq/twenty/assets/69167444/ede54ad8-22db-4b09-9617-4d999c6c08c7)

### CODE REVIEW

**Comment by lucasbordeau** [comment]
Hi @RamK777-stack, thanks for contributing !

Please could you look at this other PR which is a very similar issue : https://github.com/twentyhq/twenty/pull/5576

See this comment on how to create a hotkey in twenty : https://github.com/twentyhq/twenty/pull/5576#issuecomment-2134852669

Also I recommend using `usePreviousHotkeyScope()` that provides an API that allows to put a hotkey scope when something takes the focus, and then to put the previous hotkey scope back when exiting the focus.

Here for your case, the component is mounted when we change page in SettingsObjectNewFieldStep2, so since there is no modal behavior and it's depending only on a component being mounter, you can put usePreviousHotkeyScope() is a useEffect that calls goBackToPreviousHotkeyScope() in the return of the useEffect.

**Comment by lucasbordeau** [comment]
The documentation has been updated to explain this more in depth : https://docs.twenty.com/contributor/frontend/hotkeys

**Comment by RamK777-stack** [comment]
@lucasbordeau I'm having trouble understanding the hotKeyScope variable. I checked in other places. they get these 

```typescript
    useScopedHotkeys(
      Key.Enter,
      () => {
        handleKeyDown?.();
      },
      InputHotkeyScope.TextInput,
      [handleKeyDown],
    );
``` 
   
```typescript
<StyledOptionInput
          value={option.label}
          onChange={(label) =>
            onChange({
              ...option,
              label,
              value: getOptionValueFromLabel(label),
            })
          }
          // onKeyDown={(event: React.KeyboardEvent) => {
          //   if (event.key === 'Enter') {
          //     handleKeyDown?.();
          //   }
          // }}
          RightIcon={isDefault ? IconCheck : undefined}
          ref={ref}
        />
``` 

The useScopedHotkeys callback event isn't firing, and I suspect it's due to the scope. When I pass a different scope, such as 'hotkey-scope', the Enter key triggers the callback, but it doesn't work within the text field.

**Comment by lucasbordeau** [comment]
@RamK777-stack I suggest you use the hotkey scope debug mode by setting this to true : 

```tsx
export const DEBUG_HOTKEY_SCOPE = false;
```

In `useScopedHotkeyCallback`, you will then see what the current hotkey scope is.

**Review by lucasbordeau — APPROVED** [review]
@RamK777-stack Here's what I did for reference : 
- Disabled hotkey listener on text input component
- Added a useScopedHotkeys on 'app' hotkey scope
- Added a focused prop on the option row
- Added a state to know which option id has the focus
- Removed forwardRef : we try to avoid it as it's difficult to maintain and indicates that we are maybe trying to force something we could do with only states.
- Removed ref arrays (generally not a good pattern)

**Comment by RamK777-stack** [comment]
Thanks 😊 @lucasbordeau I just saw the changes. I learned a lot while contributing to this issue and look forward to contributing more in the future. 🚀

**Pull request merged**
