### PR TITLE
UI Component docs (Display & Feedback components)

### PR DESCRIPTION
**Pull request by nimraahmed**
Documentation for display and feedback UI components. 

(Would it be better to have external CSS instead of inline styling?)

cc: @bosiraphael @FelixMalfait

### CODE REVIEW

**Comment by charlesBochet** [comment]
@nimraahmed Thank you
- Yes, let's avoid adding extra divs to wrap the components, especially using style={{ }} property, it's fine to see the "raw" behavior of the component without container. If it's not good, the component itself should be improved

- <p style={{ display: inline-bock }}> is actually a <span>
- I am not a big fan of using the tabs to display Examples ; as Tabs are not well delimited, it's not a good support for long content. I recommand moving it in a section below every time: #Component  ##Usage (+ Props) ## Example
- IconAddressBook => Icons. we should add a section that would expose ALL icons and not only IconAddressBook

**Comment by FelixMalfait** [comment]
Can we move this to its own sidebar like userguide? The UI components will move to their own package and be shared by contributors (internal usage) as well as external (to create apps, plugins, etc.). Thanks!

**Comment by nimraahmed** [comment]
Got it, I'll do that

**Comment by charlesBochet** [comment]
@nimraahmed Any update on this one ? :)

**Comment by nimraahmed** [comment]
@charlesBochet made changes based on the feedback + added docs for some input components.

P.S. Is the button.mdx too long/should it be split somehow?

**Comment by charlesBochet** [comment]
That's better @nimraahmed!
Yes I think we should split the Button file into multiple ones.

We are still missing some base css (ImageUpload looks broken, ColorScheme too)
image
We should not see a component folder

Could we hide the TabBar within Sandpack?
image

Then, we should pay attention to our way of doing to be uniform:
- some component code have line returns in the code between import and component, others don't have. One empty line would be perfect
- SoonPill does not have a Props table; I think we should have an empty table state in case
- Icons start with an explanation, then we have the component, I would love to have something with the same structure everywhere: Intro, Usage / Props, Example for example

**Comment by charlesBochet** [comment]
@nimraahmed It's actually not that bad with the right navigation:
image

My biggest feedback right now is that we should make sure we have the default fonts and css, it's look weird without it!
Then I'll be confortable to merge it and iterate from there :)

**Comment by nimraahmed** [comment]
@charlesBochet CSS added

**Comment by charlesBochet** [comment]
@nimraahmed Let's merge and keep improving it!

**Review by charlesBochet — APPROVED** [review]
Thank you!

**Pull request merged**
