### PR TITLE
Added hover on Show Person Avatar #1149

### PR DESCRIPTION
**Pull request by Bhavish5**
Hey, I added hover on show person avatar.

### CODE REVIEW

**Review by Weiko — COMMENTED** [review]
Hi @Bhavish5!
Can you check the task list on the ticket here https://github.com/twentyhq/twenty/issues/1149?
We would like to use an extra props for that behaviour because the Avatar component is not only used on the show person page and sometimes it's not clickable.

See video below where it should not have the hover effect.

https://github.com/twentyhq/twenty/assets/1834158/d6c47173-508e-4901-880f-d5e1b8a8b73f

Thanks!

**Review by Bhavish5 — COMMENTED** [review]
Hey, I updated the changes, now only person show and company icons will change on hover. But the Front/Run storybook tests are timing out, not really sure what that is, can you take a look? Thanks.

**Comment by Weiko** [comment]
Hi @Bhavish5, can you rebase with main? This should be fixed.

**Comment by Bhavish5** [comment]
Got it, all checks have been passed, can you review it for the merge? Thanks a lot for the help!

**Comment by Bhavish5** [comment]
@Weiko @charlesBochet @Bonapara Can you merge the code all checks have been passed. Thanks for the help!

**Comment by Bhavish5** [comment]
Hey @Weiko, all checks have been passed can you merge my code. Thanks a lot for the support!

**Comment by Weiko** [comment]
Hi @Bhavish5, as mentioned in my comment above we had some implementations in mind already, you can find the tasks in the issue description https://github.com/twentyhq/twenty/issues/1149
Since those tasks were suggested by @charlesBochet, I'll let him decide if we can merge as it is 🙂 
Thanks for your contribution!

**Comment by Weiko** [comment]
Just checked offline with @charlesBochet and we would prefer to follow the suggested implementation, this will allow us to have more flexibility. Please let us know if you have any question!

**Comment by Bhavish5** [comment]
Okay, I'm new to open source, so I was not really sure what to do, I'll try to implement it as mentioned in the issue #1149 . Thanks a lot for the support, it was really helpful!

**Comment by Weiko** [comment]
No worries @Bhavish5, good luck! 💪

**Comment by charlesBochet** [comment]
@Bhavish5 We are trying to make sure to not keep staled work (> 1 week) in the PR list (it would be to hard to maintain if we get dozens of PRs in the list + discouraging for new joiners)

I'm closing this PR, please re-open it as soon as you are ready, we will review it :)

**Pull request closed without merging**
