### PR TITLE
update: Default Demo Login Credentials to noah@demo.dev

### LINKED ISSUE #7304: Set default demo account to noah@demo.dev
# Current behavior

Today, the default account on demo.twenty.com is set to tim@apple.dev, like we do in local

https://github.com/user-attachments/assets/2f5d7f44-79af-494a-a265-61ac7c04cd69

# Desired Behavior

We want the default demo default login to be set to:

email: noah@demo.dev
password: Applecar2025

### PR DESCRIPTION
**Pull request by vijaysingh2219**
This PR updates the default login credentials for the demo environment. The current default is set to tim@apple.dev, and we want to change it to:

Email: `noah@demo.dev`
Password: `Applecar2025`

Changes:

- Updated default demo login email from tim@apple.dev to noah@demo.dev

Resolves #7304

### CODE REVIEW

**Comment by vijaysingh2219** [comment]
@Bonapara Please review when you get a chance.

**Review by Weiko — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution. We still want to keep tim@apple.dev here though. This is because Demo is not automatically seeded so this account will be missing and login won't work in the current state, I don't think this is the correct way to do this.
We could use an env variable for that such as SIGN_IN_PREFILLED_DEFAULT_LOGIN. You can check how it's done with SIGN_IN_PREFILLED.
(cc @charlesBochet)

**Comment by vijaysingh2219** [comment]
Thanks for your input, @Weiko! I've now adjusted the code to ensure `tim@apple.dev` is used as the default login, as you suggested. The environment variable `SIGN_IN_PREFILLED_DEFAULT_LOGIN` is also included for flexibility, but it defaults to `tim@apple.dev` if not provided. Similarly, the password is prefilled with `Applecar2025` or `SIGN_IN_PREFILLED_DEFAULT_PASSWORD` when available.

**Comment by FelixMalfait** [comment]
Hey I'm sorry the issue wasn't clear. We actually transitioned to tim@apple.dev to be prefilled for demo but I hadn't updated the README yet because the server hadn't been deployed yet. Thanks a lot for the attempt!

**Pull request merged**
